mattermost-community/focalboard

- server/app/app.go
- server/app/auth.go
- server/app/blocks_test.go
- server/auth/auth.go
- server/server/server.go
- server/ws/websockets.go
- webapp/src/octoListener.ts
Added an auth op to websocket. Main structural changes:
* Moved GetSession from App into a new Auth class
* Pass Auth class to webSocket and App
* OctoListener passes session token on open
This probably needs refactoring in the future, but I can see more code going into an auth layer above app later on.
> Websocket auth

- README.md
Just a thought on positioning, we can always change it,
> Proposing tweak for SEO

- responsibile_disclosure_policy.md
Community is asking for how to report security issues, propose we add a policy? 
https://github.com/mattermost/focalboard/issues/57
> Adding responsible disclosure policy

- CHANGELOG.md
> Propose some minor tweaking to changelog intro

- CONTRIBUTING.md
Proposing we let people know who's doing what in this repo so people now who to mention.
https://github.com/mattermost/focalboard/issues/50
> Adding contributor section

- README.md
> Asking for GitHub star in README

- website/site/content/contribute/getting-started/_index.md
> fix a typo in the contribution guidelines

- .gitignore
- server/api/auth.go
- server/go.mod
- server/services/auth/email.go
Updated RegisterRequest validation. Added email validation via regex.
> Register Request email validation

- README.md
Make it easier for people to share feedback
> Adding "Share your feedback"

- CHANGELOG.md
Also adding a note on German and Japanese translation additions
> Adding "Work In Progress" release

- README.md
> Adding link to forum

- CHANGELOG.md
> Adding note on translate.mattermost.com

- webapp/src/widgets/propertyMenu.test.tsx
Added unit tests for the change name event, change value event and change type event in the propertyMenu component.
> [GH-132] Add unit tests for propertyMenu component.

- website/README.md
Make this more welcoming for contributors
> Updating website README

- CONTRIBUTING.md
Make is easier to contribute doc updates and new docs
> Adding Documentation section to CONTRIBUTING.md

- website/README.md
> Changing to relative references in Website README

- webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
- webapp/src/widgets/propertyMenu.test.tsx
I didn't cover scenarios related to the HTML structure of the component with my previous PRs . (For example, what options it shows to the users.) 
I think a snapshot test is better suited for that purpose.
> [GH-132] - Add snapshot test for propertyMenu component

- server/api/api.go
- server/app/auth.go
- server/app/blocks.go
- server/auth/auth.go
- server/client/client.go
- server/integrationtests/blocks_test.go
- server/main/main.go
- server/model/version.go
- server/services/auth/email.go
- server/services/auth/password.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/system.go
- server/services/store/sqlstore/user.go
- server/services/store/store.go
- server/services/telemetry/telemetry.go
- server/web/webserver.go
- server/ws/websockets.go
Just update the coding style.
1. `var for` => `foo :=`
2. Adjacent parameters with the same type should be grouped together
> chore(format): update coding style

- README.md
> Adding instructions to download Personal Desktop

- website/site/layouts/partials/hero.html
- website/site/static/css/styles.css
Updating homepage for focalboard
https://github.com/mattermost/focalboard/issues/88
> Updating homepage for focalboard

- README.md
> Note binary runs both desktop & server

- webapp/src/components/sidebar.scss
- webapp/src/components/tableComponent.scss
- webapp/src/styles/main.scss
154 - Updating table cell css
https://github.com/mattermost/focalboard/issues/154
> 154 - Updating table cell css

- .github/ISSUE_TEMPLATE/bug_report.md
Make it more consistent with feature request template
> Adding prefix "Bug: " to issue template

- website/site/config.toml
- website/site/layouts/_default/list.html
- website/site/layouts/_default/single.html
- website/site/layouts/partials/page-edit.html
- updated GH Repo URL to match the GH edit URL format/template
- updated edit-page partial
Fixes #142
> enabled edit link in documentation pages

- server/api/api.go
- server/einterfaces/einterfaces.go
- server/model/workspace.go
- webapp/i18n/en.json
- webapp/src/blocks/workspace.ts
- webapp/src/components/emptyCenterPanel.scss
- webapp/src/components/emptyCenterPanel.tsx
- webapp/src/components/sidebar/sidebar.scss
- webapp/src/components/sidebar/sidebar.tsx
- webapp/src/components/workspace.tsx
- webapp/src/pages/boardPage.tsx
* Show a hint when there is no active view
* Show the workspace name in the sidebar, and in the hint if available
Notes:
* Updated auth API to return workspace info
* Just title for now, but we can extend this to more info later
> Workspace title

- webapp/src/viewModel/boardTree.ts
Search now also searches in the properties of the card along with the name. 
https://github.com/mattermost/focalboard/issues/128
> Added search in properties of a card

- webapp/src/components/cardDetail/comment.scss
- webapp/src/components/cardDetail/commentsList.scss
- webapp/src/components/markdownEditor.scss
- webapp/src/widgets/buttons/button.scss
264 - Updating comment area css
https://github.com/mattermost/focalboard/issues/264
> 264 - Updating comment area css

- .github/workflows/build-mac.yml
- .github/workflows/prod-release.yml
- CHANGELOG.md
- mac/Focalboard/Info.plist
- mac/Focalboard/ViewController.swift
- webapp/i18n/en.json
- webapp/src/components/cardDetail/cardDetail.tsx
- webapp/src/components/content/checkboxElement.scss
- webapp/src/pages/errorPage.scss
- webapp/src/pages/errorPage.tsx
- webapp/src/pages/loginPage.tsx
> Release 0.6.5

- .github/workflows/build-mac.yml
- .github/workflows/prod-release.yml
- CHANGELOG.md
- mac/Focalboard/Info.plist
- mac/Focalboard/ViewController.swift
- server/main/main.go
- server/model/version.go
- webapp/i18n/en.json
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/cardDetail/cardDetail.tsx
- webapp/src/components/content/checkboxElement.scss
- webapp/src/constants.ts
- webapp/src/pages/errorPage.scss
- webapp/src/pages/errorPage.tsx
- webapp/src/pages/loginPage.tsx
- win-wpf/AppxManifest.xml
- win-wpf/Focalboard/App.xaml.cs
Submitted another release for the Windows App Store to try to fix #312. It seems limited to the App Store UWP app.
> Fix #312. Release 0.6.6

- webapp/src/components/propertyValueElement.tsx
- webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
- webapp/src/widgets/propertyMenu.tsx
Adds a phone number field and corresponding validation. Uses phone number regex from https://ihateregex.io/expr/phone/.
Tested with Indian and US phone numbers.
Fixes https://github.com/mattermost/focalboard/issues/41
> Added phone number field

- mac/Focalboard/AutoSaveWindowController.swift
- mac/Focalboard/Base.lproj/Main.storyboard
Disables Tab Bar in menu -> view -> tab bar.
Fixes: #332
> [Fix - #332]: Disable TabBar

- webapp/src/components/viewHeader/newCardButton.tsx
Use AddIcon instead of "+" in text
Similar to Bug `#2` at,
https://github.com/mattermost/focalboard/discussions/397#discussioncomment-720787
> Use AddIcon instead of "+" in text in newCardButton.tsx

- webapp/src/components/viewHeader/newCardButtonTemplateItem.tsx
Adds missing edit icon to the UI
Bug `#2` at,
https://github.com/mattermost/focalboard/discussions/397#discussioncomment-720787
> add missing EditIcon

- server/api/api.go
- server/app/blocks.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/blocks.go
- server/services/store/store.go
- server/services/store/storetests/blocks.go
- webapp/src/archiver.ts
- webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
- webapp/src/mutator.ts
- webapp/src/octoClient.test.ts
- webapp/src/octoClient.ts
Export/import board 
Fixes GH-261
> Add Export/import board 

- .github/workflows/build-mac.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-win-wpf.yml
- .github/workflows/ci.yml
- .github/workflows/prod-release.yml
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/content/checkboxElement.test.tsx
Started using Node v16 in GitHub actions, which is the Node version used in web app.
https://github.com/mattermost/focalboard/issues/458
> Using Node v16.0.1 in CI

- .github/workflows/codeql-analysis.yml
Added step to run automated CodeQL checks. Once this file is merged, the codeql checks (code scanning checks) will automatically be performed on following conditions:
- new pull requests to master branch
- scheduled to run every week once (it automatically pulls the latest codeql checks added, if any)
Fixes https://mattermost.atlassian.net/browse/SEC-441
> Add CodeQL check

- webapp/src/components/markdownEditor.tsx
Fixed multiple bugs faced in Safari and MacOS desktop app regaled to text editor in comments and description.
Fixes #407 #482 and #506
> Fixed multiple safari bugs

- webapp/src/components/dialog.scss
188 - Updating color for alerts
https://github.com/mattermost/focalboard/issues/188
> 188 - Updating color for alerts

- webapp/src/components/viewHeader/viewHeaderSearch.tsx
- webapp/src/viewModel/boardTree.ts
Search restting after adding a new property FIXED!
Fixes https://github.com/mattermost/focalboard/issues/418
> GH-418: Fix Resetting Search after adding new Property

- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
- webapp/src/components/sidebar/sidebar.tsx
- webapp/src/components/sidebar/sidebarSettingsMenu.test.tsx
- webapp/src/components/sidebar/sidebarSettingsMenu.tsx
- webapp/src/theme.ts
Marked selected language and theme
https://github.com/mattermost/focalboard/issues/385
Fixed #385 
**Language-**
https://user-images.githubusercontent.com/18575143/120996367-e32e6f80-c7a3-11eb-997e-69b1ab5a037a.mp4
**Theme-**
> Marked selected language and theme

- webapp/src/components/kanban/kanban.tsx
Fixed kanban board rearranging issue
https://github.com/mattermost/focalboard/issues/420
> Fixed kanban board rearranging issue

- Makefile
- win-wpf/build.bat
Some updates for windows build based on the tests made to make it work in GitLab
need this PR to enable the build for windows
MR for the internal pipeline: https://git.internal.mattermost.com/mattermost/ci/focalboard/-/merge_requests/2
> windows: updates based on tests for gitlab

- webapp/src/components/cardDetail/cardDetailProperties.tsx
- webapp/src/mutator.ts
- webapp/src/widgets/menu/textOption.tsx
- webapp/src/widgets/propertyMenu.test.tsx
- webapp/src/widgets/propertyMenu.tsx
Set property type and property name at the same time. 
Fixes GH-524
https://github.com/mattermost/focalboard/issues/524
> Card Template > Creating a property & setting type only stores either property name or type 

- .gitlab-ci.yml
add variable to define the image for gitlab internal
> add variable to define the image

- README.md
Added build staus badge to readme
> Added build sttaus badge to readme

- webapp/src/components/table/table.scss
Fixed horizontal scroll issue with table view
https://github.com/mattermost/focalboard/issues/541
> Fixed horizontal scroll issue with table view

- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/centerPanel.tsx
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableHeader.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableHeaderMenu.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
- webapp/src/components/table/table.test.tsx
- webapp/src/components/table/table.tsx
- webapp/src/components/table/tableGroup.tsx
- webapp/src/components/table/tableGroupHeaderRow.test.tsx
- webapp/src/components/table/tableGroupHeaderRow.tsx
- webapp/src/components/table/tableHeader.test.tsx
- webapp/src/components/table/tableHeaderMenu.test.tsx
- webapp/src/components/table/tableRow.test.tsx
- webapp/src/components/table/tableRows.test.tsx
- webapp/src/components/table/tableRows.tsx
Implemented Unit Tests for the tables view components.
Also, changed to useIntl() from passing as property.
> Table unit tests

- webapp/src/components/markdownEditor.tsx
The variable text was not updating on updation of UI and was getting reassigned the old value. I propagated  that by directly using the  text variable from props.
> Solved #387 Bug: Comment box doesn't clear after sending

- webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
- webapp/src/theme.ts
- webapp/src/widgets/valueSelector.scss
- webapp/src/widgets/valueSelector.tsx
Fixed issue with the dropdown background being height-limited
Before:
After:
> Fixed issue with dropdown background being height-limited

- mattermost-plugin/server/plugin.go
Follow up to https://github.com/mattermost/focalboard/pull/609
> Use path.Join in plugin's webpath property

- webapp/src/components/sidebar/sidebar.scss
Fixes issue where the sidebar gets overlaid by the top header. 
Fixes https://github.com/mattermost/focalboard/issues/567
> GH-567 -Update z-index on sidebar

- webapp/src/components/centerPanel.tsx
- webapp/src/components/kanban/kanban.tsx
- webapp/src/components/kanban/kanbanCard.tsx
When duplicate a card, it will open automatically
Fixes https://github.com/mattermost/focalboard/issues/623
> [GH-623] Add Feature Automatically open a card when duplicating it

- website/site/content/download/personal-edition/ubuntu.md
- website/site/content/guide/admin/_index.md
Adding MySQL installation and configuration to  Ubuntu.md and Personal Server configuration
> Adding MySQL to the documentation

- webapp/src/components/kanban/kanbanColumnHeader.tsx
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
- webapp/src/components/table/tableGroupHeaderRow.test.tsx
- webapp/src/components/table/tableGroupHeaderRow.tsx
- webapp/src/constants.ts
- webapp/src/test/testBlockFactory.ts
- webapp/src/widgets/label.tsx
- webapp/src/widgets/valueSelector.tsx
This fixes: https://mattermost.atlassian.net/browse/MM-36791
> Only allowing valid color classes

- server/server/server.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/system.go
- server/services/store/sqlstore/user.go
- server/services/store/sqlstore/util.go
- server/services/store/sqlstore/workspaces.go
Cherry-pick and fix merge conflicts https://github.com/mattermost/focalboard/commit/6e214ebc3dd7f1b8007b2e37336160eca7258547
NONE
> cherry-pick close_rows

- webapp/src/widgets/valueSelector.scss
- webapp/src/widgets/valueSelector.tsx
Fixed an issue with the select colour picker being clipped out of the dropdown.
Fixes #636
> Fixed issue where color panel git cut off in value selector

- webapp/src/components/propertyValueElement.tsx
- webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
- webapp/src/components/sidebar/sidebarSettingsMenu.tsx
- webapp/src/dateFormat.ts
- webapp/src/octoUtils.tsx
- webapp/src/userSettings.ts
- webapp/src/utils.ts
- webapp/src/widgets/editableDayPicker.tsx
Fixes https://github.com/mattermost/focalboard/issues/550
> add user setting for preferred date format

- server/services/store/sqlstore/blocks.go
- server/services/store/storetests/helpers.go
Fixed some missed error handling.
N/A
> Fixed missing errors

- mattermost-plugin/.golangci.yml
- mattermost-plugin/server/plugin.go
- server/.golangci.yml
- server/client/client.go
- server/services/store/sqlstore/blocks.go
- server/services/store/storetests/blocks.go
This PR fixes all linter errors in plug-in.  The linter rules have also been made consistent between plug-in and server.
https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-88cc744576c8&c=294a1308-8292-4378-8768-386d2d4cfa5b
> Fix linter errors in plugin

- .github/CODEOWNERS
I've enabled the PR auto-assignment but looks like that was not working and realize that was missing the codeowners file
lets try
> add codeowners to make the PR auto assignment to work

- webapp/src/components/table/table.scss
Fixed horizontal scroll bar appearing too high
Fixed #738
> Fixed horizontal scroll bar appearing too high

- webapp/webpack.common.js
Added hash when loading JS file to bust cache
Fixed #690
> Added hash when loading JS file to bust cache

- webapp/src/components/sidebar/sidebar.tsx
- webapp/src/components/sidebar/sidebarBoardItem.scss
- webapp/src/components/sidebar/sidebarBoardItem.tsx
- webapp/src/components/workspace.tsx
- webapp/src/theme.ts
GH-633 - Updating active indicator for boards
https://github.com/mattermost/focalboard/issues/633
> GH-633 - Updating active indicator for boards

- webapp/src/components/shareBoardComponent.scss
- webapp/src/components/shareBoardComponent.tsx
- webapp/src/components/sidebar/registrationLink.scss
- webapp/src/components/sidebar/registrationLink.tsx
- webapp/src/components/sidebar/sidebar.scss
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
- webapp/src/components/workspace.scss
- webapp/src/widgets/buttons/button.scss
- webapp/src/widgets/buttons/button.tsx
Gh 744 - Improving UI for share board popup and improving buttons
https://github.com/mattermost/focalboard/issues/744
> Gh 744 - Improving UI for share board popup and improving buttons

- webapp/src/components/kanban/kanban.tsx
Reverts mattermost/focalboard#772
> Revert "Fix Cards not Dragging to different Columns (GH-626)"

- server/services/store/storetests/users.go
Add more unit tests for ./store/sqlstore/user.go
Fixes https://github.com/mattermost/focalboard/issues/430
> Add more unit tests for ./store/sqlstore/user.go

- webapp/src/components/propertyValueElement.tsx
> Fix update properties on click outside the dialog

- webapp/src/components/propertyValueElement.tsx
> Fix bug on save on unmount

- webapp/src/mutator.ts
> Match the user settings for icon prefill on card for template

- webapp/src/mutator.ts
> Keeping the visible and hidden options when you change the grouping

- webapp/src/components/blockIconSelector.tsx
- webapp/src/components/viewTitle.tsx
> Fix problems with no refreshed data on handlers

- webapp/src/pages/boardPage.tsx
Fixes #718
This solution is not going to be applied to the main branch, because the main branch hasn't this problem.
> A not efficicient working temporary fix for switch after add view

- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/components/cardDetail/cardDetail.tsx
- webapp/src/components/cardDetail/cardDetailContents.tsx
- webapp/src/components/cardDetail/cardDetailContentsMenu.tsx
- webapp/src/components/contentBlock.scss
- webapp/src/components/markdownEditor.scss
> Show add content button on hover or focus of content block

- import/asana/importAsana.ts
- import/notion/importNotion.ts
- import/todoist/importTodoist.ts
- import/trello/importTrello.ts
Updates import scripts for object model changes made as part of redux implementation.
Fixes https://github.com/mattermost/focalboard/issues/890
> GH-890 - update import scripts for object model changes

- server/api/api.go
- server/api/auth.go
- server/client/client.go
- server/integrationtests/clienttestlib.go
- server/integrationtests/user_test.go
- server/model/user.go
Add integration tests for missing User API endpoints
Fixes https://github.com/mattermost/focalboard/issues/436
> [GH-436] Add integration tests for missing User API endpoints

- server/services/store/storetests/blocks.go
- webapp/src/blocks/board.ts
- webapp/src/blocks/boardView.ts
- webapp/src/blocks/card.ts
- webapp/src/components/calculations/__snapshots__/calculation.test.tsx.snap
- webapp/src/components/calculations/__snapshots__/options.test.tsx.snap
- webapp/src/components/calculations/calculation.scss
- webapp/src/components/calculations/calculation.test.tsx
- webapp/src/components/calculations/calculation.tsx
- webapp/src/components/calculations/calculations.test.tsx
- webapp/src/components/calculations/calculations.ts
- webapp/src/components/calculations/options.test.tsx
- webapp/src/components/calculations/options.tsx
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/calculation/__snapshots__/calculationRow.test.tsx.snap
- webapp/src/components/table/calculation/calculationRow.scss
- webapp/src/components/table/calculation/calculationRow.test.tsx
- webapp/src/components/table/calculation/calculationRow.tsx
- webapp/src/components/table/table.scss
- webapp/src/components/table/table.tsx
- webapp/src/components/table/tableRow.tsx
- webapp/src/theme.ts
- webapp/src/utils.ts
- webapp/src/widgets/icons/chevronUp.tsx
Cherry Pick of https://github.com/mattermost/focalboard/pull/761 into release-0.9.0
> Table calculations (#761)

- webapp/src/i18n.tsx
> Fix simplified chinesse language

- mattermost-plugin/webapp/webpack.config.js
> Fixing a weird import bug on react-day-picker

- mattermost-plugin/webapp/webpack.config.js
Co-authored-by: Scott Bishel <scott.bishel@mattermost.com>
(cherry picked from commit 22879318828aea809d796cadfb62d2867153cc35)
> Fixing a weird import bug on react-day-picker (#933)

- webapp/src/styles/main.scss
Fixes https://github.com/mattermost/focalboard/issues/937
> GH-937 - add overflow: hidden to prevent scrolling

- webapp/src/components/centerPanel.scss
Avoided double horizontal scrollbars
Fixes #889
> Avoided double horizontal scrollbars

- webapp/src/store/boards.ts
- webapp/src/store/cards.ts
- webapp/src/store/comments.ts
- webapp/src/store/contents.ts
- webapp/src/store/views.ts
> Cleanup the store on the initial load call

- mattermost-plugin/webapp/src/index.tsx
Fixes #973
Fixes #956 
There is still a corner case where you enter in playbooks without entering ever in a channel.
> Storing the last channel viewed to workaround the fact that playbooks is not bind to channels

- webapp/src/widgets/label.scss
GH-894 - Removing uppercase from label
https://github.com/mattermost/focalboard/issues/894
> GH-894 - Removing uppercase from column header

- webapp/src/components/contentBlock.scss
> Adjust image size to content column size

- mattermost-plugin/webapp/src/index.tsx
- webapp/src/utils.ts
> Fixing favicon changes on other browsers

- webapp/src/styles/main.scss
> Fixing text selection in all inputs for Firefox

- webapp/src/components/properties/dateRange/__snapshots__/dateRange.test.tsx.snap
- webapp/src/components/properties/dateRange/dateRange.scss
- webapp/src/components/properties/dateRange/dateRange.test.tsx
- webapp/src/components/properties/dateRange/dateRange.tsx
- webapp/src/components/properties/link/link.tsx
- webapp/src/components/propertyValueElement.tsx
GH-966 - Removing empty placeholders
https://github.com/mattermost/focalboard/issues/966
> GH-966 - Removing empty placeholders

- webapp/src/components/sidebar/boardTemplateMenuItem.tsx
- webapp/src/widgets/menu/menu.tsx
1004-add-board-menu
https://github.com/mattermost/focalboard/issues/1004
> 1004-add-board-menu

- webapp/src/components/table/table.scss
Updating cell alignment for table view
> Updating cell alignment for table view

- mattermost-plugin/webapp/src/index.tsx
Update the channel header button hint.
> Fix #1086: Update channel header button hint

- webapp/src/widgets/menuWrapper.scss
> Fixing property name text select on plugin mode

- webapp/src/components/contentBlock.scss
> Fix chrome drag and drop preview

- .github/workflows/build-mac.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-win-wpf.yml
- .github/workflows/dev-release.yml
- .github/workflows/plugin-release.yml
- .github/workflows/prod-release.yml
- mattermost-plugin/server/plugin.go
- mattermost-plugin/webapp/src/index.tsx
- mattermost-plugin/webapp/webpack.config.js
- server/api/api.go
- server/app/clientConfig.go
- server/model/clientConfig.go
- server/services/config/config.go
- webapp/src/app.tsx
- webapp/src/components/centerPanel.tsx
- webapp/src/config/clientConfig.ts
- webapp/src/octoClient.ts
- webapp/src/telemetry/telemetry.ts
- webapp/src/telemetry/telemetryClient.test.ts
- webapp/src/telemetry/telemetryClient.ts
* implement webapp telemetry
* cleanup
* remove imports, update events
* change event title
* update for lint
* add test, update filename
* linter fix
* fix field name
* revert changes
* fix test
* update builds
* fix workflows
* fix workflows
* fix workflow
* temp checkin
* remove log lines
* updates from peer review
> Plugin telemetry (#1069)

- .github/workflows/prod-release.yml
Set the telemetry key in the production release workflow.
> Fix #1229. Set telemetry key for production

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Fixes issue with SQL query for workspace switcher in MySQL.
Fixes #1242
> Workspace switcher query Mysql issue resolved

- mattermost-plugin/webapp/src/index.tsx
Fixed issue where the app switcher doesn't take to the dashboard
Fixes #1258
> Open dashboard from apps witcher

- webapp/src/components/centerPanel.scss
- webapp/src/components/dialog.scss
- webapp/src/components/viewHeader/viewHeader.scss
GH-1276 - Updating scroll on IOS
Fixes https://github.com/mattermost/focalboard/issues/1276
> GH-1276 - Updating scroll on IOS

- webapp/src/components/sidebar/sidebar.scss
GH-1263 - Updating sidebar width
Fixes https://github.com/mattermost/focalboard/issues/1263
Fixes https://github.com/mattermost/focalboard/issues/1238
> GH-1263 - Updating sidebar width

- webapp/src/mutator.ts
- webapp/src/octoClient.ts
Fixed a bug where the user couldn't create boards from templates
Fixes #1311
> Fixed a bug where the user couldn't create boards from templates

- CONTRIBUTING.md
Updated with information about how to contribute to the docs.
> Update CONTRIBUTING.md with new Docs info

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- webapp/src/pages/dashboard/dashboardPage.scss
Handled the case of missing user in workspace list API for workspace switcher and dashboard.
Fixes #1363
> Handled the case of missing user

- webapp/src/components/cardDialog.tsx
- webapp/src/components/globalHeader/globalHeader.tsx
- webapp/src/components/table/tableRows.tsx
- webapp/src/components/viewHeader/viewHeaderSearch.tsx
- webapp/src/nativeApp.ts
- webapp/src/octoClient.ts
- webapp/src/pages/boardPage.tsx
- webapp/src/svg/dashboard-onboarding.tsx
- webapp/src/svg/search-illustration.tsx
- webapp/src/userSettings.ts
Fixes lint warnings for missing return type on function
Fixes https://github.com/mattermost/focalboard/issues/1362
> GH-1362: Fix missing return type on function

- webapp/src/pages/dashboard/dashboardPage.scss
Allowed dashboard to scroll
Fixes #1372
> Allowed dashboard to scroll

- server/app/app_test.go
- server/app/clientConfig_test.go
Two linter errors slipped through via cherry picks:  https://github.com/mattermost/focalboard/pull/1293
NONE
> Fix linter errors

- webapp/src/components/gallery/gallery.tsx
> Remove default `return`

- webapp/src/components/kanban/kanban.scss
> Fix kanban cards overlapping with header

- webapp/src/components/viewHeader/__snapshots__/viewHeader.test.tsx.snap
- webapp/src/components/viewHeader/viewHeader.test.tsx
- webapp/src/testUtils.tsx
Add tests unit for viewHeader
Fixes #864
> [GH-864]: add tests unit for viewHeader

- webapp/src/components/viewHeader/__snapshots__/viewHeaderSearch.test.tsx.snap
- webapp/src/components/viewHeader/viewHeaderSearch.test.tsx
- webapp/src/testUtils.tsx
add unit tests for viewHeaderSearch
fixes #868
> [GH-868]: add unit tests viewHeaderSearch

- webapp/src/components/cardDetail/__snapshots__/cardDetailContents.test.tsx.snap
- webapp/src/components/viewHeader/__snapshots__/viewHeaderPropertiesMenu.test.tsx.snap
- webapp/src/components/viewHeader/viewHeaderPropertiesMenu.test.tsx
- webapp/src/testUtils.tsx
Add unit tests for viewHeaderPropertiesMenu
Fixes #867
> [GH-867]: add unit tests for viewHeaderPropertiesMenu

- server/services/store/sqlstore/migrate.go
Remove left-over debugging line.
NONE
> Remove left-over debugging line.

- webapp/src/octoClient.ts
- webapp/src/pages/registerPage.tsx
Hello.
Adjusted the warnings in the file
`webapp/src/octoClient.ts`
where the typing from `any` to `unknown` was changed.
#1354
> Typing adjustment - 1354

- webapp/src/components/markdownEditor.tsx
This pull request resolves linter warnings for the markdownEditor.tsx component
Tests using this component pass locally, suggestions on improvement welcome.
Fixes https://github.com/mattermost/focalboard/issues/1352
> [GH-1352] Webapp Linter Fixes - fix linter warnings for file markdownEditor.tsx

- webapp/src/components/viewHeader/__snapshots__/filterValue.test.tsx.snap
- webapp/src/components/viewHeader/filterValue.test.tsx
- webapp/src/testUtils.tsx
Add units test for filterValue
Fixes #861
> [GH-861] add units test for filterValue

- webapp/src/components/viewHeader/__snapshots__/viewHeaderGroupByMenu.test.tsx.snap
- webapp/src/components/viewHeader/viewHeaderGroupByMenu.test.tsx
- webapp/src/testUtils.tsx
Add unit tests for component viewHeaderGroupByMenu
Fixes #866
> [GH-866] add unit test for viewHeaderGroupByMenu

- webapp/src/csvExporter.ts
The exported CSV headers weren't consistent with the displayed ones, now they are the same.
[#993](https://github.com/mattermost/focalboard/issues/993)
> [GH-993] Fix csv export header

- webapp/package.json
- webapp/src/blocks/archive.ts
- webapp/src/telemetry/telemetryClient.ts
- webapp/src/testUtils.tsx
Hello.
Adjusted the warnings in the files
`webapp/src/telemetry/telemetryClient.ts`
`webapp/src/testUtils.tsx`
`webapp/src/blocks/archive.ts`
where the typing from `any` to `unknown` was changed.
Fixes #1357
> Typing adjustment - 1357

- webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
- webapp/src/components/viewHeader/filterEntry.test.tsx
Add tests unit for filterEntry
Fixes #860
> [GH-860] Add tests unit for filterEntry

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dev-release.yml
- .github/workflows/lint-plugin.yml
- .github/workflows/lint-server.yml
Cherry-pick https://github.com/mattermost/focalboard/pull/1390
https://github.com/mattermost/focalboard/issues/1365
> run all CI on PRs to be merged with release branches (#1390)

- webapp/src/components/viewHeader/__snapshots__/filterComponent.test.tsx.snap
- webapp/src/components/viewHeader/filterComponent.test.tsx
Add tests unit for filterComponent
Fixes #859
> [GH-859] Add tests unit for filterComponent

- webapp/src/hooks/sortable.tsx
Hello.
Adjusted the warnings in the file
`webapp/src/hooks/sortable.tsx`
Fixes #1353
> Typing adjustment - 1353

- webapp/src/app.tsx
Avoided boards from navigating to URL not belonging to it.
Fixes #1452 
Fixes #1453
> Avoided boards from navigating to URL not belonging to it

- webapp/src/components/viewHeader/__snapshots__/emptyCardButton.test.tsx.snap
- webapp/src/components/viewHeader/emptyCardButton.test.tsx
Add tests unit on emptyCardButton
There's no issue but to finish all tests in viewHeader
> Add tests unit on emptycardButton

- webapp/src/components/properties/dateRange/dateRange.scss
- webapp/src/components/properties/dateRange/dateRange.tsx
Highlight the selected dates if there are any in adjacent months. 
Fixes [Issue #1439](https://github.com/mattermost/focalboard/issues/1439)
> GH-1439: do not show outside dates in datepicker

- webapp/src/components/kanban/__snapshots__/kanbanColumn.test.tsx.snap
- webapp/src/components/kanban/kanbanColumn.test.tsx
Add unit test for kanbanColumn
Fixes #855
> [GH-855]: Add unit test for kanbanColumn

- webapp/src/components/kanban/__snapshots__/kanbanHiddenColumnItem.test.tsx.snap
- webapp/src/components/kanban/kanbanHiddenColumnItem.test.tsx
Add unit tests for kanbanHiddenColumnItem
Fixes #857
> [GH-857]: Add unit tests for kanbanHiddenColumnItem

- README.md
Add a Description in the README File like in the Issue https://github.com/mattermost/focalboard/issues/91 Requested in the First Comment, and I Personally would have needed to get started with this project.
https://github.com/mattermost/focalboard/issues/91 (Kind Of)
And Duplicate: https://github.com/mattermost/focalboard/issues/893
I know there is  a Compose File floating around in the docker Folder, i hope that i Added the Intended Way to the README.
If not please see this as a notch, for creating fitting Documentation here and on: https://www.focalboard.com/download/personal-edition/docker/
Please be aware the Expiremental Feature will only work if my other Pull Request: https://github.com/mattermost/focalboard/pull/1700 gets accepted
> [GH-91] Added Install/Build Instructions for Docker in Readme

- webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
- webapp/src/components/centerPanel.test.tsx
Add unit tests for centerPanel
Fixes #828
> [GH-828]: Add unit tests for centerPanel

- webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
- webapp/src/components/kanban/kanbanCard.test.tsx
Add unit tests for kanbanCard
Fixes #854
> [GH-854]: Add unit tests for kanbanCard

- server/utils/utils.go
Adds a new utils method to convert a BlockType to an IDType.
NONE
> utils.BlockType2IDType

- webapp/src/components/workspaceSwitcher/__snapshots__/workspaceSwitcher.test.tsx.snap
- webapp/src/components/workspaceSwitcher/workspaceSwitcher.test.tsx
- webapp/src/components/workspaceSwitcher/workspaceSwitcher.tsx
Prevented workspace switcher from setting dashboard as the last visited workspace
Fixes #1597
> Prevented workspace switcher from settiong dashboard as the last visited workspace

- webapp/src/components/cardDialog.tsx
- webapp/src/components/centerPanel.tsx
- webapp/src/components/gallery/galleryCard.tsx
- webapp/src/components/kanban/kanbanCard.tsx
- webapp/src/components/viewMenu.tsx
Cherry pick of #1739 on release-0.10.
```release-note
NONE
```
> Automated cherry pick of #1739

- webapp/src/components/__snapshots__/topBar.test.tsx.snap
- webapp/src/components/topBar.test.tsx
Add unit tests for topBar
Fixes #837
> [GH-837]: Add unit tests for topBar

- webapp/src/components/kanban/calculation/calculationOptions.test.tsx
Fixes a failing test in Main from this commit.
https://github.com/mattermost/focalboard/pull/1529
> Fix failing test in Main

- mattermost-plugin/webapp/src/index.tsx
> Applying the plugin theme changes based on websocket event

- webapp/src/store/initialLoad.ts
Cherry pick of #1773 on release-0.10.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #1773

- CHANGELOG.md
> Fix #1777. v0.10 changelog

- webapp/src/components/kanban/kanban.tsx
Cherry pick of #1771 on release-0.10.
/cc  @hahmadia
```release-note
NONE
```
> Automated cherry pick of #1771

- mattermost-plugin/server/plugin.go
Cherry pick of #1763 on release-0.10.
/cc  @hahmadia
```release-note
NONE
```
> Automated cherry pick of #1763

- webapp/src/styles/main.scss
> Fixing styles on product switcher menu

- webapp/src/styles/main.scss
Cherry pick of #1783 on release-0.10.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #1783

- webapp/src/components/table/table.scss
GH-1024 - Updating table row css
https://github.com/asaadmahmood/focalboard/compare/GH-1024?expand=1
> GH-1024 - Updating table row css

- webapp/src/components/table/table.scss
GH-1024 - Updating table row css
fixes https://github.com/asaadmahmood/focalboard/compare/GH-1024?expand=1
This was already merged into release-0.10
> Updating table row css (#1787)

- mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.scss
> Updating unfurl UI

- mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.scss
Cherry pick of #1794 on release-0.10.
```release-note
NONE
```
> Automated cherry pick of #1794

- webapp/src/components/addContentMenuItem.tsx
- webapp/src/components/cardDetail/cardDetailContents.tsx
- webapp/src/components/cardDetail/cardDetailContext.tsx
- webapp/src/components/cardDetail/imagePaste.tsx
Fixes #1792
Fixes #1767
Fixes #1798
> Fixing Adding content bug

- README.md
Fixing main readme for broken links to badges
> fixing readme broken since #1663 completed

- webapp/src/components/emptyCenterPanel.scss
GH-1519 - Fixing color on template picker
https://github.com/mattermost/focalboard/issues/1519
> GH-1519 - Fixing color on template picker

- mac/Focalboard.xcodeproj/project.pbxproj
- mac/Focalboard/Base.lproj/Main.storyboard
- mac/Focalboard/Globals.swift
- mac/Focalboard/WhatsNewViewController.swift
- mac/Focalboard/whatsnew.txt
Update Mac app for v0.10.0. Also refactored what's new text into `whatsnew.txt` to make future updates easier.
#1839
> Fix #1839. Update Mac App for v0.10.0

- mac/Focalboard.xcodeproj/project.pbxproj
- mac/Focalboard/Base.lproj/Main.storyboard
- mac/Focalboard/Globals.swift
- mac/Focalboard/WhatsNewViewController.swift
- mac/Focalboard/whatsnew.txt
Cherry pick of #1842 on release-0.10.
/cc  @chenilim
```release-note
NONE
```
> Automated cherry pick of #1842

- CHANGELOG.md
- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mac/Focalboard/whatsnew.txt
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
- win-wpf/AppxManifest.xml
Update to v0.11, and update the changelog.
> Update version to 0.11.0

- README.md
Update readme to emphasize project management, and link to Mattermost Boards.
> Readme 112221

- webapp/src/app.tsx
Fixes a bug causing empty white screen to appear on refreshing Mattermost desktop app
Fixes #1852
> Fixed issue with desktop app causing white screen

- webapp/src/components/markdownEditor.scss
GH-1837 - Updating link css
Fixes https://github.com/mattermost/focalboard/issues/1837
> GH-1837 - Updating link css

- webapp/src/components/calendar/fullcalendar.scss
1873 - Calendar UI update
Fixes https://github.com/mattermost/focalboard/issues/1873
> 1873 - Calendar UI update

- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/components/properties/dateRange/dateRange.scss
- webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
- webapp/src/components/properties/user/user.tsx
GH-1284 - Fixing alignment of properties on cards
Fixes https://github.com/mattermost/focalboard/issues/1284
> GH-1284 - Fixing alignment of properties on cards

- webapp/src/blocks/__snapshots__/block.test.ts.snap
- webapp/src/blocks/block.test.ts
- webapp/src/blocks/block.ts
- webapp/src/components/content/checkboxElement.tsx
> Properly generating patch diffs from two blocks

- .github/ISSUE_TEMPLATE/bug_report.md
Adds Triage tag to all new bugs created
None
> Add Triage tag to new bugs

- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
- win-wpf/AppxManifest.xml
Update the version number to v0.12.0. Going forward, we will update the version number on main right after branching for the release.
> Update to v0.12

- webapp/src/components/calendar/fullCalendar.tsx
Cherry pick of #1898 on release-0.11.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #1898

- server/api/api.go
- server/api/auth.go
- server/app/auth.go
- server/services/metrics/metrics.go
- webapp/src/components/sidebar/sidebarUserMenu.tsx
- webapp/src/octoClient.ts
- webapp/src/pages/errorPage.tsx
Cherry pick of #1895 on release-0.11.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #1895

- webapp/src/components/cardDetail/commentsList.scss
- webapp/src/components/markdownEditorInput/markdownEditorInput.scss
GH-1880 - Updating styling for mention popup (theme compatible)
Fixes https://github.com/mattermost/focalboard/issues/1880
> GH-1880 - Updating styling for mention popup (theme compatible)

- server/api/api.go
- server/api/auth.go
- server/app/auth.go
- server/services/metrics/metrics.go
- webapp/src/components/sidebar/sidebarUserMenu.tsx
- webapp/src/octoClient.ts
- webapp/src/pages/errorPage.tsx
* Adding explict logout logic
* Fixing golangci-lint errors
(cherry picked from commit 2f08c6782762e58e008bd50f3892cb1cdd1be539)
> Adding explict logout logic (#1895)

- webapp/src/blocks/card.ts
This only takes care of not breaking on bad data, the unique IDs migration fix will avoid bad data from being created.
Fixes https://github.com/mattermost/focalboard/issues/1922
> Prevents the application from crashing if there is a null content order

- webapp/src/components/markdownEditor.scss
Fixes #1884 
Fixes #1918 
Fixes #1915
> Making markdown editor text selectable

- webapp/src/blocks/card.ts
Cherry pick of #1937 on release-0.11.
```release-note
NONE
```
> Automated cherry pick of #1937

- webapp/src/components/markdownEditor.scss
Cherry pick of #1896 on release-0.11.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #1896

- server/api/auth.go
- webapp/src/pages/registerPage.tsx
Fixes an Issue
Refer to https://mattermost.atlassian.net/browse/MM-40429
> Fix an Issue

- webapp/src/components/cardDetail/commentsList.scss
- webapp/src/components/markdownEditorInput/markdownEditorInput.scss
Cherry pick of #1925 on release-0.11.
```release-note
NONE
```
> Automated cherry pick of #1925

- server/integrationtests/user_test.go
- server/model/user.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Removed unused fields
https://mattermost.atlassian.net/browse/MM-40536
> Removed unused fields

- webapp/src/mutator.test.ts
- webapp/src/mutator.ts
Fixed a bug preventing new template being created from a card
Fixes #1888
> Fixed a bug preventing new template being created from a card

- webapp/cypress/integration/createBoard.ts
> [GH-1815]: Add e2e tests for empty board

- server/api/api.go
- server/app/blocks.go
- server/app/blocks_test.go
- server/model/block.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/store.go
- server/services/store/storetests/blocks.go
- webapp/src/mutator.ts
- webapp/src/octoClient.ts
Cherry pick of #1935 on release-0.11.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #1935

- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/data_migrations_test.go
Cherry pick of #1965 on release-0.11.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #1965

- webapp/cypress/integration/createBoard.ts
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
- webapp/src/components/sidebar/sidebarBoardItem.scss
- webapp/src/components/sidebar/sidebarBoardItem.tsx
- webapp/src/styles/main.scss
Cherry pick of #1978 on release-0.11.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #1978

- webapp/src/components/properties/user/__snapshots__/user.test.tsx.snap
- webapp/src/components/properties/user/user.scss
- webapp/src/components/properties/user/user.tsx
GH-1907 - Updating person popover
https://github.com/mattermost/focalboard/issues/1907
> GH-1907 - Updating person popover

- webapp/src/components/properties/dateRange/dateRange.scss
Cherry pick of #1981 on release-0.11.
```release-note
NONE
```
> Automated cherry pick of #1981

- webapp/src/components/markdownEditorInput/markdownEditorInput.scss
Update style to remove extra borders
#1992
> Fix #1992. Remove borders around code block lines.

- server/services/store/sqlstore/blocks.go
While working on enabling mysql support for unit & integration tests SQL syntax errors were found in getSubtree3 and deleteBlock.  This PR fixes them.
Fixes https://github.com/mattermost/focalboard/issues/1996
> fix syntax errors for mysql

- server/web/webserver.go
When running unit tests an error is output for each test, including a full stack trace.
```
Unable to serve the index.html file  error="open pack/index.html: no such file or directory"
```
The "error" is expected for unit tests.  This PR changes the log level to warning when running unit tests to eliminate the clutter of a full stack trace.
NONE
> Remove noisy error for unit tests

- webapp/src/pages/errorPage.tsx
Fixes a linter error that got introduced here -
https://github.com/mattermost/focalboard/pull/1885
> Fix linter error

- server/services/store/sqlstore/blocks.go
This PR fixes the panic at start-up for plugin + postgres/mysql.  When selecting on a timestamp database type, the type of the var to scan into is different based on database type.  The fix is to convert the timestamp to string within the query and scan into a string.
I will look into why this wasn't caught via unit testing.
NONE
> fix panic selecting insert_at

- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/cardDetail/comment.scss
- webapp/src/components/cardDetail/commentsList.scss
- webapp/src/components/cardDetail/commentsList.tsx
- webapp/src/utils.ts
GH-479 - Updating comment order and images
https://github.com/mattermost/focalboard/issues/479
> GH-479 - Updating comment order and adding images

- webapp/src/components/__snapshots__/topBar.test.tsx.snap
- webapp/src/components/topBar.tsx
Remove Beta label from TopBar
#2038
> Fix #2038. Remove beta label

- CHANGELOG.md
> Update CHANGELOG.md for v0.12

- .github/workflows/ci.yml
Changes github actions config to run CI against all PRs and pushes in all branches.
NONE
> Run CI against all PRs and pushes, in any branch

- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
- win-wpf/AppxManifest.xml
> Update version to 0.14.0

- server/model/notification.go
- server/services/notify/notifysubscriptions/diff.go
- server/services/notify/notifysubscriptions/diff2slackattachments.go
- server/services/notify/notifysubscriptions/notifier.go
- server/services/notify/notifysubscriptions/util.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/migrations/bindata.go
Cherry pick of #2055 on release-0.12.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2055

- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Fixes a bug with stale closure in markdown editor.
Fixes #2036
> Fixed bug of stale closure in markdown editor

- mac/Focalboard.xcodeproj/project.pbxproj
- mac/Focalboard/Base.lproj/Main.storyboard
- mac/Focalboard/CustomWKWebView.swift
- mac/Focalboard/ViewController.swift
Prevent macOS from interpreting WKWebView key presses as unhandled, to stop the "funk" error sound.
The problem seems to be that WKWebView doesn't report some handled keys correctly to the host app.
#2062
> Gh 2062 mac error sound

- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
(cherry picked from commit 33407e7dd9a079138acc08421539ee90ebceee1b)
> fix comments being set backwards (#2076)

- server/api/api.go
Cherry pick of #2072 on release-0.12.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2072

- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Cherry pick of #2085 on release-0.12.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #2085

- webapp/src/components/markdownEditor.scss
Fixing link color on card (Personal Server)
Fixes https://github.com/mattermost/focalboard/issues/1960
> GH-1960 - Fixing link color on card (Personal Server)

- webapp/src/components/markdownEditor.scss
Cherry pick of #2087 on release-0.12.
```release-note
NONE
```
> Automated cherry pick of #2087

- webapp/src/components/cardDetail/cardDetail.scss
GH-1948 - Updating overflow on input fields
Fixes https://github.com/mattermost/focalboard/issues/1948
> GH-1948 - Updating overflow on input fields

- webapp/src/components/cardDetail/cardDetail.scss
Cherry pick of #2088 on release-0.12.
```release-note
NONE
```
> Automated cherry pick of #2088

- server/model/block.go
- server/model/block_test.go
> Fixing unique ID problems on content order with multiple colums

- server/model/block.go
- server/model/block_test.go
Cherry pick of #2071 on release-0.12.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #2071

- server/services/notify/notifysubscriptions/diff2slackattachments.go
- server/services/notify/notifysubscriptions/notifier.go
Cherry pick of #2096 on release-0.12.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2096

- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
Fixed a bug where mentions don't show up in descripotions
Fixes #2097
> Fixed a bug where mentions don't show up in descripotions

- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/components/cardDetail/cardDetailProperties.tsx
- webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
- webapp/src/components/kanban/__snapshots__/kanbanCard.test.tsx.snap
- webapp/src/components/propertyValueElement.tsx
Cherry pick of #2103 on release-0.12.
```release-note
NONE
```
> Automated cherry pick of #2103

- server/model/properties.go
Cherry pick of #2110 on release-0.12.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2110

- mattermost-plugin/server/plugin.go
- server/services/config/config.go
- webapp/src/components/cardDialog.tsx
Removes the feature flag for subscriptions
Fixes https://github.com/mattermost/focalboard/issues/2130
> GH-2130: Remove subscriptions feature flag

- mac/Focalboard/Info.plist
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
- win-wpf/AppxManifest.xml
> Update to v0.12.1

- mattermost-plugin/server/plugin.go
- server/services/config/config.go
- webapp/src/components/cardDialog.tsx
Cherry pick of #2132 on release-0.12.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #2132

- website/site/config.toml
> Fixed a typo

- .vscode/launch.json
Add the 'json1' tag to the vscode Go launch command.
> Add json1 tag to vscode launch

- server/api/api.go
- webapp/src/components/content/imageElement.tsx
> Adding gif support for boards

- import/asana/README.md
- import/asana/package-lock.json
- import/notion/README.md
- import/notion/package-lock.json
- import/todoist/package-lock.json
- import/trello/README.md
- import/trello/package-lock.json
- webapp/src/utils.ts
Updates import projects for growth spike.
- Code update which causes imports to currently fail.
- Doc update to clarify some instructions
- package security updates for dependencies
https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/cackk6a45ptns8k8ojnqb1na6xc
> update documents and import issues

- website/site/layouts/partials/hero.html
Cleaned up the homepage links to be more direct, and clearer per audience.
> Update website links.

- .github/ISSUE_TEMPLATE/bug_report.md
Add note about setting the severity in bug reports.
> Add note about Severity labels to bug template

- server/api/api.go
- server/integrationtests/sharing_test.go
Updates API to verify the Configuration for `EnablePublicSharedBoards`
Fixes https://mattermost.atlassian.net/browse/MM-40542
> MM-40542: Verify config setting in api

- website/site/static/css/styles.css
Fix website background for narrow windows / views.
#2149
> Fix #2149. Website background.

- mattermost-plugin/webapp/src/index.tsx
- mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
- webapp/src/telemetry/telemetryClient.ts
Implements registry for ChannelIntro button. 
Fixes https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/canqped3rnty78yz9bedq5ka8qe
https://github.com/mattermost/mattermost-webapp/pull/9683
> [Growth Spike] Implement registry for channel intro button

- website/site/content/download/personal-edition/ubuntu.md
It's possible to run under linode.
> Add links to linode

- mattermost-plugin/webapp/package-lock.json
- mattermost-plugin/webapp/package.json
- webapp/package-lock.json
- webapp/package.json
Updating webapp dependencies for dependabot alerts.
> Update dependencies for webapp and mattermost-plugin/webapp

- CHANGELOG.md
> Update CHANGELOG.md for v0.14 release

- CHANGELOG.md
Cherry pick of #2232 on release-0.14.
/cc  @wuwinson
```release-note
NONE
```
> Automated cherry pick of #2232

- website/site/layouts/partials/hero.html
Update website text with Ben's new copy.
> Website: Update homepage text

- server/api/api.go
- server/app/blocks.go
- server/services/store/sqlstore/blocks.go
- webapp/src/mutator.ts
Cherry pick of #2253 on release-0.14.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2253

- webapp/src/archiver.ts
Cherry pick of #2254 on release-0.14.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2254

- CHANGELOG.md
Cherry pick of #2261 on release-0.14.
/cc  @wuwinson
```release-note
NONE
```
> Automated cherry pick of #2261

- Makefile
- webapp/src/components/cardDialog.test.tsx
- webapp/src/components/cardDialog.tsx
Cherry pick of #2260 on release-0.14.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2260

- webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
- webapp/src/components/globalHeader/globalHeaderSettingsMenu.test.tsx
- webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
- webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
- webapp/src/components/sidebar/sidebarSettingsMenu.test.tsx
- webapp/src/components/sidebar/sidebarSettingsMenu.tsx
- webapp/src/constants.ts
- webapp/src/telemetry/telemetryClient.ts
Add menu items for supported imports with link to help file. 
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vpb5hydjzqtr7txbxeqpjxyfz4o/cackk6a45ptns8k8ojnqb1na6xc
> Growth Spike - implement imports to help redirect

- webapp/src/store/contents.ts
Cherry pick of #2259 on release-0.14.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2259

- mattermost-plugin/server/plugin.go
- server/ws/helpers_test.go
- server/ws/plugin_adapter.go
Cherry pick of #2256 on release-0.14.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #2256

- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorPreview.test.tsx.snap
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.scss
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
GH-2249 - Updating template selector screen
Fixes https://github.com/mattermost/focalboard/issues/2249
Fixes https://github.com/mattermost/focalboard/issues/2236
> GH-2249 - Updating template selector screen

- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorPreview.test.tsx.snap
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.scss
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
Cherry pick of #2279 on release-0.14.
```release-note
NONE
```
> Automated cherry pick of #2279

- server/swagger/README.md
Add notes on how to use the APIs with Mattermost Boards
> API Readme: Add note on Boards API usage.

- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
> Preview the first view of the template

- docs/code-review.md
- docs/contribution-checklist.md
- docs/contributions-without-ticket.md
- docs/dev-tips.md
- docs/index.md
- website/site/content/contribute/getting-started/_index.md
- website/site/content/contribute/getting-started/dev-tips.md
Port contributors guide to GitHub pages.
#2178
> Port contributors guide to GitHub pages

- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
Cherry pick of #2295 on release-0.14.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #2295

- webapp/src/pages/boardPage.scss
See https://github.com/mattermost/mattermost-webapp/pull/9755 for more information
https://mattermost.atlassian.net/browse/MM-41342
> MM-41342 Revert fixes related to using team sidebar in products

- webapp/src/blocks/board.ts
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
Cherry pick of #2221 on release-0.14.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #2221

- webapp/src/components/table/calculation/calculationRow.tsx
Cherry pick of #2262 on release-0.14.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #2262

- website/site/layouts/partials/footer.html
Add standard links to website footer.
> Website: Add links to footer

- CONTRIBUTING.md
A bit of housekeeping to update the very outdated contributors list in contributing.md.
> Update contributors list in contributing.md

- server/model/blocktype.go
- server/services/notify/notifysubscriptions/subscriptions_backend.go
This PR fixes the panic in plugin when creating new cards.  
NONE
> Fix panic when creating new card in notifysubscriptions

- README.md
This PR updates the readme to reflect changes to the standalone app build for Linux.  
NONE
> Update readme with accurate Linux standalone app build instructions

- README.md
- docs/dev-tips.md
- docs/mattermost-boards-dev-guide.md
Draft of developers guide for building and deploying the Boards plugin.
I based most of this from the [thread here](https://community.mattermost.com/core/pl/649rnxgkijfdux5xsmio348gar). Should be a starting point for adding more tips and tricks, e.g. around debugging.
#1957
> Fix #1957. Boards dev guide.

- webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
Fixing template picker delete alignment
> Fixing template picker delete alignment

- webapp/src/components/dialog.scss
GH-2243 - Centering dialog modals
Fixes https://github.com/mattermost/focalboard/issues/2243
> GH-2243 - Centering dialog modals

- webapp/src/components/cardDetail/commentsList.scss
GH-2405 - Updating comment box alignment
Fixes https://github.com/mattermost/focalboard/issues/2405
> GH-2405 - Updating comment box alignment

- webapp/package-lock.json
- webapp/package.json
Fixed tippy version to resolve an issue with tooltip arrows in Mattermost
https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vd89yph84ajbkufkbgts9m3sb5a/cqj1fq3su67rtprsfj7h5x4hooh
> Fixed tippy version to resolve an issue with tooltip arrows in Mattermost

- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/__snapshots__/topBar.test.tsx.snap
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
- win-wpf/AppxManifest.xml
> Update to v0.16.0

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #2354 on release-0.15.
/cc  @akkivasu
```release-note
NONE
```
> Automated cherry pick of #2354

- CHANGELOG.md
Update Focalboard changelog for v0.15
> Update CHANGELOG.md for v0.15

- server/app/onboarding.go
- server/app/onboarding_test.go
Fixed a bug where images of the welcome board were not copied over.
Fixes #2451
> Fixed a bug where images of the welcome board were not copied over.

- webapp/src/components/topBar.scss
- webapp/src/styles/main.scss
GH-2212 - Update global link on board
Fixes #2212
> GH-2212 - Update global link on board

- webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
GH-2330 - Responsive UI update on template picker
Fixes #2330
> GH-2330 - Responsive UI update on template picker

- webapp/src/components/cardDetail/comment.scss
GH-2387 - Fixing link in comments
Fixes https://github.com/mattermost/focalboard/issues/2387
> GH-2387 - Fixing link in comments

- webapp/src/components/topBar.scss
- webapp/src/styles/main.scss
Cherry pick of #2492 on release-0.15.
```release-note
NONE
```
> Automated cherry pick of #2492

- webapp/src/components/cardDetail/comment.scss
Cherry pick of #2480 on release-0.15.
```release-note
NONE
```
> Automated cherry pick of #2480

- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
- webapp/src/components/centerPanel.tsx
- webapp/src/components/viewHeader/viewHeader.test.tsx
- webapp/src/components/viewHeader/viewHeader.tsx
Permissions branch has a build error for webapp (due to https://github.com/mattermost/focalboard/commit/e664becf902f925cad3d43712fbc7b4cd6b52ac4)  This PR fixes it.
NONE
> Permissions branch: Fix webapp compile error, missing enableSharedBoards

- webapp/src/components/centerPanel.scss
Cherry pick of #2497 on release-0.15.
```release-note
NONE
```
> Automated cherry pick of #2497

- webapp/src/components/properties/dateRange/dateRange.scss
Cherry pick of #2466 on release-0.15.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #2466

- webapp/src/pages/boardPage.tsx
> Fix problem with viewId 0 in the URL

- webapp/src/pages/boardPage.tsx
Cherry pick of #2474 on release-0.15.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #2474

- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/components/properties/link/link.scss
GH-2456 - Updating url property
Fixes https://github.com/mattermost/focalboard/issues/2456
> GH-2456 - Updating url property

- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/styles/main.scss
- webapp/src/widgets/label.scss
- webapp/src/widgets/valueSelector.tsx
GH-2447 - Updating label overflow
Fixes https://github.com/mattermost/focalboard/issues/2447
> GH-2447 - Updating label overflow

- webapp/src/pages/boardPage.tsx
Cherry pick of #2499 on release-0.15.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #2499

- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/cardDetail/commentsList.scss
- webapp/src/components/cardDialog.scss
- webapp/src/components/cardDialog.tsx
- webapp/src/components/dialog.scss
- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/shareBoard/shareBoard.scss
- webapp/src/components/shareBoard/shareBoard.tsx
Gh-2437 - Updating share board modal
Fixes https://github.com/mattermost/focalboard/issues/2437
Fixes #2519
> Gh-2437 - Updating share board modal

- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/cardDetail/commentsList.scss
- webapp/src/components/cardDialog.scss
- webapp/src/components/cardDialog.tsx
- webapp/src/components/dialog.scss
- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/shareBoard/shareBoard.scss
- webapp/src/components/shareBoard/shareBoard.tsx
Cherry pick of #2511 on release-0.15.
```release-note
NONE
```
> Automated cherry pick of #2511

- webapp/src/components/globalHeader/globalHeaderSettingsMenu.test.tsx
- webapp/src/components/sidebar/sidebarSettingsMenu.test.tsx
- webapp/src/store/teams.ts
Fixes unit tests caused by updates to submenus.
https://github.com/mattermost/focalboard/commit/5b309e8e25e7455e2b328f25f0a3f62638fe4fc2
> Fix menu tests

- docs/index.md
Updated the link to help wanted bugs that are also up for grabs, plus a couple other minor edits.
> Minor updates to the contributor's guide

- webapp/src/components/cardDialog.test.tsx
- webapp/src/components/centerPanel.test.tsx
- webapp/src/components/onboardingTour/addProperties/add_properties.tsx
- webapp/src/components/pulsating_dot/pulsating_dot.scss
Cherry pick of #2525 on release-0.15.
```release-note
NONE
```
> Automated cherry pick of #2525

- .github/ISSUE_TEMPLATE/bug_report.md
Cleaned up the bug template to try to streamline it a bit.
* Made optional section clearer
* Removed the need for browser version
> Tweaked bug template

- webapp/src/components/shareBoard/userPermissionsRow.tsx
> Show properly the user avatar in the ShareBoard component

- Dockerfile.build
- docker/Dockerfile
This prevents supply chain attacks where the latest image is replaced with a malicious version.
Pinning done by using https://github.com/Jille/dockpin
> Pin the FROM in dockerfiles

- website/site/layouts/partials/hero.html
DOH! Fix bad copy and paste.
#2556
> Fix #2556. Update website link

- webapp/src/components/shareBoard/shareBoard.tsx
> Fixing ShareBoard users ordering

- webapp/src/components/cardDetail/cardDetail.test.tsx
- webapp/src/components/cardDetail/cardDetailContents.test.tsx
- webapp/src/components/cardDetail/cardDetailProperties.test.tsx
- webapp/src/components/cardDetail/commentsList.test.tsx
- webapp/src/components/onboardingTour/addComments/addComments.test.tsx
- webapp/src/components/onboardingTour/addDescription/addDescription.test.tsx
- webapp/src/components/onboardingTour/addProperties/addProperties.test.tsx
- webapp/src/components/onboardingTour/addView/addView.test.tsx
- webapp/src/components/onboardingTour/copyLink/copyLink.test.tsx
- webapp/src/components/onboardingTour/openCard/openCard.test.tsx
- webapp/src/components/onboardingTour/shareBoard/shareBoard.test.tsx
- webapp/src/components/onboardingTour/tourTipRenderer/tourTipRenderer.tsx
- webapp/src/route.tsx
Added flag to allow disabling tour
> Dismiss tour config

- server/services/store/sqlstore/migrate.go
> Fixed bug where migration failed if no teamless board existed

- webapp/src/store/cards.ts
- webapp/src/store/comments.ts
> Fixing the sorting of cards taking into consideration the last comment date

- webapp/src/components/viewMenu.tsx
- webapp/src/widgets/menu/menu.tsx
- webapp/src/widgets/menu/subMenuOption.tsx
> Fix hover menu behavior on ViewHeader component

- mattermost-plugin/webapp/src/index.tsx
> Fixing redirects on team change outside of boards

- webapp/cypress/global.d.ts
- webapp/cypress/integration/cardURLProperty.ts
- webapp/cypress/integration/createBoard.ts
- webapp/cypress/integration/loginActions.ts
- webapp/cypress/support/api_commands.ts
Took @kamre patch he provided here - https://github.com/mattermost/focalboard/pull/2676#issuecomment-1082226961
And applied that patch to fix cypress tests...
Fixes https://github.com/mattermost/focalboard/issues/2670
> Fixes for cypress tests

- server/api/api.go
- server/api/archive.go
- server/app/import.go
- server/app/import_test.go
- server/app/templates_test.go
Archive import was broken after permissions branch merge.
- API route was incorrect
- user was not added to the newly created boards
fixes https://github.com/mattermost/focalboard/issues/2692
fixes https://github.com/mattermost/focalboard/issues/2629
> GH-2692 - Fix archive import

- import/asana/importAsana.ts
- import/jira/jiraImporter.test.ts
- import/jira/jiraImporter.ts
- import/nextcloud-deck/importDeck.ts
- import/notion/importNotion.ts
- import/todoist/importTodoist.ts
- import/trello/importTrello.ts
- import/util/archive.ts
This PR fixes the import scripts broken via Permissions branch merge.
**Note: I only tested Asana import script, but the others should work if they worked before the merge**
fixes https://github.com/mattermost/focalboard/issues/2638
> GH-2638 - Fix Import scripts

- webapp/src/components/cardDetail/cardDetail.scss
GH-2708 - Updating z-index for dropdown list
Fixes #GH-2708
> GH-2708 - Updating z-index for dropdown list

- webapp/src/components/viewMenu.tsx
> Fixed bug where next view wasn't selected

- mattermost-plugin/webapp/src/index.tsx
Updates introduction link to use teams rather than channels.
Fixes https://github.com/mattermost/focalboard/issues/2709
> update link for teams

- server/services/store/sqlstore/boards_and_blocks.go
Make all duplicated boards private.
Fixes https://github.com/mattermost/focalboard/issues/2822
> make all duplicated boards private

- server/api/api.go
- server/app/import.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/sqlstore/board.go
- server/services/store/sqlstore/migrate.go
- server/services/store/store.go
- server/ws/plugin_adapter.go
This PR is a first pass at cleaning up log levels.  This pass is focused on moving log entries out of ERROR or INFO when they are not useful for customers to see or report.
fixes https://github.com/mattermost/focalboard/issues/2750
> GH-2750 - Cleanup log levels

- webapp/src/components/calendar/fullCalendar.tsx
Adds key to FullCalendar component so it is reloaded rather then reused. If switching from one calendar view from another calendar view.
Fixes https://github.com/mattermost/focalboard/issues/2506
> GH-2506 Calendar View

- webapp/src/components/propertyValueElement.tsx
The PR will allow selecting the option in the select property.
Fixes https://github.com/mattermost/focalboard/issues/2867
> Added the dependency for useCallback in onChangeInSelect function

- webapp/src/components/addContentMenuItem.test.tsx
- webapp/src/components/addContentMenuItem.tsx
- webapp/src/components/cardDetail/cardDetailContents.tsx
- webapp/src/components/cardDetail/cardDetailContext.tsx
- webapp/src/components/cardDetail/imagePaste.tsx
> Fixing redo on card contents

- mattermost-plugin/Makefile
- mattermost-plugin/go.mod
- mattermost-plugin/server/configuration.go
- mattermost-plugin/server/configuration_test.go
- mattermost-plugin/server/data_retention.go
- mattermost-plugin/server/data_retention_test.go
- mattermost-plugin/server/plugin.go
- mattermost-plugin/server/plugin_test.go
- server/server/server.go
- server/services/config/config.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/data_retention.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/sqlstore_test.go
- server/services/store/store.go
- server/services/store/storetests/data_retention.go
Implement Data Retention for Boards
- mattermost-webapp and mattermost-server already have necessary changes.
Fixes https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vezy9zbpm1tnmfecbuoopjgsgqc/c88h9o9twcbgw787cd61r5a3wkw
> Implement Boards Data Retention - Take 2

- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/shareBoard/shareBoard.scss
- webapp/src/components/shareBoard/shareBoard.test.tsx
- webapp/src/components/shareBoard/shareBoard.tsx
This is at least a partial fix. It has been styled to match the members list in the same dialog. 
We currently do not return the user Full Name nor their status, so we cannot do the complete style called for in the spec this release. I have [created a new ticket to track](https://github.com/mattermost/focalboard/issues/2933) this for next release.
Fixes https://github.com/mattermost/focalboard/issues/2877
> GH-2877 - Style Autocomplete Modal

- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
- webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
- webapp/src/components/globalHeader/globalHeaderSettingsMenu.test.tsx
- webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
Fixes #2865
The bug was that I wasn't setting the user prop that indicated the tour has started. So skipping from the welcome page never allowed you to restart the tour.
> Fixed bug ehere start tour param was not sent when restarting touyr

- mattermost-plugin/server/manifest.go
- webapp/src/components/__snapshots__/topBar.test.tsx.snap
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Update the month for v0.16.0 to "May" and the server version to "0.6.7"
Note: this is merging directly to `release-0.16`
> Update month and min server version

- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/__snapshots__/topBar.test.tsx.snap
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- win-wpf/AppxManifest.xml
> Update for v0.17.0

- webapp/src/components/properties/lastModifiedBy/__snapshots__/lastModifiedBy.test.tsx.snap
- webapp/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/table.test.tsx
The PR fixes the alignment of the last updated field in the card view.
Fixes https://github.com/mattermost/focalboard/issues/2874
> Last updated by aligement fixed

- webapp/src/components/shareBoard/userPermissionsRow.tsx
> Remove viewer role from the interface

- webapp/src/store/cards.ts
Cherry pick of #2986 on release-0.16.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #2986

- webapp/src/pages/boardPage/websocketConnection.tsx
Cherry pick of #2997 on release-0.16.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #2997

- webapp/src/components/properties/lastModifiedBy/__snapshots__/lastModifiedBy.test.tsx.snap
- webapp/src/components/properties/lastModifiedBy/lastModifiedBy.tsx
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/table.test.tsx
Cherry pick of #2937 on release-0.16.
```release-note
NONE
```
> Automated cherry pick of #2937

- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/components/kanban/calculation/calculationOption.scss
- webapp/src/components/kanban/kanban.scss
- webapp/src/components/kanban/kanbanCard.scss
> Minor UI Updates to Card title and Column Dropdown

- webapp/src/components/createCategory/createCategory.tsx
This PR adds a feature of creating categories by hitting the enter button inside Category model
Fixes: https://github.com/mattermost/focalboard/issues/2863
> Feature added: Pressing enter should create a category

- server/services/store/sqlstore/boards_and_blocks.go
Cherry pick of #3011 on release-0.16.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3011

- webapp/src/store/boards.ts
Cherry pick of #2969 on release-0.16.
```release-note
NONE
```
> Automated cherry pick of #2969

- webapp/src/components/createCategory/createCategory.tsx
(cherry picked from commit c08ce96)
Cherry for https://github.com/mattermost/focalboard/pull/2940
> Creating category by pressing enter button (#2944)

- mattermost-plugin/webapp/src/plugin.scss
- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/shareBoard/shareBoard.scss
- webapp/src/components/shareBoard/teamPermissionsRow.tsx
- webapp/src/components/shareBoard/userPermissionsRow.tsx
- webapp/src/styles/_modifiers.scss
- webapp/src/styles/main.scss
- webapp/src/theme.ts
2889 - Hiding images on share modal on personal
Also made some other minor UI updates.
Fixes #2889 
Fixes #2888
> 2889 - Hiding images on share modal on personal

- mattermost-plugin/webapp/src/plugin.scss
- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/shareBoard/shareBoard.scss
- webapp/src/components/shareBoard/teamPermissionsRow.tsx
- webapp/src/components/shareBoard/userPermissionsRow.tsx
- webapp/src/styles/_modifiers.scss
- webapp/src/styles/main.scss
- webapp/src/theme.ts
Cherry pick of #2925 on release-0.16.
```release-note
NONE
```
> Automated cherry pick of #2925

- server/app/blocks.go
- server/app/boards.go
Cherry pick of #3012 on release-0.16.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3012

- mattermost-plugin/server/manifest.go
- webapp/src/components/content/textElement.test.tsx
- webapp/src/components/contentBlock.test.tsx
- webapp/src/components/markdownEditor.test.tsx
- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
> All team users autocomplete new

- webapp/src/components/table/table.test.tsx
This PR fixes webapp in main which has a broken jest test.
NONE
> Fix broken webapp in main

- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- mattermost-plugin/webapp/package-lock.json
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/__snapshots__/topBar.test.tsx.snap
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
> Update version to 7.0.0

- webapp/src/store/cards.ts
Backports fix for crash during search.
https://github.com/mattermost/focalboard/issues/2970
https://github.com/mattermost/focalboard/pull/2986
Fixes https://github.com/mattermost/focalboard/issues/3066
> Fix for null propertyValue

- webapp/src/components/calendar/__snapshots__/fullCalendar.test.tsx.snap
- webapp/src/components/calendar/fullCalendar.tsx
- webapp/src/components/calendar/fullcalendar.scss
- webapp/src/components/messages/cloudMessage.tsx
Backports fix for read-only calendar, also fixes read-only view displays cloud message.
Fixes https://github.com/mattermost/focalboard/issues/3060
> GH-3060 Fix Read-only calendar

- webapp/cypress/integration/cardBadges.ts
- webapp/i18n/en.json
- webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorPreview.test.tsx.snap
- webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/viewHeader/__snapshots__/viewHeader.test.tsx.snap
- webapp/src/components/viewHeader/__snapshots__/viewHeaderSearch.test.tsx.snap
- webapp/src/components/viewHeader/viewHeader.scss
- webapp/src/components/viewHeader/viewHeaderSearch.test.tsx
- webapp/src/components/viewHeader/viewHeaderSearch.tsx
Adding search bar instead of search button for board
> Adding search bar instead of search button for board

- mattermost-plugin/server/plugin.go
- server/api/api.go
- server/app/cloud.go
- server/app/cloud_test.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/store.go
- server/services/store/storetests/blocks.go
This PR adds testing to the apply cloud limit logic and improves it to limit only non-template cards
> Improve apply cloud limits to leave templates unlimited

- webapp/cypress/integration/createBoard.ts
Fixes https://github.com/mattermost/focalboard/pull/3074#issuecomment-1136036930.
N/A
> Cypress test `wait` increase

- server/api/api.go
- server/app/app.go
- server/server/server.go
- webapp/cypress/integration/createBoard.ts
- webapp/src/octoClient.ts
This PR fixes the issue of system admins not getting notifications when user request upgrades.  
fixes https://github.com/mattermost/focalboard/issues/3123
> GH-3123 Fix notify admin on request upgrade

- webapp/i18n/en.json
- webapp/src/components/viewHeader/viewHeader.tsx
- webapp/src/components/viewLimitDialog/viewLimitDialog.tsx
- webapp/src/components/viewLimitDialog/viewLimitDialogWrapper.scss
- webapp/src/components/viewLimitDialog/viewLimitDialogWrapper.tsx
- webapp/src/widgets/notification-box.scss
- webapp/src/widgets/notification-box.tsx
Fixes #3145
Implements https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vch9s93uimjrfik7fisjczzpfkc/cmrzk8jek5igfmmkimqroahzish
Demo-
https://user-images.githubusercontent.com/18575143/171136987-493496c0-3047-4c5f-8679-bbb519a4dc84.mp4
> Added success toast for notify admin

- webapp/src/components/cardLimitNotification.tsx
- webapp/src/components/centerPanel.tsx
- webapp/src/store/limits.ts
> Fixing Issue 3124

- webapp/src/widgets/valueSelector.scss
Fix CSS selector for ValueSelector menu. 
Fixes #3170
> [GH-3170] Fix overflow for ValueSelector menu

- server/web/webserver.go
> Allowing subpath in development environment

- webapp/src/components/centerPanel.tsx
- webapp/src/components/workspace.tsx
- webapp/src/store/limits.ts
Fixes https://github.com/mattermost/focalboard/issues/3175
> Fix limits selector and stores limitsEnabled value to avoid race condition

- webapp/src/components/calendar/fullcalendar.scss
Backport fix to 7.0. 
Fixes https://github.com/mattermost/focalboard/issues/3143
> GH-3143 Fix for calendar popout transparency

- mac/Focalboard/Info.plist
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
> update version to v7.0.1

- webapp/src/pages/errorPage.tsx
> Fixed a bug causing error page when new users signs up

- mattermost-plugin/webapp/src/index.tsx
- mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
- webapp/src/insights/index.ts
- webapp/src/octoClient.ts
New client function and connecting to new registry handler for insights
https://mattermost.atlassian.net/browse/MM-44657
> [MM-44657] Client side code for insights

- mattermost-plugin/server/plugin.go
- server/api/api.go
- server/server/params.go
- server/server/server.go
Fixes https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/vuswsftt1rb873datosmmbtwkpa/cg9qq1rceetndmkwctwwexnjyfe
> Not registering personal-server exclusive APIs in plugin mode

- webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
- webapp/src/components/viewMenu.scss
- webapp/src/components/viewMenu.tsx
This Pr will fix the issue of accessing all views from the view switcher a s-list goes beyond viewport
Fixes https://github.com/mattermost/focalboard/issues/3106
> Added the scroll to all the view in the drop down for view switcher

- webapp/src/components/cardDetail/cardDetail.tsx
Fixes https://github.com/mattermost/focalboard/issues/2982
> Resized the add icon button in card Dailog

- mattermost-plugin/.golangci.yml
- server/.golangci.yml
- server/services/store/sqlstore/migrate.go
Reimplement Cyclomatic complexity check 
Update migrate() to use defer in order to reduce CC.
Fixes https://github.com/mattermost/focalboard/issues/2645
> add cyclo complexity, update migrate() to use defer

- mattermost-plugin/webapp/src/index.tsx
> Opening the dashboard if the current channel ID is not available

- server/services/store/sqlstore/migrations/000017_add_file_info.up.sql
Make CREATE TABLE idempotent.
NONE
Reported here:  https://community.mattermost.com/private-core/pl/dopgtyckftf4zmfspsogh9az8e
> Make CREATE TABLE idempotent for migration 17

- mac/Focalboard.xcodeproj/project.pbxproj
- mac/Focalboard/AppDelegate.swift
- mac/Focalboard/Base.lproj/Main.storyboard
- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mac/Focalboard/WhatsNewViewController.swift
- mac/Focalboard/whatsnew.txt
Cherry pick the fix for #3268 to release-7.0.
> Cherry pick #3268 to release-7.0

- mac/Focalboard.xcodeproj/project.pbxproj
- mac/Focalboard/AppDelegate.swift
- mac/Focalboard/Base.lproj/Main.storyboard
- mac/Focalboard/Globals.swift
- mac/Focalboard/Info.plist
- mac/Focalboard/WhatsNewViewController.swift
- mac/Focalboard/whatsnew.txt
Cherry pick fix for #3268 to main
> Cherry pick fix for #3268 to main

- website/site/config.toml
Post-launch there have been a few copy tweaks. I will replace the actual files in the S3 Bucket, but will leave this PR open for a week or so just in case we catch any more. Then we can do one merge with all the edits.
cc: @chenilim
> focalboard.com edits

- webapp/src/components/__snapshots__/topBar.test.tsx.snap
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/components/sidebar/sidebarUserMenu.tsx
- webapp/src/components/topBar.tsx
- webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
Cherry-pick for https://github.com/mattermost/focalboard/pull/3274
> Replaced versionDisplayString with versionString

- experiments/webext/package-lock.json
- mattermost-plugin/webapp/package-lock.json
- mattermost-plugin/webapp/package.json
- webapp/package-lock.json
- webapp/package.json
> update webapp dependencies

- webapp/cypress/integration/cardURLProperty.ts
PR to partially disable Cypress test to unblock PRs for `main`.   Issue https://github.com/mattermost/focalboard/issues/3318 has been created to fix and re-enable the test.
NONE
> Partially disable failing cypress test

- server/app/cloud.go
Logs when cloud limits are being set.
> Add loggin on cloud limits set

- server/app/cloud.go
Cherry pick of #3337 on release-7.1.
```release-note
NONE
```
> Automated cherry pick of #3337

- webapp/src/octoClient.ts
> Fixed incorrect API path being used for notify admin upgrade API

- webapp/src/components/viewHeader/viewHeader.scss
- webapp/src/widgets/menu/menu.scss
Minor UI Updates - Border on menu, and search icon alignment
> Minor UI Updates - Border on menu, and search icon alignment

- mac/Focalboard.xcodeproj/project.pbxproj
- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
This PR updates all version references to point to 7.3
> Update Boards version to 7.3

- server/services/store/sqlstore/migrate.go
Cherry pick of #3406 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3406

- server/services/store/sqlstore/data_migrations.go
- server/services/store/sqlstore/migrate.go
This PR will help admins to have more insights on what's happening during database migrations
> Adds more loglines to the database migrations and fixes some inconsistencies

- server/services/store/sqlstore/data_migrations.go
- server/services/store/sqlstore/migrate.go
Cherry pick for https://github.com/mattermost/focalboard/pull/3392
> Adds more loglines to the database migrations and fixes some inconsistencies (#3392)

- webapp/src/components/shareBoard/shareBoard.scss
Cherry pick of #3393 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3393

- mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
> Openning the board in a new window from the RHS in channels

- webapp/src/components/shareBoard/teamPermissionsRow.tsx
- webapp/src/components/shareBoard/userPermissionsRow.tsx
> Removing unexpected roles from the team/user selector in share board modal

- .github/workflows/lint-server.yml
PR contains changes to fix lint pipeline for multi-product architecture. We need to clone mattermost-server repo for the lint to work.
> Fix lint pipeline 

- server/services/store/sqlstore/data_migrations.go
Cherry pick of #3420 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3420

- mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
Cherry pick of #3416 on main.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3416

- mattermost-plugin/webapp/src/components/boardSelector.tsx
- mattermost-plugin/webapp/src/index.tsx
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
- webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
- webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
- webapp/src/components/sidebar/sidebarCategory.tsx
- webapp/src/components/viewMenu.tsx
- webapp/src/components/workspace.tsx
- webapp/src/pages/boardPage/boardPage.tsx
- webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
- webapp/src/router.tsx
- webapp/src/types/index.d.ts
- webapp/src/utils.ts
Cherry pick of #3415 on main.
fixes #3367 
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3415

- webapp/src/components/shareBoard/shareBoard.tsx
Cherry pick of #3429 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3429

- webapp/src/widgets/menu/textInputOption.tsx
- webapp/src/widgets/propertyMenu.test.tsx
- webapp/src/widgets/propertyMenu.tsx
Cherry pick of #3256 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3256

- server/services/store/sqlstore/data_migrations.go
- server/services/store/sqlstore/migrations/000019_populate_categories.up.sql
- server/services/store/sqlstore/migrations/000020_populate_category_blocks.up.sql
Cherry pick of #3437 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3437

- server/app/boards.go
- server/app/boards_test.go
> Converted synthetic membership to natuaral for board's channel members

- server/app/boards.go
- server/app/boards_test.go
Cherry pick of #3390 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3390

- webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
> Added min height for template sepector

- server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
Cherry pick of #3454 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3454

- webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
- webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
- webapp/src/components/searchDialog/searchDialog.scss
- webapp/src/components/searchDialog/searchDialog.tsx
- webapp/src/constants.ts
Cherry pick of #3242 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3242

- webapp/src/components/sidebar/sidebarBoardItem.scss
- webapp/src/components/sidebar/sidebarBoardItem.tsx
- webapp/src/components/sidebar/sidebarCategory.scss
- webapp/src/components/sidebar/sidebarCategory.tsx
- webapp/src/widgets/menu/menu.tsx
- webapp/src/widgets/menu/menuUtil.ts
- webapp/src/widgets/menu/subMenuOption.tsx
Cherry pick of #3426 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3426

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This PR adds a pull request template for Github.  The template includes instructions to assign 2 reviewers.
NONE
> Add pull request template for Github

- webapp/src/pages/boardPage/boardPage.tsx
Cherry pick of #3473 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3473

- server/api/api.go
- server/app/auth.go
- server/services/permissions/mmpermissions/mocks/mockpluginapi.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/user.go
- server/services/store/store.go
- server/ws/mocks/mockpluginapi.go
- webapp/cypress/integration/cardURLProperty.ts
- webapp/src/octoClient.ts
- webapp/src/store/boards.ts
Cherry pick of #3379 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3379

- webapp/src/wsclient.ts
Cherry pick of #3485 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3485

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #3490 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3490

- mattermost-plugin/webapp/src/components/boardSelector.scss
- webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.scss
- webapp/src/components/kanban/kanbanCard.scss
- webapp/src/components/searchDialog/searchDialog.scss
- webapp/src/components/sidebar/sidebarBoardItem.scss
- webapp/src/components/viewHeader/filterEntry.scss
- webapp/src/components/viewTitle.scss
- webapp/src/pages/welcome/welcomePage.scss
- webapp/src/widgets/menu/menu.scss
3276 - FIxing text overflow on menus
3185 - Fixing card title overlap with menu
2521 - Adding scrollbar to board description
3360 - Updating filter button overflow
3191 - Welcome screen scrolling fix
3445 - Updating board switcher UI
Fixes #3276 
Fixes #3185 
Fixes #2521
Fixes #3360
Fixes #3191 
Fixes #3442
> Various UI fixes

- webapp/src/components/shareBoard/channelPermissionsRow.tsx
Cherry pick of #3430 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3430

- webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
- webapp/src/components/sidebar/sidebarBoardItem.scss
- webapp/src/components/sidebar/sidebarBoardItem.tsx
Cherry pick of #3501 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3501

- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.tsx
- webapp/src/components/cardDialog.tsx
- webapp/src/components/centerPanel.tsx
- webapp/src/components/kanban/kanban.test.tsx
- webapp/src/components/kanban/kanban.tsx
- webapp/src/components/kanban/kanbanCard.tsx
- webapp/src/mutator.ts
Cherry pick of #3444 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3444

- webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
Cherry pick of #3427 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3427

- mattermost-plugin/plugin.json
Update minimum server version to 7.2. 
Fixes #3535
> update min server version to 7.2

- webapp/src/components/calendar/fullCalendar.tsx
- webapp/src/components/calendar/fullcalendar.scss
- webapp/src/styles/_z-index.scss
Cherry pick of #3486 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3486

- webapp/src/components/viewMenu.scss
Cherry pick of #3504 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3504

- server/api/api.go
- webapp/src/components/shareBoard/channelPermissionsRow.tsx
- webapp/src/components/shareBoard/shareBoard.tsx
Cherry pick of #3529 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3529

- webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
- webapp/src/components/sidebar/sidebarCategory.test.tsx
- webapp/src/components/sidebar/sidebarCategory.tsx
Show the active board even when the category is hidden.
> Show the active board even when the category is hidden

- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
- webapp/src/components/sidebar/sidebarCategory.test.tsx
- webapp/src/components/sidebar/sidebarCategory.tsx
Cherry pick of #3556 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3556

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Manual cherry-pick of https://github.com/mattermost/focalboard/pull/3552 and fix merge conflict.
NONE
> Cherry pick PR 3552

- webapp/src/pages/boardPage/boardPage.tsx
- webapp/src/store/boards.ts
Cherry pick of #3388 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3388

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Additional fix for GetMemberForBoard returning nil,nil 
See https://github.com/mattermost/focalboard/pull/3552
NONE
> Additional fix for GetMemberForBoard returning nil,nil 

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #3570 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3570

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #3557 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3557

- mattermost-plugin/webapp/src/components/boardSelector.test.tsx
- mattermost-plugin/webapp/src/components/boardSelector.tsx
- server/api/api.go
- server/integrationtests/permissions_test.go
- webapp/src/octoClient.ts
Cherry pick of #3553 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3553

- mattermost-plugin/webapp/src/index.tsx
Cherry pick of #3499 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3499

- webapp/cypress/support/api_commands.ts
- webapp/i18n/en.json
- webapp/package-lock.json
- webapp/src/components/messages/versionMessage.scss
- webapp/src/components/messages/versionMessage.test.tsx
- webapp/src/components/messages/versionMessage.tsx
- webapp/src/pages/boardPage/boardPage.tsx
- webapp/src/store/users.ts
- webapp/src/telemetry/telemetryClient.ts
Cherry pick of #3522 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3522

- mattermost-plugin/webapp/src/index.tsx
- webapp/src/pages/boardPage/boardPage.tsx
- webapp/src/types/index.d.ts
Cherry pick of #3602 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3602

- mattermost-plugin/server/manifest.go
- server/model/category.go
- server/services/store/sqlstore/category.go
- server/services/store/sqlstore/migrations/000023_persist_category_collapsed_state.down.sql
- server/services/store/sqlstore/migrations/000023_persist_category_collapsed_state.up.sql
- server/services/store/sqlstore/migrations/000024_mark_existsing_categories_collapsed.down.sql
- server/services/store/sqlstore/migrations/000024_mark_existsing_categories_collapsed.up.sql
- server/services/store/sqlstore/sqlstore_test.go
- server/services/store/storetests/category.go
- server/services/store/storetests/categoryBoards.go
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/components/sidebar/sidebar.test.tsx
- webapp/src/components/sidebar/sidebarCategory.tsx
- webapp/src/store/sidebar.ts
- webapp/src/test/testBlockFactory.ts
* WIP
* Finished impl
* Finished impl
* Added tests
* Refactored SQL migraiton into two migration to keep DDL isolated
(cherry picked from commit e855a37c215fdb1797aadf5b6c03df2f577db5fb)
> Persist category state (#3579)

- server/services/store/sqlstore/data_migrations.go
- server/services/store/sqlstore/migrate.go
Cherry pick of #3613 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3613

- webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
- webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.scss
- webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.test.tsx
- webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
Cherry pick of #3626 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3626

- mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
- mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
- mattermost-plugin/webapp/src/components/boardSelectorItem.scss
- mattermost-plugin/webapp/src/components/boardSelectorItem.tsx
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx
- webapp/src/components/table/table.scss
Cherry pick of #3581 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3581

- webapp/src/components/sidebar/sidebar.scss
GH-3544 - Updating scrollbar color
Fixes #3544
> GH-3544 - Updating scrollbar color for sidebar

- server/app/boards.go
- server/app/onboarding_test.go
- server/client/client.go
- server/integrationtests/board_test.go
- server/model/category.go
- webapp/src/components/sidebar/sidebarBoardItem.tsx
Cherry pick of #3395 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3395

- mattermost-plugin/server/manifest.go
- webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
- webapp/src/components/table/tableRow.tsx
Don't display drag and delete menu in table view if readonly
Fixes https://github.com/mattermost/focalboard/issues/3601
> check readonly flag before displaying row menu

- webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
- webapp/src/components/table/tableRow.tsx
Cherry pick of #3611 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3611

- webapp/src/components/viewHeader/newCardButton.tsx
Cherry pick of #3609 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3609

- server/ws/plugin_adapter.go
- server/ws/plugin_adapter_cluster.go
Cherry pick of #3594 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3594

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Updating User channel search to make it case insensitive when searching titles
Fixes https://github.com/mattermost/focalboard/issues/3621
> GH-3621- Make query case insensitive

- mattermost-plugin/webapp/package.json
- webapp/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
- webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx
- webapp/src/components/onboardingTour/index.ts
- webapp/src/components/onboardingTour/manageBoards/manageBoards.scss
- webapp/src/components/onboardingTour/manageBoards/manageBoards.tsx
- webapp/src/components/onboardingTour/manageCategories/manageCategories.scss
- webapp/src/components/onboardingTour/manageCategories/manageCategories.tsx
- webapp/src/components/onboardingTour/searchForBoards/searchForBoards.scss
- webapp/src/components/onboardingTour/searchForBoards/searchForBoards.tsx
- webapp/src/components/onboardingTour/sidebarCategories/sidebarCategories.scss
- webapp/src/components/onboardingTour/sidebarCategories/sidebarCategories.tsx
- webapp/src/components/onboardingTour/tourTipRenderer/tourTipRenderer.tsx
- webapp/src/components/searchDialog/searchDialog.tsx
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarCategory.test.tsx.snap
- webapp/src/components/sidebar/sidebar.test.tsx
- webapp/src/components/sidebar/sidebar.tsx
- webapp/src/components/sidebar/sidebarBoardItem.scss
- webapp/src/components/sidebar/sidebarBoardItem.tsx
- webapp/src/components/sidebar/sidebarCategory.scss
- webapp/src/components/sidebar/sidebarCategory.test.tsx
- webapp/src/components/sidebar/sidebarCategory.tsx
Cherry pick of #3619 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3619

- webapp/src/components/sidebar/sidebar.scss
Cherry pick of #3617 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3617

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/sqlstore/board.go
Cherry pick of #3622 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3622

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #3623 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3623

- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/shareBoard/shareBoard.test.tsx
- webapp/src/components/shareBoard/shareBoard.tsx
Don't display channel roles in ShareBoard if board is a template.
Fixes https://github.com/mattermost/focalboard/issues/3625
> don't display channel roles if board is a template

- server/app/boards.go
Cherry pick of #3598 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3598

- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/shareBoard/shareBoard.test.tsx
- webapp/src/components/shareBoard/shareBoard.tsx
Cherry pick of #3639 on release-7.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3639

- mattermost-plugin/webapp/src/index.tsx
Cherry pick of #3651 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3651

- server/services/store/sqlstore/data_migrations.go
- server/services/store/sqlstore/legacy_blocks.go
- server/services/store/sqlstore/migrate.go
Cherry pick of #3635 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3635

- webapp/src/components/workspace.tsx
Cherry pick of #3657 on release-7.2.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #3657

- webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx
Cherry pick of #3673 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3673

- mattermost-plugin/server/plugin.go
- server/main/main.go
- server/model/version.go
Cherry-pick for https://github.com/mattermost/focalboard/pull/3711
> Print log server information on plugin run (#3711)

- webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
- webapp/src/components/kanban/kanban.test.tsx
- webapp/src/components/kanban/kanban.tsx
Cherry pick of #3696 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3696

- webapp/src/pages/boardPage/boardPage.scss
Stack second banner message, on top of one if one exists.
Fixes https://github.com/mattermost/focalboard/issues/3694
https://user-images.githubusercontent.com/12704875/186273159-33d4da17-5cb2-490a-9f47-0efc6693aa0f.mov
> stack banners if multiple displayed

- server/services/store/sqlstore/migrations/000025_indexes_update.down.sql
- server/services/store/sqlstore/migrations/000025_indexes_update.up.sql
- server/services/store/storetests/blocks.go
Cherry pick of #3732 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3732

- server/services/store/sqlstore/sqlstore.go
Cherry pick of #3725 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #3725

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to 7.2.1

- webapp/src/store/contents.ts
Fix issue returning from function early without full processing changes.
Fixes https://github.com/mattermost/focalboard/issues/3704
> GH-3704 - Fix for not copying all content items.

- webapp/src/components/propertyValueElement.tsx
This PR checks for the undefined default value for all the properties in a particular card.
Fixes https://github.com/mattermost/focalboard/issues/3751
> Undefined check for propertyValue

- mattermost-plugin/server/boards/boardsapp_util.go
- server/server/server.go
- server/services/config/config.go
Cherry pick of #3817 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3817

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update to version 7.4.0

- webapp/src/properties/multiperson/multiperson.tsx
Cherry pick of #3793 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3793

- Makefile
- server/api/teams.go
- server/app/user.go
- server/integrationtests/pluginteststore.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/user.go
- server/services/store/store.go
- server/swagger/docs/html/index.html
- server/swagger/swagger.yml
- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
- webapp/src/components/shareBoard/shareBoard.tsx
- webapp/src/octoClient.ts
- webapp/src/properties/person/person.tsx
Cherry pick of #3762 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3762

- mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/__snapshots__/confirmAddUserForNotifications.test.tsx.snap
- webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
- webapp/src/components/__snapshots__/dialog.test.tsx.snap
- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
- webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
- webapp/src/components/cardDialog.scss
- webapp/src/components/cardDialog.tsx
- webapp/src/components/createCategory/__snapshots__/createCategory.test.tsx.snap
- webapp/src/components/createCategory/createCategory.test.tsx
- webapp/src/components/createCategory/createCategory.tsx
- webapp/src/components/dialog.scss
- webapp/src/components/dialog.tsx
- webapp/src/components/searchDialog/searchDialog.scss
- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialog.test.tsx.snap
- webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialogWrapper.test.tsx.snap
Cherry pick of #3827 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3827

- webapp/src/components/messages/versionMessage.tsx
Cherry pick of #3822 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3822

- server/app/boards.go
- server/app/boards_test.go
- server/server/server.go
- server/services/metrics/metrics.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/store.go
- server/services/store/storetests/boards.go
Cherry pick of #3820 on release-7.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3820

- webapp/src/components/shareBoard/shareBoard.tsx
Cherry pick of #3841 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3841

- webapp/src/components/shareBoard/shareBoard.tsx
Fixes a lint issue that got into main, causing build in main to fail.
> fix lint issue that snuck through

- server/api/users.go
- server/app/auth.go
- server/app/auth_test.go
- server/app/onboarding.go
- server/app/onboarding_test.go
- server/app/user.go
- server/integrationtests/permissions_test.go
- server/integrationtests/pluginteststore.go
- server/model/user.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/user.go
- server/services/store/store.go
- server/services/store/storetests/users.go
- server/services/store/storetests/util.go
Cherry pick for https://github.com/mattermost/focalboard/pull/3843
> Update user store to return the updated entities after inserting / patching them (#3843)

- mattermost-plugin/webapp/src/components/rhsChannelBoardItem.test.tsx
- webapp/src/blocks/board.ts
- webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
- webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
- webapp/src/components/shareBoard/teamPermissionsRow.tsx
- webapp/src/components/shareBoard/userPermissionsRow.tsx
- webapp/src/hooks/permissions.tsx
- webapp/src/pages/boardPage/boardPage.tsx
- webapp/src/properties/person/person.tsx
- webapp/src/store/boards.ts
Co-authored-by: Scott Bishel <scott.bishel@mattermost.com>
Co-authored-by: Mattermod <mattermod@users.noreply.github.com>
(cherry picked from commit 03d1b584ca06d7b64a502adac552aa3e34c4b108)
> Fixing minimum board roles behavior (#3836)

- server/api/users.go
Fixes compilation issue on `main`
> removed non-existent field

- webapp/src/wsclient.ts
Cherry pick of #3858 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3858

- webapp/src/properties/multiperson/multiperson.tsx
> Fixes app crash in multiperson property if user is removed from board

- webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
- webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
- webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
- webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
- webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
- webapp/src/widgets/buttons/buttonWithMenu.scss
- webapp/src/widgets/menu/subMenuOption.scss
- webapp/src/widgets/menu/subMenuOption.tsx
Gh 3849 - Fixing menu text and submenu icon
Fixes #3849
> Gh 3849 - Fixing menu text and submenu icon

- webapp/src/components/__snapshots__/blockIconSelector.test.tsx.snap
- webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
- webapp/src/components/__snapshots__/viewMenu.test.tsx.snap
- webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
- webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
- webapp/src/widgets/buttons/buttonWithMenu.scss
- webapp/src/widgets/menu/subMenuOption.scss
- webapp/src/widgets/menu/subMenuOption.tsx
Cherry pick of #3857 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3857

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Cherry pick of #3819 on release-7.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3819

- webapp/src/pages/boardPage/boardPage.tsx
Cherry pick of #3880 on release-7.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3880

- webapp/src/components/confirmAddUserForNotifications.scss
Cherry pick of #3887 on release-7.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3887

- webapp/src/properties/multiperson/multiperson.tsx
- webapp/src/properties/person/person.tsx
- webapp/src/utils.ts
Co-authored-by: Mattermod <mattermod@users.noreply.github.com>
(cherry picked from commit 3c8f6324e45d678807cbe313f50c11fdbeb862a3)
> Gh 3884 Fix Multiperson property (#3888)

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update to version 7.5.0

- mattermost-plugin/webapp/src/components/rhsChannelBoards.scss
Cherry pick of #3908 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3908

- webapp/src/components/sidebar/sidebarCategory.tsx
> Fixed incorrect params to create/update categroy component

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #3786 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3786

- mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
- mattermost-plugin/webapp/src/components/boardSelector.test.tsx
- mattermost-plugin/webapp/src/components/boardSelector.tsx
Cherry pick of #3850 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #3850

- webapp/src/components/cardDetail/cardDetailProperties.test.tsx
- webapp/src/components/cardDetail/cardDetailProperties.tsx
Cherry pick of #3920 on release-7.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3920

- webapp/src/properties/person/person.scss
Fix text color by adding css color on person
Fix #3918
> fix[GH-3918]: add color on person class

- server/api/members.go
- server/integrationtests/board_test.go
- server/integrationtests/permissions_test.go
Allows editors to add members to a public board.
> fix adding members to public board by editor

- server/api/members.go
- server/integrationtests/board_test.go
- server/integrationtests/permissions_test.go
* fix adding members to public board by editor
* remove log line
* fix unit tests
* lint fix
* update test
(cherry picked from commit ee2f07c3dad4c0266561009f8eded1856402d2b0)
> CP - fix adding members to public board by editor (#3954)

- mattermost-plugin/product/boards_product.go
- mattermost-plugin/server/manifest.go
We do this to get the changes published
from the server.
https://mattermost.atlassian.net/browse/MM-47403
```release-note
NONE
```
> MM-47403: Add hooks to the product

- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
- webapp/src/properties/multiperson/multiperson.tsx
- webapp/src/properties/person/person.tsx
Cherry pick of #3961 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3961

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Update minor version to v7.4.1
> Update version to 7.4.1

- webapp/i18n/en.json
- webapp/src/components/__snapshots__/confirmAddUserForNotifications.test.tsx.snap
- webapp/src/components/confirmAddUserForNotifications.tsx
Fixed typo in modal in `en.json` and `confirmAddUserForNotifications.tsx`
Fixes https://github.com/mattermost/focalboard/issues/3940
> fixed typo in modal

- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
- webapp/src/properties/multiperson/multiperson.tsx
- webapp/src/properties/person/person.tsx
Cherry pick of #3972 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3972

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to 7.4.2

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #3998 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #3998

- webapp/src/properties/multiperson/multiperson.tsx
- webapp/src/properties/person/person.tsx
Retrieve me and check for isGuest in person and multiPerson properties. Guest are only allowed to view explicit board members
Fixes https://github.com/mattermost/focalboard/issues/3974
> Gh 3974 guest autocomplete

- server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
> Cherrypicking #4029

- webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
> Stopped reacting to initial text changes and not being a controlled component

- webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
- webapp/src/properties/types.tsx
Update the exportValue function in the abstract PropertyType class to handle the various potential return types from `this.displayValue` 
Fixes #4047
> GH-4047 Handle all potential displayValue types

- webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
- webapp/src/properties/types.tsx
Cherry pick of #4048 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4048

- webapp/src/store/users.ts
Cherry pick of #4042 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4042

- .github/workflows/ci.yml
- Makefile
- docker-testing/docker-compose-mariadb.yml
- server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
- server/services/store/sqlstore/migrationstests/fixtures/test18AddTeamsAndBoardsSQLMigrationFixtures.sql
- server/services/store/sqlstore/migrationstests/migration_18_test.go
- server/services/store/sqlstore/sqlstore.go
- server/services/store/sqlstore/util.go
Cherry pick of #3929 on release-7.4.
```release-note
NONE
```
> Automated cherry pick of #3929

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to 7.4.3

- server/services/permissions/mmpermissions/mmpermissions.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #4060 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4060

- webapp/src/components/shareBoard/shareBoard.tsx
This currently results in a crash when clicking on the Share Board button when Boards is running in product mode
https://mattermost.atlassian.net/browse/MM-47873
> MM-47873 Replace react-router import with react-router-dom

- mattermost-plugin/server/manifest.go
- webapp/src/properties/multiperson/multiperson.scss
- webapp/src/properties/person/person.scss
Remove margin and minimum width to allow cell to truncate.
Fixes https://github.com/mattermost/focalboard/issues/3830
> GH 3830 - fix person/multi-person overflow

- webapp/src/properties/baseTextEditor.tsx
Disable patches on unmount on readOnly mode
Fixes #4081
Fixes #4074
> Disable patches on unmount on readOnly mode

- webapp/src/components/sidebar/sidebar.tsx
Removes leftover console.log from #3877
> Removed leftover debug logs

- server/services/store/sqlstore/data_migrations.go
Automated cherry-pick failed for https://github.com/mattermost/focalboard/pull/4080 so this PR does it manually for release 7.4.
https://github.com/mattermost/focalboard/issues/4067
> Cherry-pick GH-4067 fix collation personal server

- webapp/src/properties/baseTextEditor.tsx
Cherry pick of #4089 on release-7.4.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #4089

- webapp/src/components/cardDetail/comment.scss
> wrap long words in comments

- webapp/src/store/cards.ts
Cherry pick of #4098 on release-7.4.
```release-note
NONE
```
> Automated cherry pick of #4098

- mattermost-plugin/server/boards/boardsapp_test.go
- mattermost-plugin/server/boards/boardsapp_util.go
- mattermost-plugin/server/boards/configuration.go
- mattermost-plugin/server/boards/configuration_test.go
- mattermost-plugin/server/manifest.go
- server/app/auth.go
- server/app/boards_test.go
- server/app/onboarding_test.go
- server/app/user.go
- server/integrationtests/pluginteststore.go
- server/services/config/config.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/user.go
- server/services/store/store.go
- server/services/store/storetests/users.go
Fix to respect full name and email configuration settings. We currently don't return email in the user json, but implemented it as well when using plugin.
Did not implement on the Personal server side as we don't set/retrieve `LastName` and `FirstName` and as stated above, we don't return the `Email` in the user json.
https://mattermost.atlassian.net/browse/MM-48009
> Fix to respect System Console settings

- mattermost-plugin/server/boards/boardsapp_test.go
- mattermost-plugin/server/boards/boardsapp_util.go
- mattermost-plugin/server/boards/configuration.go
- mattermost-plugin/server/boards/configuration_test.go
- server/app/auth.go
- server/app/boards_test.go
- server/app/onboarding_test.go
- server/app/user.go
- server/integrationtests/pluginteststore.go
- server/services/config/config.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/user.go
- server/services/store/store.go
- server/services/store/storetests/users.go
Cherry pick of #4110 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4110

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.4.4

- mattermost-plugin/server/boards/boardsapp_test.go
- mattermost-plugin/server/boards/boardsapp_util.go
- mattermost-plugin/server/boards/configuration.go
- mattermost-plugin/server/boards/configuration_test.go
- server/app/auth.go
- server/app/boards_test.go
- server/app/onboarding_test.go
- server/app/user.go
- server/integrationtests/pluginteststore.go
- server/services/config/config.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/user.go
- server/services/store/store.go
- server/services/store/storetests/users.go
Cherry pick of #4110 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Cherry pick of #4110

- webapp/src/cardFilter.test.ts
- webapp/src/cardFilter.ts
Cherry pick for https://github.com/mattermost/focalboard/pull/4152
> Updated the filter condition for notContains (#4152)

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
This fix for this PR - https://github.com/mattermost/focalboard/pull/4145 caused this issue as `SearchBoardForUserInTeam` did not return implicit memberships.
Essentially, I followed the pattern used in `SearchBoardForUser`, which is to create the function in `mattermostauthlayer.go` and update the query to include a join to the Channels table.
Fixes #4157
> Implicit memberships in SearchBoardForUserInTeam

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #4158 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4158

- webapp/src/cardFilter.test.ts
- webapp/src/cardFilter.ts
Cherry pick of #4153 on release-7.5.
```release-note
NONE
```
> Automated cherry pick of #4153

- server/app/boards.go
- server/app/boards_test.go
> Fix a bug where board didn;t show up in LHS when someone added me on it

- webapp/src/store/sidebar.ts
Cherry pick of #4163 on release-7.5.
```release-note
NONE
```
> Automated cherry pick of #4163

- server/app/boards.go
- server/app/boards_test.go
Cherry pick of #4133 on release-7.5.
```release-note
NONE
```
> Automated cherry pick of #4133

- server/app/category.go
Cherry pick of #4161 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4161

- mattermost-plugin/webapp/src/index.tsx
Honor the multi-team themes settings and applying correctly with the dark themes
Fixes #3803
> Fix themes on differen teams

- server/go.mod
- server/go.sum
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/board.go
- server/services/store/sqlstore/boards_and_blocks.go
- server/services/store/sqlstore/legacy_blocks.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/sqlstore/util.go
- server/services/store/store.go
- server/services/store/storetests/blocks.go
- server/services/store/storetests/util.go
- server/utils/callbackqueue.go
Cherry pick of #3943 on release-7.5.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #3943

- server/app/boards.go
Don't attempt to add templates to default category. 
Fixes https://github.com/mattermost/focalboard/issues/4170
> Don't add templates to default category

- mattermost-plugin/webapp/src/index.tsx
Cherry pick of #4172 on release-7.5.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #4172

- server/app/boards.go
Cherry pick of #4174 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4174

- server/app/templates.go
Updating template version to ensure templates will load properly.
Fixes https://github.com/mattermost/focalboard/issues/4170
> Update template version

- server/app/templates.go
Cherry pick of #4177 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4177

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update to version 7.6.0

- webapp/src/components/table/table.scss
- webapp/src/components/table/tableRow.scss
GH-4193 - Updating table view structure for drag
Fixes https://github.com/mattermost/focalboard/issues/4193
> GH-4193 - Updating table view structure for drag

- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/components/sidebar/sidebar.test.tsx
- webapp/src/components/sidebar/sidebar.tsx
Fixes #4175 
See here for PR explaination - https://github.com/mattermost/focalboard/pull/4200/files#diff-2584a3ca3151bd39ae5824f10680692410a3975e1f0bdfe0f257d32b5170717eR104
> Set board category if not set

- Makefile
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/data_retention.go
- server/services/store/sqlstore/sqlite.go
Cherry pick of #4213 on cloud.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #4213

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to 7.5.1

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Manually de-duplicate result set for SearchBoardsForUserInTeam since adding `distinct` to the query increased cost by 15X.
https://mattermost.atlassian.net/browse/MM-48549
> Manually de-duplicate result set for SearchBoardsForUserInTeam

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry-picks https://github.com/mattermost/focalboard/pull/4232 for cloud branch.
https://mattermost.atlassian.net/browse/MM-48549
> Cherry-pick MM-48549 for cloud

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Bump version to 7.5.2 for new dot release.
NONE
> bump version to 7.5.2 for release

- mattermost-plugin/product/api_adapter.go
- mattermost-plugin/webapp/src/index.tsx
Cherry pick of #4247 on cloud.
```release-note
NONE
```
> Automated cherry pick of #4247

- webapp/src/components/workspace.tsx
> Not opening template picker if there are no boards

- .github/workflows/prod-release.yml
Updating prod-release workflow for Multi-product architecture.
followed the changes made for [dev-release](https://github.com/mattermost/focalboard/commit/e7b5830a20cc66ad32409d349c37eadf9b4139b4)
(which builds successfully)
> Update production release workflow for MPA

- .github/workflows/prod-release.yml
> Remove extra run tag for plugin check

- .github/workflows/prod-release.yml
Cherry pick of #4260 on release-7.6.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4260

- .github/workflows/prod-release.yml
No longer can exclude server or it will download prebuilt.
> don't exclude server from build

- .github/workflows/prod-release.yml
Cherry pick of #4262 on release-7.6.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4262

- .github/workflows/prod-release.yml
Cherry pick of #4264 on release-7.6.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4264

- .github/workflows/prod-release.yml
Fix production release workflow
> Fix prod workflow

- .github/workflows/prod-release.yml
Cherry pick of #4266 on release-7.6.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4266

- server/app/insights.go
My insights is available in free tier so we need to adjust the permissions
https://mattermost.atlassian.net/browse/MM-48592
> [MM-48592] Make my insights available in free tier

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to v7.7.0

- server/app/boards_test.go
- server/app/category_boards.go
- server/app/category_boards_test.go
- server/app/category_test.go
- server/app/import_test.go
- server/app/onboarding_test.go
Cherry pick of #4284 on release-7.6.
```release-note
NONE
```
> Automated cherry pick of #4284

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
To address performance issue, two queries have been modified to use unions instead of multiple left joins.  This PR modifies the SearchBoardsForUser query.
https://github.com/mattermost/focalboard/pull/4307 modifies the SearchBoardsForUserInTeam query.
This PR also avoids the manual de-duplication of the result sets.
NONE
> Modify query in SearchBoardsForUser to use union.

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #4308 on release-7.6.
```release-note
NONE
```
> Automated cherry pick of #4308

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #4312 on release-7.6.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #4312

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #4327 on release-7.5.
```release-note
NONE
```
> Automated cherry pick of #4327

- server/services/store/sqlstore/data_migrations.go
Cherry pick of #4325 on release-7.5.
```release-note
NONE
```
> Automated cherry pick of #4325

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version 7.5.4

- mattermost-plugin/product/boards_product.go
Remove app package dependency for products.
https://mattermost.atlassian.net/browse/MM-48883
```release-note
NONE
```
> [MM-48883] reflect app <-> product package changes

- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #4335 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4335

- mattermost-plugin/server/manifest.go
- webapp/src/components/calendar/fullcalendar.scss
Fixes transparent background on popout on Weekends.
Fixes #3592
> Fix transparent background on weekends

- mattermost-plugin/product/boards_product.go
Breaking changes in mm-server force a PR in Boards to fix.  Need to go directly into rolling-stable to unblock CI.
NONE
> reflect app <-> product package changes (#4320)

- mattermost-plugin/product/boards_product.go
Cherry-pick the boards fix for breaking mm-server change.  Cherry-picks https://github.com/mattermost/focalboard/pull/4320
NONE
> Cherry-pick 4320: reflect app <-> product package changes (#4320)

- README.md
> Added API docs in readme

- server/services/store/sqlstore/migrations/000026_create_preferences_table.up.sql
This PR fixes the default collation for the preferences table migration.
> Fix default collation on preferences table

- webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
- webapp/src/components/table/__snapshots__/table.test.tsx.snap
- webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
- webapp/src/components/table/calculation/calculationRow.scss
- webapp/src/components/table/table.scss
- webapp/src/components/table/tableRow.scss
- webapp/src/components/table/tableRow.tsx
> Calculation row padding fix

- mattermost-plugin/server/manifest.go
- webapp/src/styles/main.scss
> Fixed flex-wrap to display all emojis

- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/cardDetail/__snapshots__/cardDetail.test.tsx.snap
- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/components/cardDetail/cardDetail.tsx
- webapp/src/components/dialog.scss
GH-4332 - Updating card editor classes
Fixes #4332
> GH-4332 - Updating card editor classes

- mattermost-plugin/server/manifest.go
- webapp/src/styles/main.scss
Cherry pick of #4355 on release-7.7.
```release-note
NONE
```
> Automated cherry pick of #4355

- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/cardDetail/__snapshots__/cardDetail.test.tsx.snap
- webapp/src/components/cardDetail/cardDetail.scss
- webapp/src/components/cardDetail/cardDetail.tsx
- webapp/src/components/dialog.scss
Cherry pick of #4350 on release-7.7.
```release-note
NONE
```
> Automated cherry pick of #4350

- webapp/src/components/content/attachmentElement.scss
This PR fixes the delete menu hover issue and moves of delete menu around after hover changes in file attachment for boards.
Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/4241
> Fixed delete menu hover issue

- webapp/src/components/content/attachmentElement.scss
Cherry pick of #4297 on release-7.7.
```release-note
NONE
```
> Automated cherry pick of #4297

- webapp/src/components/content/attachmentElement.tsx
Cherry pick of #4296 on release-7.7.
```release-note
NONE
```
> Automated cherry pick of #4296

- mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
- mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
- mattermost-plugin/webapp/src/components/boardSelectorItem.scss
- mattermost-plugin/webapp/src/components/boardSelectorItem.tsx
- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
GH-4298 - Updating link boards modal item
Fixes #4298
> GH-4298 - Updating link boards modal item

- mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
- mattermost-plugin/webapp/src/components/__snapshots__/boardSelectorItem.test.tsx.snap
- mattermost-plugin/webapp/src/components/boardSelectorItem.scss
- mattermost-plugin/webapp/src/components/boardSelectorItem.tsx
Cherry pick of #4362 on release-7.7.
```release-note
NONE
```
> Automated cherry pick of #4362

- website/site/layouts/partials/head.html
Updated the lucky orange code as Daniel Sischy asked me to update it.
> Updating luckyorange tracking code

- mattermost-plugin/server/boards/boardsapp.go
- server/app/blocks.go
- server/app/blocks_test.go
- server/app/cloud.go
- server/app/cloud_test.go
Cherry pick of #4268 on release-7.7.
```release-note
NONE
```
> Automated cherry pick of #4268

- mattermost-plugin/webapp/src/components/boardSelectorItem.scss
GH-4385 - Updating padding for boardselectoritem
Fixes #4385
> GH-4385 - Updating padding for boardselectoritem

- mattermost-plugin/webapp/src/components/boardSelectorItem.scss
Cherry pick of #4387 on release-7.7.
```release-note
NONE
```
> Automated cherry pick of #4387

- webapp/src/csvExporter.ts
This PR fixes the export value for `createdBy` property for cards.
Fixes https://github.com/mattermost/focalboard/issues/4134
> Fixed the CSV export for created by property

- server/app/boards.go
Cherry pick of #4353 on release-7.7.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4353

- mattermost-plugin/product/boards_product.go
- mattermost-plugin/server/boards/boards_service_api.go
- mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
- mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoards.test.tsx.snap
- server/api/search.go
- server/app/app.go
- server/app/boards.go
- server/app/permissions.go
- server/client/client.go
- server/integrationtests/pluginteststore.go
- server/model/board.go
- server/model/error.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mockstore/mockstore.go
- server/services/store/sqlstore/board.go
- server/services/store/sqlstore/public_methods.go
- server/services/store/store.go
- server/services/store/storetests/boards.go
Cherry-pick https://github.com/mattermost/focalboard/pull/4404 and https://github.com/mattermost/focalboard/pull/4291 into release7.7
NONE
> Cherry-pick 4404: expose boards APIs

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to v7.8.0

- mattermost-plugin/webapp/webpack.config.js
Cherry pick of #4463 on release-7.7.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #4463

- mattermost-plugin/webapp/src/components/__snapshots__/boardSelector.test.tsx.snap
- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/__snapshots__/confirmAddUserForNotifications.test.tsx.snap
- webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
- webapp/src/components/__snapshots__/dialog.test.tsx.snap
- webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
- webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
- webapp/src/components/cardDialog.scss
- webapp/src/components/confirmationDialogBox.scss
- webapp/src/components/confirmationDialogBox.tsx
- webapp/src/components/createCategory/__snapshots__/createCategory.test.tsx.snap
- webapp/src/components/createCategory/createCategory.scss
- webapp/src/components/createCategory/createCategory.tsx
- webapp/src/components/dialog.scss
- webapp/src/components/dialog.tsx
- webapp/src/components/gallery/__snapshots__/galleryCard.test.tsx.snap
- webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialog.test.tsx.snap
- webapp/src/components/viewLImitDialog/__snapshots__/viewLimitDialogWrapper.test.tsx.snap
Adjusting modals and updating close icon on input
Fixes #4434 
Fixes #4457
> Adjusting modals and updating close icon on input

- server/app/export.go
- server/app/import.go
- server/app/import_test.go
This PR will solve the issue of retaining the membership of the user when imported from the board archive 
Fixes https://github.com/mattermost/focalboard/issues/4275
> Export Import Memberships is retained

- webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx
- webapp/src/components/sidebar/sidebarSettingsMenu.tsx
Menu was closing on toggling random icons
Fixes https://github.com/mattermost/focalboard/issues/4300
> [GH-4300]: Fix menu closing on toggling random icons.

- webapp/src/cardFilter.test.ts
- webapp/src/cardFilter.ts
Fix for if the filter.Value is not set, don't filter.
Fixes #4482
> Gh 4482 fix empty filters

- mattermost-plugin/product/api_adapter.go
- mattermost-plugin/server/api_adapter.go
- mattermost-plugin/server/manifest.go
- server/model/mocks/mockservicesapi.go
- server/model/services_api.go
- server/services/notify/plugindelivery/plugin_delivery.go
- server/services/notify/plugindelivery/subscription_deliver.go
- server/services/notify/plugindelivery/user_test.go
Cherry pick of #4496 on cloud.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #4496

- server/api/categories.go
- server/integrationtests/permissions_test.go
Checking that you have permissions to view a team to be able to manipulate categories in that team.
[MM-43342](https://mattermost.atlassian.net/browse/MM-43342)
> MM-43342: More strict permissions on categories

- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/cardDialog.tsx
This PR fixes the issue of file attachments in the personal server
Fixes https://github.com/mattermost/focalboard/issues/4497
> File attachment in personal server

- webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
- webapp/src/components/cardDialog.tsx
Cherry pick of #4506 on release-7.8.
```release-note
NONE
```
> Automated cherry pick of #4506

- server/app/import.go
- server/app/import_test.go
(cherry picked from commit 79686c7b32cd0ab361d0dc264bca1a258977c80f)
> add admin user on import

- webapp/src/widgets/menu/menu.scss
Cherry pick of #4411 on release-7.8.
/cc  @kostaspt
```release-note
NONE
```
> Automated cherry pick of #4411

- server/integrationtests/work_template_test.go
I didn't really want to do this PR but this is how it is 😬 Because this is kind of a "first", I opened a thread here: https://community.mattermost.com/core/pl/t7d16sx83tnw7phhh8bp9h844a
Work templates rely on the fact that certain boards templates exist, but we have no way to guarantee this on the mattermost-server/webapp side. This test acts as a warning that something might break in work templates because a templates is not reachable.
N/A
> Add a test to help detect potential sync issues with work template

- webapp/src/components/markdownEditorInput/entryComponent/entryComponent.tsx
(cherry picked from commit 8544a25746fbf104c1580e78d79582e7a02dd2e4)
> check isbot property before displaying botbadge

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to v7.8.1

- server/api/files.go
Cherry pick of #4542 on release-7.8.
```release-note
NONE
```
> Automated cherry pick of #4542

- server/app/blocks.go
- server/app/boards.go
- webapp/cypress/integration/cardURLProperty.ts
- webapp/src/components/cardDetail/attachment.scss
- webapp/src/mutator.ts
- webapp/src/pages/boardPage/boardPage.tsx
- webapp/src/store/attachments.ts
Cherry pick of #4444 on release-7.8.
```release-note
NONE
```
> Automated cherry pick of #4444

- webapp/src/widgets/menu/menu.scss
Cherry pick of #4570 on release-7.8.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4570

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to v7.8.2

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version 7.7.1

- webapp/src/properties/url/url.tsx
Disable patches on unmount on readOnly mode
Fixes https://mattermost.atlassian.net/browse/MM-50951
> Disable patches on read-only unmount for url property

- webapp/src/properties/url/url.tsx
(cherry picked from commit 805e0d93dc30c5decbb5419ad766e3982affaaec)
> disable patches on read-only unmount (#4608)

- webapp/src/pages/welcome/__snapshots__/welcomePage.test.tsx.snap
- webapp/src/pages/welcome/welcomePage.scss
- webapp/src/pages/welcome/welcomePage.tsx
Updating welcome screen for small sizes
The button gets hidden on smaller height screens, so proposing we move the button above the above on those instances.
> Updating welcome screen for small sizes

- webapp/src/components/table/table.scss
Clear overflow on Multiperson property as well.
Fixes https://github.com/mattermost/focalboard/issues/3903
> Fix table multiperson

- webapp/src/properties/date/__snapshots__/date.test.tsx.snap
- webapp/src/properties/date/date.test.tsx
- webapp/src/properties/date/date.tsx
Date property on a card was not updating when you changed it's value elsewhere
https://github.com/mattermost/focalboard/issues/4474
> Updating date when prop has changed

- webapp/src/properties/date/__snapshots__/date.test.tsx.snap
- webapp/src/properties/date/date.test.tsx
- webapp/src/properties/date/date.tsx
> Date properties test server

- mattermost-plugin/webapp/src/components/rhsChannelBoardItem.tsx
- webapp/src/telemetry/telemetryClient.ts
Add telemetry information everytime a board card is clicked from the channels RHS boards list.
https://mattermost.atlassian.net/browse/MM-48246
> MM-48246 - ab test open RHS with linked board; add telemetry info

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Update `Main` version to v7.10.0
> update version to v7.10.0

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.9.2

- webapp/src/widgets/emojiPicker.tsx
Fixes the path to static file for emoji picker.
Fixes https://github.com/mattermost/focalboard/issues/4633
> fix path for static files

- server/services/store/sqlstore/schema_table_migration.go
- server/services/store/sqlstore/util.go
Adds schema name to boards schema_migration upgrade process.
Fixes https://mattermost.atlassian.net/browse/MM-51303
> Add  schema check for schema migration

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.8.3

- server/services/store/sqlstore/migrate.go
This PR adds escaping to the MySQL tables when using database helpers to allow admins to use schema names that start with a digit or in general require to be escaped.
Fixes https://github.com/mattermost/focalboard/issues/4631
> Adds escaping when normalizing table names for MySQL on DB helpers

- server/services/store/sqlstore/migrate.go
Cherry pick of https://github.com/mattermost/focalboard/pull/4653 for 7.8
> Adds escaping when normalizing table names for MySQL on DB helpers (#4653)

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version 7.8.4

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.9.3

- server/api/files.go
* copy safe writeFileResponse into personal server/desktop
* lint fix
---------
Co-authored-by: Mattermost Build <build@mattermost.com>
(cherry picked from commit d8e1fb4832953fb31c54d4bc3542e2e4d4fe0fb7)
> copy safe writeFileResponse into personal server/desktop (#4654)

- server/services/store/sqlstore/data_migrations.go
- server/services/store/sqlstore/migrationstests/boards_migrator_test.go
- server/services/store/sqlstore/migrationstests/de_duplicate_category_boards_migration_test.go
- server/services/store/sqlstore/migrationstests/fixtures/test33_with_deleted_data.sql
- server/services/store/sqlstore/migrationstests/fixtures/test33_with_no_deleted_data.sql
- server/services/store/sqlstore/migrationstests/fixtures/test37_valid_data.sql
- server/services/store/sqlstore/migrationstests/fixtures/test37_valid_data_no_hidden_boards.sql
- server/services/store/sqlstore/migrationstests/fixtures/test37_valid_data_preference_but_no_hidden_board.sql
- server/services/store/sqlstore/migrationstests/fixtures/test37_valid_data_sqlite.sql
- server/services/store/sqlstore/migrationstests/fixtures/test37_valid_data_sqlite_preference_but_no_hidden_board.sql
- server/services/store/sqlstore/migrationstests/fixtures/testDeDuplicateCategoryBoardsMigration.sql
Cherrypicking https://github.com/mattermost/mattermost-server/pull/22606 from mono-repo for backport
> Cherrypicking 22606 to old focalboard

- webapp/src/widgets/emojiPicker.tsx
Fixes for "mono-repo" got merged back to focalboard repo, need to buildURL in focalboard repo.
Fixes https://mattermost.atlassian.net/browse/MM-51837
> need url for emoji picker

- README.md
Added details around sunsetting Personal Editions as well as changes to the plugin.
> Update README.md for Focalboard

- webapp/src/properties/number/__snapshots__/number.test.tsx.snap
- webapp/src/properties/number/number.test.tsx
- webapp/src/properties/number/number.tsx
Cherry-pick of #4694 to `release-7.10`
```release-note
Fixed issue while creating/editing cards with multiple number fields
```
> Cherry Pick #4694 Backport: MM-51842: fix value-change detection in number properties

- server/services/store/sqlstore/schema_table_migration.go
Cherry pick of https://github.com/mattermost/focalboard/pull/4717 for release-7.10
> Fix table_schema check for postgres

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.9.4

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.8.5

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.1.1

- mattermost-plugin/webapp/src/components/boardsUnfurl/__snapshots__/boardsUnfurl.test.tsx.snap
- mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.test.tsx
- mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.tsx
Essentially cp of https://github.com/mattermost/mattermost-server/pull/22697
Fixes issue where bad board link can cause issue with displaying channels.
Fixes https://mattermost.atlassian.net/browse/MM-51713
```release-note
Fixes issue with bad board link 
```
> fix issue with card id being valid block but not a card

- mattermost-plugin/webapp/src/components/boardsUnfurl/__snapshots__/boardsUnfurl.test.tsx.snap
- mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.test.tsx
- mattermost-plugin/webapp/src/components/boardsUnfurl/boardsUnfurl.tsx
(cherry picked from commit 0af70a0a4f2ae1c11633d4431f4db70db1640337)
> fix issue with card id being valid block but not a card (#4729)

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update to version v7.11.0

- .github/workflows/ci.yml
- .github/workflows/dev-release.yml
- .github/workflows/lint-server.yml
- .github/workflows/prod-release.yml
- server/app/boards_test.go
- server/app/helper_test.go
- server/model/permission.go
Fixing failing compilation of boards in 7.8.
> Fixing failed CP

- mattermost-plugin/server/manifest.go
- server/app/blocks.go
- server/services/store/sqlstore/blocks.go
* Fix cards not deleting properly.
* Review feedback
* Test and lint fixes.
* Fix tests.
(cherry picked from commit c3b1c82b1a6727c6eb69c611c6316cc555bc0f9a)
> Fix cards not deleting properly. (#4746)

- webapp/src/widgets/emojiPicker.tsx
Fix emoji picker for release-7.8
> fix emoji for release-7.8

- .github/workflows/ci.yml
- .github/workflows/dev-release.yml
- .github/workflows/lint-server.yml
- .github/workflows/prod-release.yml
- build/gowork/main.go
- mattermost-plugin/Makefile
- Fixed server CI after renaming the project
MM-52996
> [MM-52996] fix server ci after renaming the project

- webapp/src/components/shareBoard/teamPermissionsRow.tsx
Cherry pick of https://github.com/mattermost/mattermost/pull/22773
https://mattermost.atlassian.net/browse/MM-51822
> Fix boards share dialog

- webapp/src/components/shareBoard/teamPermissionsRow.tsx
Cherry pick of #4761 on release-7.8.
/cc  @crspeller
```release-note
NONE
```
> Automated cherry pick of #4761

- .github/workflows/scorecards-analysis.yml
Updates scorecard action version to fix CI in `main`
> Upgrade Scorecards action version

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to v7.9.5

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to v7.10.2

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version to v7.8.6

- .github/workflows/scorecards-analysis.yml
Cherry pick of #4760 on release-7.11.
```release-note
NONE
```
> Automated cherry pick of #4760

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dev-release.yml
- .github/workflows/lint-server.yml
- .github/workflows/prod-release.yml
- .github/workflows/scorecards-analysis.yml
Cherry pick of #4771 on release-7.10.
```release-note
NONE
```
> Automated cherry pick of #4771

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update version 7.10.3

- server/auth/auth.go
- server/integrationtests/permissions_test.go
Cherry pick of #4739 on release-7.10.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4739

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.9.6

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.10.4

- server/app/files.go
Older attachment files are not displayed correctly.
https://mattermost.atlassian.net/browse/MM-53240
> MM-53240-older attachment files don't work.

- server/app/files.go
Cherry pick of #4785 on release-7.11.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4785

- server/app/files.go
Cherry-pick of https://github.com/mattermost/focalboard/pull/4785 for `release-7.10`
https://mattermost.atlassian.net/browse/MM-53240
> cherry-pick: check 'path' for 'empty' as well (#4785)

- server/app/import.go
Cherry pick of #4788 on release-7.11.
```release-note
NONE
```
> Automated cherry pick of #4788

- server/api/api_test.go
- server/model/block.go
- server/model/error.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/legacy_blocks.go
- server/services/store/storetests/blocks.go
- server/services/store/storetests/boards_and_blocks.go
This PR unifies all block validations in an `IsValid` receiver method and adds enhances the logic. 
https://mattermost.atlassian.net/browse/MM-53234
> Unify and enhance block validation

- server/api/api_test.go
- server/model/block.go
- server/model/error.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/legacy_blocks.go
- server/services/store/storetests/blocks.go
- server/services/store/storetests/boards_and_blocks.go
Cherry pick of #4790 on release-7.11.
```release-note
NONE
```
> Automated cherry pick of #4790

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Cherry pick of #4797 on release-7.11.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #4797

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version 7.10.5

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version 7.11.2

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version 7.9.7

- server/services/store/sqlstore/blocks.go
Cherry pick of #4802 on release-7.8.
```release-note
NONE
```
> Automated cherry pick of #4802

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Updating main version to v7.12.0.
> update version v7.12.0

- server/api/api_test.go
- server/app/import.go
- server/model/block.go
- server/model/error.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/legacy_blocks.go
- server/services/store/storetests/blocks.go
- server/services/store/storetests/boards_and_blocks.go
Cherry pick for https://github.com/mattermost/focalboard/pull/4790 and https://github.com/mattermost/focalboard/pull/4788 for `release-7.10`
> Cherry pick enhance validation 7.10

- server/api/api_test.go
- server/app/import.go
- server/model/block.go
- server/model/error.go
- server/services/store/sqlstore/blocks.go
- server/services/store/sqlstore/legacy_blocks.go
- server/services/store/sqlstore/migrationstests/migration40_test.go
- server/services/store/storetests/blocks.go
- server/services/store/storetests/boards_and_blocks.go
Cherry pick for https://github.com/mattermost/focalboard/pull/4790 and https://github.com/mattermost/focalboard/pull/4788 for `release-7.8`
> Cherry pick enhance validation 7.8

- server/api/users.go
- server/app/user.go
- server/model/user.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
- server/services/store/mattermostauthlayer/mattermostauthlayer_test.go
Cherry pick of #4820 on release-7.11.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #4820

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.11.3

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.8.9

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> update version to v7.10.6

- mattermost-plugin/plugin.json
- mattermost-plugin/server/manifest.go
- server/model/version.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
> Update to version 7.11.4

- server/api/users.go
- server/client/client.go
- server/integrationtests/pluginteststore.go
- server/integrationtests/user_test.go
- server/services/store/mattermostauthlayer/mattermostauthlayer.go
Cherry pick of #4884 on release-7.10.
/cc  @mattermost-build
```release-note
NONE
```
> Automated cherry pick of #4884

- CONTRIBUTING.md
- README.md
- docs/README.md
🆕 docs: Add new README.md in docs folder with updated disclaimer
The README.md file has been updated to reflect the current status of the project. The project is no longer maintained by Mattermost and has transitioned to being fully community supported. The contribution guidelines have been updated to encourage the community to fork this repository for continued development and contributions. A new README.md file has been added in the docs folder to provide the updated disclaimer in a more prominent location. This change is necessary to keep the community informed about the project's status and how they can contribute moving forward.
> 📝 docs(README.md): Update project status and contribution guidelines

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dev-release.yml
- .github/workflows/lint-server.yml
- .github/workflows/prod-release.yml
- .github/workflows/scorecards-analysis.yml
Fix pipelines, update actions add dependabot
> Fix pipelines, update actions add dependabot
