mattermost-community/focalboard

import/asana/importAsana.ts
import/asana/package.json
import/notion/importNotion.ts
import/notion/package.json
import/trello/importTrello.ts
import/trello/package.json
webapp/src/archiver.ts
webapp/src/blocks/archive.test.ts
webapp/src/blocks/archive.ts
webapp/src/lineReader.ts
webapp/src/octoClient.ts
webapp/src/octoListener.ts

Changed the .focalboard archive format to JSONL (https://jsonlines.org/)
* The first line is a header, followed by lines for each block, interfaces defined in Archive.ts
* Implemented streaming line-by-line parser for import, but also checked in non-streaming one

Archive in JSONL format

---

website/site/content/download/personal-edition/ubuntu.md

`ln` command in server setup was failed. It should be `ln -s ${source_file} ${target_file}`.
```bash
$ sudo ln -s /etc/nginx/sites-enabled/focalboard /etc/nginx/sites-available/focalboard
ln: failed to create symbolic link '/etc/nginx/sites-available/focalboard': File exists
```
N/A

Fix setup command

---

Dockerfile

Add a Dockerfile to launch the application within a container.
*NOTE:* At the moment, the focalboard version is hard-coded and there is
a bug that means the download is not actually a .tar.gz file, but a
.tgz.gz file inside a .zip file.
This also assumes the use of SQLite as the database rather than PgSQL.
Fixes https://github.com/mattermost/mattermost-server/issues/75

Add Dockerfile to run service in a container

---

website/site/content/download/personal-edition/ubuntu.md

The documentation doesn't show to change the dbtype to postgres, which when is kept as sqlite will result in failure. This fixes that.

updated the document to include `dbtype` in dbconfig

---

webapp/src/components/propertyValueElement.tsx
webapp/src/widgets/propertyMenu.tsx

This PR adds the option to choose email as a field type.
#40 
Most of the components are not covered by unit tests, including the ones I changed. So I was not sure what strategy the creators have in mind for unit testing components. Please advise. I would be happy to add unit tests.
Thank you!

[GH-40] Add property type email

---

Dockerfile

Remove the need for `unzip` and switch to using the Github Releases file as per #77 
#77

Remove unnecessary binaries, update to use github releases

---

webapp/__mocks__/styleMock.js
webapp/package.json
webapp/src/widgets/propertyMenu.test.tsx

Yesterday, I submitted a PR (https://github.com/mattermost/focalboard/pull/84) for adding email as an option for the property type. But I didn't write any unit tests as part of it, and @jespino agreed it is okay to submit the unit tests as a separate PR. This PR contains a basic unit test for the `propertyMenu.tsx`  file I changed as part of yesterday's PR.
I had to change the Jest config to provide a mock in place of `sass` files imported by components.
Once this PR is in, I would be happy to add more unit tests.

Add basic setup for unit testing components with sass files import

---

CONTRIBUTING.md

Have contributors update changelog, e.g. https://github.com/mattermost/focalboard/pull/138

Adding Changelog update instructions

---

CHANGELOG.md

Also linking to contributor PRs. Also adding release dates, rather than release months. We might release more than once a month given our velocity right now.

Adding DockerHub, PR#s, release date to changelog

---

.github/ISSUE_TEMPLATE/enhancement.md

We had this problem in Mattermost where when we used the term "Feature Requests" it sounded a bit like "Pull Requests" and there was an expectation sometimes, in our own team and in the community, that it was some sort of formal ticket that had to be addressed. 
We later changed to "Feature Idea" and then the expectations changed, where the maintainers didn't necessarily need to address every new ticket, since it was more sharing an idea, versus putting in a request. 
Right now the volume of feature ideas is a little overwhelming and my sense is we should make this change to lower the perceived pressure a bit. 
If we make this change, we can go update the previous tickets to match, and link to this ticket to explain why.

Switch from "Feature Request" to "Feature Idea"

---

server/api/api.go
server/app/files.go
server/swagger/docs/html/index.html
server/swagger/swagger.yml
webapp/src/components/addContentMenuItem.tsx
webapp/src/components/cardDetail/cardDetailContentsMenu.tsx
webapp/src/components/content/contentRegistry.tsx
webapp/src/components/content/imageElement.tsx
webapp/src/mutator.ts
webapp/src/octoClient.ts

Changed files API to store and retrieve files per workspace and rootID. This is to allow permissions later. A user has access to a file if and only if one of the following is true:
1. Logged in with a valid session (and has access to the workspace, if workspaces are enabled)
2. Pass a valid read_token in the querystring, that is valid for the specified root block (sharing read-only)
This is a breaking change on the previous file storage location.

Store files per workspace and root block

---

linux/main.go

This PR changes the search path of the server binary in the linux app  to be not `./` (the working directory) but the same path as the apps executable. 
This is part of an effort to better separate program and configuration.

linux: find server executable relative to app

---

server/services/config/config.go

The current setup expects `focalboard-app`, `focalboard-server`, `config.json` and the `pack` directory to reside in the same location. 
This PR allows for at least the configuration to be overridden via the execution environment which makes it easier to use the app in a environment where the programs assets and executables reside in a global, not user writeable location as is the case with nix(os) and many other scenarios. 
ideally the app would take a `--config-file` parameter but this is not straight forward with the viper framework and therefore I present this as the smallest and least invasive change to solve the problem.

server: additionally read config settings from env

---

import/trello/README.md

This is a documentation-only change.
Without this, the steps indicated in the Trello import readme currently result in errors, as described on the ticket below.
Fixes #255 .

[GH-255] Add crucial step to Trello import readme

---

webapp/src/components/gallery/galleryCard.tsx

This prevents cards on gallery boards from being draggable when the board is read-only.
Comparing with [KanbanCard](https://github.com/mattermost/focalboard/blob/main/webapp/src/components/kanban/kanbanCard.tsx#L44), I noticed that the `draggable` property is also set explicitly there. In my testing for gallery cards this did not seem necessary though.
Fixes #278
PS: When signing the CLA, the form said you'll send me something as a thank you if my contribution is accepted. Please don't mail me anything to Germany for a one-line fix. I would feel embarrassed. 😅

[GH-278] Prevent dragging of gallery cards in read-only mode

---

webapp/src/components/contentBlock.tsx

This wraps the `.dnd-handle` drag grip with `!props.readonly &&` so that it doesn't show when viewing card details in read-only mode.
Since all children of the parent `.octo-block-margin` div are excluded in read-only mode now, we could also move the read-only check here. Other than preventing the empty div, that didn't seem to provide any significant advantage though so I left it like this. Happy to change this if you disagree though. 🙂
Fixes #277

[GH-277] Hide drag grip on content blocks in read-only mode

---

mac/Focalboard/Info.plist

Let macOS handle quarantine on downloaded files.
I know focalboard still doesn't have files other than images (although non images can be uploaded and they wont display properly). but at some point it will and having the OS handle quarantine files will probably ease security.
No ticket per se, but I recently [did that on the desktop app](https://mattermost.atlassian.net/browse/MM-20677) and thought it would be nice to have it here as well. 
I don't think it can be tested right now, but once you can download a file from Focalboard you can create a sample file out of the terminal app by going to the menu->shell->export settings (export as a `.terminal` file)

Add macOS quarantine

---

webapp/src/widgets/editable.scss

316 - Updating editable default height
https://github.com/mattermost/focalboard/issues/316

316 - Updating editable default height

---

webapp/i18n/en.json
webapp/src/components/centerPanel.tsx
webapp/src/components/sidebar/sidebarSettingsMenu.tsx
webapp/src/userSettings.ts

This does the minimum work for #190 by adding a global settings option to disable random icons on newly created cards.
Partially fixes #190

[GH-190] Add global option to disable randomized card icons

---

webapp/src/blocks/boardView.test.ts
webapp/src/blocks/boardView.ts
webapp/src/components/sidebar/sidebarBoardItem.tsx

This is a stopgap towards #299 that sorts views in the sidebar alphabetically but only after stripping any leading emoji. This prevents unintuitive results such as putting "📥 Inbox" before "🚀 Active".
*Before*
*After*
Still not sure if maybe this is too specialized a use case to warrant including this logic so happy to hear thoughts. 🙂 
Relates to #299

[GH-299] Sort views alphabetically after stripping leading emoji

---

webapp/src/components/table/table.scss

Updates css, to prevent column headers from overflowing into the next cell.
Also fixes sizing in text properties where they didn't take up entire cell.
Fixes https://github.com/mattermost/focalboard/issues/351
Fixes https://github.com/mattermost/focalboard/issues/352

[GH-351] Truncate Column Headers in Table View if necessary

---

webapp/src/components/propertyValueElement.tsx
webapp/src/components/viewHeader/viewHeaderActionsMenu.tsx
webapp/src/csvExporter.ts
webapp/src/octoUtils.tsx
webapp/src/utils.ts

Currently dates are displayed in English regardless of the language used by the user.
This PR allows to use the React translation tool already used in focalboard to display the date in the user's language

Translate date and datetime with React Translator

---

webapp/src/components/sidebar/sidebarBoardItem.scss
webapp/src/components/sidebar/sidebarBoardItem.tsx

This moves the click handler from sidebar item titles to the sidebar items themselves. This way, the clickable area matches with the visually highlighted area on hover.
Fixes #307

[GH-307] Increase clickable area on sidebar items

---

webapp/src/components/table/tableRow.scss

Updated the "Open" button size to better fill the row
The open button currently does not fill the row completely and makes it a bit odd when trying to click on it
Which has been updated to,
None I think

Update "Open" button size

---

webapp/src/components/cardDetail/cardDetail.tsx
webapp/src/components/content/__snapshots__/checkboxElement.test.tsx.snap
webapp/src/components/content/checkboxElement.tsx
webapp/src/components/kanban/kanbanColumnHeader.tsx
webapp/src/components/markdownEditor.tsx
webapp/src/components/propertyValueElement.tsx
webapp/src/components/table/tableRow.tsx
webapp/src/components/viewHeader/viewHeader.tsx
webapp/src/components/viewTitle.tsx
webapp/src/widgets/__snapshots__/propertyMenu.test.tsx.snap
webapp/src/widgets/editable.tsx
webapp/src/widgets/propertyMenu.tsx

This PR enables built-in browser spell checking by:
- Adding `spellcheck="true"` to all relevant `<input>` elements
- Enabling the native spell checking mode in easy-markdown-editor
Tested on macOS with German set as the primary and US English as the secondary language. Safari and Chrome correctly spell check both languages:
Firefox, unfortunately, continued using English only for spell checking even after changing the language in the browser settings. 😞 
Safari, sadly, refuses to do spell checking in the markdown editor:
Chrome and Firefox do though:
Relates to #315

[GH-315] Enable spell checking in inputs and markdown editor

---

webapp/src/userSettings.ts

This adds `randomIcons` to the exported user settings. Apologies for missing this earlier. 🤦 
Fixes #375

[GH-375] Persist `randomIcons` setting in native mac app

---

webapp/src/components/markdownEditor.tsx

This removes a redundant manual blur of the input field. In the macOS app this caused the blur handler to be retriggered which resulted in the description being duplicated.
Fixes #309

[GH-309] Prevent description duplication on Safari / macOS app

---

webapp/src/components/sidebar/sidebar.tsx
webapp/src/components/sidebar/sidebarUserMenu.scss
webapp/src/components/sidebar/sidebarUserMenu.tsx

This adds a "BETA" label underneath the version number if workspaces are used. It's pretty simple, but some considerations for the future:
* Current logic is based on using workspaces. Ultimately, we should add a load-time property, e.g. "isMattermost".
* "Load time" because there's currently a short delay showing the badge (before the workspace info is retrieved)
* Reason for this logic is we don't want to show the Beta badge in the app versions

Add Beta badge

---

import/asana/package-lock.json
import/asana/package.json
import/notion/package-lock.json
import/notion/package.json
import/todoist/package-lock.json
import/trello/package-lock.json
import/trello/package.json
webapp/package-lock.json
webapp/src/utils.ts

Ran npm audit fix in response to dependbot alert.
Also fixed an issue running the import scripts:
* They are nodejs apps that depend on code in webapp
* Was failing due to Utils.ts calling a document method at load time
* Moved the canvas init into the call to work around

npm audit fix and fix import scripts

---

config.json
docker/config.json
server-config.json
server/go.mod
server/go.sum
server/server/server.go
server/services/config/config.go
server/services/prometheus/intrumentor.go
server/services/prometheus/prometheus.go
website/site/content/guide/admin/_index.md

As an SRE team we would like to expose standard metrics and grouped by version
of the application. Right now will expose only metrics related to Go but instrumentor
should be used in other parts of the codebase so we can track other metrics, eg.
number of tasks, boards, users etc. Similar as we do in MM.
It will run in port `localhost:9092` and it is a new config `prometheus_address`.
Also in the commit we introduced, `group.Add` which helps us to handle gracefully
errors for goroutines. It's a good practice and there are couple of articles by
Golang for this.
Open source Friday :)

Enable prometheus metrics for Focalboard to enable observability

---

webapp/package-lock.json
webapp/package.json

As part of the `EditableDayPicker` component we're requiring `moment`, which was available as a transitive dependency of `cypress`. This PR makes the dependency explicit and enables building the release pipeline with `npm install --no-optional`, which was failing.

Add moment as a direct dependency

---

webapp/src/components/content/__snapshots__/checkboxElement.test.tsx.snap
webapp/src/widgets/editable.scss
webapp/src/widgets/editable.tsx

This is an attempt to fix #410 by making the background of text input fields transparent when the field is read-only. Making it transparent will make the parent's background show through which works in conjunction with table cells which change background on hover.
Alternatively, we could also set a static color but I found this solution to work nicely irrespective of the parent's background.
Fixes #410

[GH-410] Remove background from read-only input fields

---

.github/workflows/build-mac.yml
.github/workflows/build-ubuntu.yml
.github/workflows/build-win-wpf.yml
.github/workflows/ci.yml
.github/workflows/prod-release.yml
.gitlab-ci.yml
Dockerfile.build
Makefile
README.md
server/go.mod
server/go.tools.mod

- This PR adds the GitLab CI to build Focalboard internally, the internal pipeline is setup here: https://git.internal.mattermost.com/mattermost/ci/focalboard/-/merge_requests/1 and for now it builds for the main branch for Linux and Mac.
Added a dockerfile to build the Linux inside a container to not have many outside dependencies, all we need to build focalboard for Linux is in the dockerfile and the pipeline uses that to build.
trying to see if we can do the same for windows and mac, but since it depends on some C it is a bit hard to crosscompile it :/
- Also bumps Go to 1.16
Missing to do
- add windows build
- add pipeline for release branch
- add pipeline for the official release (when there is a tag)
but adding this now to we can validate the build
focalboard mirror is already in …

Add GitLab ci to build internally and bump go to 1.16

---

webapp/package-lock.json
webapp/package.json

Fixed Docker build failure due to some missing optional dependencies.
Certain dependencies of `webpack-image-loader` are marked as optional dependencies, which we don't install during Docker build.
I've specified those as Focalboard's direct dependencies.

Fixed Docker build breaking due to webpack-image=loader

---

linux/go.sum
linux/main.go
mattermost-plugin/build/go.sum
mattermost-plugin/go.sum
mattermost-plugin/server/plugin.go
server/go.mod
server/go.sum

Windows build was failing due to Logr syslog dependency since syslog is not supported on Windows. This PR fixes the issue by bumping the Logr version to the one that includes a fix.
https://github.com/mattermost/focalboard/issues/519

Bump Logr version to fix Windows build

---

mac/Focalboard/AppDelegate.swift

This change intercepts reopen events and creates a new window in case no windows exist.
Fixes https://github.com/mattermost/focalboard/issues/443

[GH-443] Create new window when reopening without existing windows

---

webapp/src/pages/boardPage.tsx

This PR contains a fix for the Tab header which displays "OCTO"  before fix and now it displays  Focalboard
Fixes https://github.com/mattermost/focalboard/issues/480

Fixed Tab header displays 

---

server/services/store/sqlstore/migrate.go
server/services/store/sqlstore/migrate_test.go

This PR fixes a server panic that would happen in case the server is trying to connect to a MySQL database with no query parameters, when trying to append the `multiStatements` parameter.
Based on the [server fix applied for this same bug](https://github.com/mattermost/mattermost-server/pull/17723).

Fix MySQL migration connection when the DSN doesn't contain any query parameters

---

mattermost-plugin/Makefile

This PR disables `cgo` when compiling the plugin to avoid it depending on the `libc` present on the server's system.
https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde/shared?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-88cc744576c8&r=762db9c6-305c-4d13-8ce6-9f11e5232c24&c=f4de0ac7-3a79-4ad2-8eb6-a22857680b6e

Ensures cgo is disabled for plugin compilation to avoid libc linking

---

webapp/src/widgets/menu/menu.scss

Not sure why this regressed, but explicitly setting the font size and line height for .menu-option now. We want to cherry pick this for the v0.7.0 release.

Fix #556: menu font size

---

webapp/src/octoListener.ts
webapp/src/pages/boardPage.scss
webapp/src/pages/boardPage.tsx

This will show a banner when the websocket connection is interrupted for more than 5 seconds, and remove it on re-connect.
It will link to troubleshooting steps via an fwlink `https://www.focalboard.com/fwlink/websocket-connect-error.html`, which currently points to https://github.com/mattermost/focalboard/discussions/566.
This will help mitigate the issue of Admins not configuring their web proxies correctly. However, this is also useful for general connectivity issues.

Fix #569: Show websocket connection error banner

---

config.json
server/integrationtests/clienttestlib.go
server/main/main.go
server/server/server.go
server/services/config/config.go

Renamed the config key names for logger and audit config.  `config.json` lets you specify a path to logging/audit config or provide config via embedded JSON.
`logging_file` was used as the key name to specify a path to config file for logging.  It was confusing as it could be mistakenly thought to be the name of the file to output logs to.  It has been changed to `logging_cfg_file`.  Same reasoning for changing `audit_file` to `audit_cfg_file`.
NONE

rename logger & audit config

---

server/api/admin.go
server/api/api.go
server/api/auth.go
server/app/app.go
server/go.mod
server/go.sum
server/server/server.go

This PR refactors the App lifecycle by not creating a new App instance each request.  One App is created at server creation time, and passed to any services needing it.
To avoid cyclical dependencies, the few server methods needed by App are provided via interface.
https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-88cc744576c8&c=8b6fc880-163b-4f70-8cfa-2be198b487be

Refactor App lifecycle

---

mattermost-plugin/plugin.json
mattermost-plugin/server/manifest.go

This PR adds a link to the setup instructions on the System Console section of `focalboard`. It should be cherry-picked to `v0.7.0` after merge.
[Focalboard card](https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=612a901f-5c6d-4dde-8e35-3c16b6024a67&c=a67e26c8-4e40-4c86-8a5a-c336f36bcf99)

Adds a link to the setup docs on the plugin's config header section

---

mattermost-plugin/server/plugin.go

This PR solves plugin not correctly serving the frontend interface when used in a server with a custom plugin directory. Fixes #592 
[Card](https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=612a901f-5c6d-4dde-8e35-3c16b6024a67&c=f8ad1709-b903-4172-8076-1b82649de09a)

Fixes web files not found when plugin directory is custom

---

webapp/src/combinedProviders.tsx
webapp/src/components/properties/user/user.test.tsx
webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
webapp/src/components/sidebar/sidebarSettingsMenu.tsx
webapp/src/i18n.tsx

Fixes #448 
- Modified the language selectors to remain the base language regardless of the translation.
- Traditional Chinese also had the wrong code and the name/code swapped.
- Modified the split of the `locale` to support Chinese language codes.

Updated lanquage selectors and fixed traditional chinese

---

docker/Dockerfile
docker/docker-compose-db-nginx.yml
docker/docker-compose.yml

If this commit merged focalboard helm chart would be able to implement a metrics endpoint.
Expose 9092 port on docker container
Follow-up to https://github.com/mattermost/focalboard/pull/414

Expose 9092 port on docker container

---

webapp/src/utils.test.ts
webapp/src/utils.ts

Fixes a double slash when calling buildURL()
Fixes https://github.com/mattermost/focalboard/issues/613

GH-613 - fix double slash on buildURL

---

webapp/src/components/table/__snapshots__/table.test.tsx.snap
webapp/src/components/table/table.tsx
webapp/src/components/viewHeader/viewHeaderSortMenu.tsx

Fixed ascending and descending sort icons.
1. Changed ascending icon to up arrow.
2. Changed descending arrow to down arrow.
Before-
After-
https://github.com/mattermost/focalboard/issues/561

Fixed sorting icons

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go
server/services/store/sqlstore/sqlstore.go

This adds the environment variables to limit the number of connections to the database. This is a temporary fix, and this works just fine in regular on prem service, but in mattermost-plugin, because the database connection is "duplibcated" the value added in the environment variable is going to be duplicated.
This is only for the 0.7.1 version, the 0.8.0 version is going to come with the new shared db connections provided by @agnivade, so this can be perfectly deprecated.

Adding max-db-conns and max-idle-conns through environment variables

---

webapp/src/components/sidebar/sidebarBoardItem.scss

Don't change visibility of `MenuWrapper` when hover state of its parent is changed.
Fixes #538

[GH-538] Fix for menu of side bar item

---

webapp/cypress/integration/createBoard.js

Cypress test for hiding and showing the sidebar with active board added:
* active board is essential because it can cover the show  button,
* presence of sidebar heading is used to check if sidebar is visible.
* changing `z-index` of hidden sidebar back to `5` (as it was before the actual fix) _will be caught_ by this test in Cypress with the message:
```
Timed out retrying after 4050ms: cy.click() failed because this element:
<div class="octo-sidebar-header show-button">...</div>
is being covered by another element:
<div class="top-head">...</div>
```
This test will help to avoid bugs like #641

[GH-641] Test for hiding and showing the sidebar

---

server/ws/websockets.go

Prevented concurrent writes to websockets. This fixes the the plugin crash occurring when dragging and dropping multiple cards together.
The problem is caused by gorilla WebSocket not support concurrent writes to WebSockets - https://github.com/gorilla/websocket/issues/119
#650

Prevented concurrent writes to websocket

---

mattermost-plugin/server/plugin.go
server/server/server.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go
server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/system.go
server/services/store/sqlstore/user.go
server/services/store/sqlstore/util.go
server/services/store/sqlstore/workspaces.go

This PR fixes a leak where not all code paths closed `*sql.Rows`.  
Some code paths implicitly closed rows by enumerating the whole set, which closes automatically.  However, an early return while iterating caused a leak.  
Other code paths explicitly closed the rows in a utility method that iterated the rows, therefore the close was not where the allocation occurred.  The hidden close caused some places to leak where the utility was no longer used.  
Another minor issue was that the error returned from `sql.Rows.Close()` was ignored.
This PR ensures all allocations of `sql.Rows` close the rows at the allocation site, and logs any errors.
https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=ca1a5441-4c1c-4d0e-856e-8 …

Ensure all code paths close *sql.Rows

---

mattermost-plugin/server/plugin.go

This PR checks if the `SiteURL` property is set and uses an empty string if it's not, preventing the plugin from crash at start time due to a `nil` pointer.
Possibly related to https://github.com/mattermost/focalboard/issues/648

Prevent plugin from crashing if SiteURL is not set

---

webapp/src/components/kanban/kanban.tsx

When cards are dropped on the column change also the cards order in the active view along with their properties. 
Fixes #622 
* should this be done only when manual order is selected?
* how can we test this with jest tests?

[GH-622] Fix dragging card to another column

---

webapp/src/components/table/table.scss

An unrelated PR unintentionally increased the table row height. This PR fixes that.
NA

Fixed table row height

---

webapp/src/components/sidebar/sidebar.tsx
webapp/src/components/sidebar/sidebarUserMenu.tsx

This hides the (non-functional) account actions in the Focalboard menu when running as a plugin.

Fix #739: Don't show account options as plugin

---

webapp/src/theme.ts

Issue 678 - Updating default dark theme label
https://github.com/mattermost/focalboard/issues/678

Issue 678 - Updating default dark theme label

---

server/services/store/sqlstore/blocks.go

This reverts the InsertBlock logic to insert per workspace. This was changed in PR #583, and due to that change, blocks with the same ID in different workspaces would fail to update. It also exposes a security hole where the workspace of a block can be changed by an insert.
Currently, the primary key of a block is WorkspaceID+ID. If / when we change that, we will need to change it across the DB store system.

InsertBlock per workspace logic

---

webapp/src/components/kanban/kanban.tsx

If you create a new card and then try to drag to a new group, it won't work because boardTree is out of sync. 
Sometimes boardTree is not in sync and it causes cards not being able to be dragged to different columns hence we need to useRef to fix this.
Fixes GH-626

Fix Cards not Dragging to different Columns (GH-626)

---

webapp/src/components/propertyValueElement.tsx
webapp/src/components/sidebar/__snapshots__/sidebarSettingsMenu.test.tsx.snap
webapp/src/components/sidebar/sidebarSettingsMenu.tsx
webapp/src/dateFormat.ts
webapp/src/userSettings.ts
webapp/src/widgets/editableDayPicker.tsx

* Preferred date format removed from the user settings
* Date format for editing in the input is always `MM/DD/YYYY` 
Fixes #778

[GH-778] Remove date format from the user settings

---

webapp/src/components/cardDetail/comment.tsx
webapp/src/components/properties/createdAt/createdAt.tsx
webapp/src/components/properties/lastModifiedAt/__snapshots__/lastModifiedAt.test.tsx.snap
webapp/src/components/properties/lastModifiedAt/lastModifiedAt.test.tsx
webapp/src/components/properties/lastModifiedAt/lastModifiedAt.tsx
webapp/src/components/table/__snapshots__/table.test.tsx.snap
webapp/src/utils.test.ts
webapp/src/utils.ts

Format for date and time changed:
* `Utils.displayDateTime` is used inside `Comment`/`CreatedAt`/`LastModifiedAt` components
* options for month and year are the same as in `Utils.displayDate` for consistency
Here is how it looks in the card dialog:
and on the board:
Fixes #779

[GH-779] Consistent date time format

---

Makefile

This PR adds documentation to Makefile so that rules can be easily looked up with `make help`. This should help new contributors as well as people jumping between projects to not constantly looking something up in the `Makefile`.
It also removes `server-doc` rule that does not seem to be working.
Screenshot with the output of running `make help`:
Fixes #805

[GH-805] - Add Makefile documentation

---

webapp/src/components/kanban/kanban.scss

Fix for kaban board height: use `1` for `flex-grow`.
Fixes #815

[GH-815] Fix kanban board height

---

webapp/src/components/cardDetail/__snapshots__/cardDetailProperties.test.tsx.snap
webapp/src/components/propertyValueElement.tsx
webapp/src/components/table/__snapshots__/table.test.tsx.snap
webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
webapp/src/styles/main.scss
webapp/src/widgets/valueSelector.scss
webapp/src/widgets/valueSelector.tsx

Fixes #370 
For table view:
For read only cases like board card and gallery card:
For card view:

Add clear button to value selectors

---

webapp/src/components/sidebar/sidebarUserMenu.tsx
webapp/src/components/topBar.scss
webapp/src/components/topBar.tsx

This moves the version label to the top right of the main page when running as a plugin:

Move version label to top right for plugin

---

webapp/src/octoClient.ts

I ran into the issue in the associated bug. This was introduced when BoardTree was removed during the Redux refactor. BoardTree used to call HydrateBlocks, which fixes downloaded blocks to the latest schema. This change makes the HydrateBlocks call in OctoUtils.

Fix #945. Hydrate blocks on get

---

webapp/src/components/calculations/__snapshots__/options.test.tsx.snap
webapp/src/components/calculations/options.tsx
webapp/src/components/properties/dateRange/dateRange.scss
webapp/src/components/table/calculation/calculationRow.scss

Updated some old CSS variables to the new ones.
Fixes #938

Fixed missing CSS vars

---

webapp/src/components/calculations/options.tsx

Added ability for calculation menu to open wherever there is available space
Fixes #930 
It opens the menu at the bottom by default and opens above if there is no space below
This changes the behaviour from the default top menu to the default bottom menu. Unfortunately, there is no way in react select to set default menu placement to top and open in the bottom only if there is no space.

Added ability for calculation menu to open wherever there is available space

---

webapp/src/components/sidebar/sidebar.scss
webapp/src/components/sidebar/sidebar.tsx

Updated UI on the plugin:
* Add the hide button on the same row as the workspace (channel) name
* Fix showing the show-sidebar (hamburger) button when hidden (this was a css conflict with the .hidden class)

Fix #934. Sidebar hide-unhide as plugin.

---

webapp/src/components/gallery/gallery.scss

Allows overflow on the Gallery container.
This was previously supplied by the `BoardComponent` but set to `overflow: hidden` to fix double scrollbars.
The other views, `Board` and `Table` provide the overflow setting on the same class, so this is now more consistent with other views.
Fixes https://github.com/mattermost/focalboard/issues/964

GH-964: Allow overflow in Gallery View

---

webapp/src/components/viewHeader/filterEntry.tsx

fixes bug where wrong filter was being deleted and last filter couldn't be deleted.
Fixes https://github.com/mattermost/focalboard/issues/958

GH-958 - fix for wrong filter deletion

---

webapp/src/components/markdownEditor.tsx
webapp/src/styles/main.scss
webapp/src/theme.ts

Fixes GH-955 
Fix CSS variable name to show proper color
Fixes GH-936
Needed to import SIMPLE MDE css file as per their instructions https://github.com/RIP21/react-simplemde-editor/blob/master/README.md#usage
Also a mismatch on --link-color-rgb . Standalone received a hex value, plugin received a RGB value. 
I had to make it so the plugin also passed down a hex value so the color got correctly set.

Fix GH-955 and GH-936

---

webapp/src/components/workspace.scss

Because the sidebar uses position: absolute, the uncollapse button is hidden when there is a global header. Solution is for the container (Workspace) to be position: relative.

Fix #977. Show uncollapse button even with global nav.

---

webapp/src/store/contents.ts

When editing template card or creating a new one, content of template card doesn't show up. 
This fixes the problem by including template cards
Fixes GH-1006

Fix GH-1006: Editing card template's description doesn't work

---

mattermost-plugin/webapp/src/plugin.scss

GH-994 - Updating color for global header menu
https://github.com/mattermost/focalboard/issues/994

GH-994 - Updating color for global header menu

---

webapp/src/components/properties/link/link.tsx

Stop event propagation for click on the link for URL property.
Fixes #1033

[GH-1033] Prevent opening card dialog when link for URL is clicked.

---

mattermost-plugin/server/manifest.go
webapp/src/wsclient.ts

The `WSClient` in plugin mode can start sending messages before the Mattermost WebSocket client is ready. This PR adds a retry mechanism for `WSClient` to be set as `open` only when the Mattermost WebScocket client is connected.
Fixes #1125

Add retry mechanism when opening WSClient in plugin mode

---

mattermost-plugin/webapp/src/plugin.scss

Updates CSS to unset menu setting that are causing an issue with the GlobalNav Bar.
Fixes https://github.com/mattermost/focalboard/issues/1131

GH-1131 - fix for displaying global nav in focalboard

---

mattermost-plugin/webapp/src/plugin.scss
webapp/src/components/viewHeader/viewHeader.scss
webapp/src/widgets/buttons/button.scss

1112 - Updating button active state in viewHeader
The problem with this is, that the buttons by default use `semibold` weight on community, so styles conflict. I have given the button another style.
Fixes https://github.com/mattermost/focalboard/issues/1112
Fixes https://github.com/mattermost/focalboard/issues/1095

1112 - Updating button active state in viewHeader

---

webapp/src/store/comments.ts

Sort card comments oldest-first. Also remove unused `getComments` method to avoid future confusion.
Fixes #1206

Fix #1206. Sort card comments.

---

webapp/src/components/dialog.tsx

This resolves the timing issue in FireFox between the dialog background click and onBlur handing in MarkdownEditor.
Notes:
* When I added a breakpoint (in FireFox) to the onMouseDown handler in Dialog.tsx, the bug does not repro, even without this change
* Not sure which part of the onClose handler causes the update to abort.

Fix #1217. Save dialog changes before closing.

---

webapp/src/components/sidebar/sidebar.scss

Updated the css selector to only hide the collapse-sidebar button when there is a workspace. This might need to be refactored in the future to be more robust.

Fix #1215. Don't sidebar collapse on Personal Server.

---

webapp/src/widgets/menuWrapper.scss

Adds settings 
-webkit-user-select: text; /* Chrome all / Safari all */
-moz-user-select: text; /* Firefox all */
-ms-user-select: text; /* IE 10+ */
for .MenuWrapper *:firstChild{}
All other places we set `user-select: text;`, we set these as well.
Related to -
https://github.com/mattermost/focalboard/pull/1094
Fixes https://github.com/mattermost/focalboard/issues/1244

GH-1244 add setting -webkit-user-select and others for MenuWrapper

---

server/integrationtests/blocks_test.go

Disables Flakey Server Test - TestGetSubTree
created ticket to fix and reenable (https://github.com/mattermost/focalboard/issues/1305)
Fixes https://github.com/mattermost/focalboard/issues/1232

disable flakey test

---

modd-watchplugin.conf

In some cases both server and webapp commands can collide when first starting as the server watcher was watching for changes on the `manifest.go` file, which is generated by both targets.
This PR ignores that file so no build loop happens.

Ignores manifest.go file on watch-plugin to avoid reboot loop

---

webapp/src/cardFilter.ts

When the filter has a "notIncludes" clause, don't set a property value for new cards. The intent of this code is so that new cards appear with the current filter settings. However, the previous behavior of setting the value to another unfiltered value is unnecessary.

Fix #1285. Don't set property for notIncludes filter.

---

server/app/blocks.go
server/model/block.go
server/services/store/sqlstore/blocks.go
server/ws/plugin_adapter.go
server/ws/server.go
webapp/src/blocks/block.ts
webapp/src/components/content/checkboxElement.test.tsx
webapp/src/pages/boardPage.tsx

This PR adds the `workspaceID` property to the blocks when they're retrieved from the store and makes the boards page react only to those updates that are aimed at the workspace that the user is currently in.
Fixes https://github.com/mattermost/focalboard/issues/1280

Adds workspaceID to blocks and makes board page only reacts to the workspace updates

---

mattermost-plugin/webapp/src/index.tsx

Fix closing tab mattermost hang issue.
Whenever you open Focalboard from the header icon and close the tab, your mattermost instance freezes.
This PR aims to fix the issue

Fix closing tab mattermost hang issue

---

webapp/src/pages/boardPage.tsx

Currently, the page title is "Focalboard". When running as a plugin, the page title should be "Boards - Mattermost" to align with the new branding. Personal Editions should continue to be titled "Focalboard"
This is only displayed when No Board is selected.
Fixes https://github.com/mattermost/focalboard/issues/1312
Plugin (notice url)
Personal Server (notice url)

GH-1312 - Update title when running a plugin

---

webapp/src/components/calculations/calculations.test.tsx
webapp/src/components/calculations/calculations.ts
webapp/src/components/calculations/options.tsx

Adds count and percent table calculations for checkbox property
https://github.com/mattermost/focalboard/issues/1082

[GH-1082] Add count and percent table calculations for checkbox

---

webapp/@custom_types/pgtools.d.ts

This pr removes the file `webapp/@custom_types/pgtools.d.ts`
I could not find any reference to this file anywhere. Not in package.json. Nor could I find any reference to the functions exported from this file. 
It is causing lint warnings, rather than attempt to fix, remove the file.
Fixes https://github.com/mattermost/focalboard/issues/1364

gh-1364 - remove file causing lint warnings

---

webapp/src/components/gallery/galleryCard.scss

Fixes for drag and drop of gallery card:
- use `translate3d` workaround for proper preview in Chrome
- set `pointer-events` to `none` to prevent image opening in Firefox
Fixes #1291 and #1265

[GH-1291] Fix drag and drop for gallery card

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dev-release.yml
.github/workflows/lint-plugin.yml
.github/workflows/lint-server.yml

Update workflow files to run on `release-**` branches in addition to main. Per [GitHub docs here](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags).

Fix #1365. Run CI workflows on release branches

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dev-release.yml
.github/workflows/lint-plugin.yml
.github/workflows/lint-server.yml

A recent cherry-pick via PR caused the release branch to have linter errors because CI was not run against PR's to be merged into release branches.  This PR ensures full CI is run for these cases.
https://github.com/mattermost/focalboard/issues/1365

Run all CI on PRs to be merged with release branches

---

webapp/src/app.tsx
webapp/src/components/viewMenu.tsx
webapp/src/components/workspace.tsx
webapp/src/octoClient.ts
webapp/src/utils.ts

This PR fixes two issues. 
1. When we change views on shared boards, non validated users receive an Access Denied error.
This appears to work in Personal Server, however, because the token is not included in the query string, a refresh in Personal Server results in the same error.
Add the `?r=readtoken` parameter to the url path when either displaying a different view or a card view.
2. While testing, the card view was not being displayed in read-only view. 
I think this is due to the recent route changes. 
Add the `/cardId?` parameter to the "shared" routes.
Fixes https://github.com/mattermost/focalboard/issues/1371

gh-1371 - Add readtoken when in readonly mode

---

webapp/package.json

Added `--progress` for `watchdev` npm script. This allows to show progress when webpack is in watch mode, similar to what is used in [webapp repo](https://github.com/mattermost/mattermost-webapp/blob/master/package.json#L285).
No ticket link.

Progress for webpack watch mode

---

webapp/src/components/kanban/kanbanCard.scss
webapp/src/components/properties/link/link.tsx
webapp/src/widgets/label.scss

Fix displaying properties on kanban cards:
- hide URL property only when it is empty
- hide empty labels for Select/Multi Select properties
Here is how it looks (non-empty URL property is visible, empty property values are collapsed):
Also minor tweak for proper alignment of Select/Multi Select empty labels:
Fixes #1331

[GH-1331] Fix for URL property on kanban card

---

mattermost-plugin/webapp/loaders/globalScssClassLoader.js
mattermost-plugin/webapp/src/plugin.scss
webapp/src/widgets/icons/logo.tsx

Fixing tiny icons caused by CSS pollution. 
Tiny icons on community:
Fixed version:
https://mattermost.atlassian.net/browse/MM-38807

MM-38807 Fix tiny icons caused by css pollution

---

webapp/src/app.tsx

Resolves the issue of opening Boards via a link in Channels.
Fixes #1373

Resolved issue regarding openign boards link from channels

---

webapp/src/components/viewHeader/viewHeader.test.tsx

Views were added to the mocked store state because they are required by the code that is being tested.
Not related to any ticket.

Fix failing unit test for viewHeader

---

webapp/src/components/viewHeader/__snapshots__/viewHeaderActionsMenu.test.tsx.snap
webapp/src/components/viewHeader/viewHeaderActionsMenu.test.tsx
webapp/src/testUtils.tsx

Add other tests unit to viewHeaderActionMenu
Fixes #865

[GH-865] Add more tests unit to viewHeaderActionMenu

---

webapp/i18n/en.json
webapp/src/pages/dashboard/__snapshots__/centerContent.test.tsx.snap
webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap
webapp/src/pages/dashboard/centerContent.tsx
webapp/src/pages/dashboard/dashboardPage.scss
webapp/src/userSettings.ts

Add a "Show empty" toggle to the Dashboard to show / hide workspaces with no boards. This setting is persisted in localStorage.
https://github.com/mattermost/focalboard/issues/1397

Fix #1397. Add show empty toggle to Dashboard

---

import/trello/importTrello.ts

Adds the ability to import checklists to Focalboard when importing from Trello. It's pretty simple code, but it's my first attempt at TypeScript, so appreciate any feedback. I'm not 100% sure of my `undefined` logic etc. But it does work :shrug: 
This is kind of related to https://github.com/mattermost/focalboard/issues/53 but there's no specific issue relating to this. I wrote it for my own needs and figured I should push it upstream.
I started looking at importing images as well, but they require auth now if the Trello board is private. That is a different kettle of fish, so decided to leave that out of this PR.

Add the ability to import checklists from Trello

---

webapp/src/components/__snapshots__/propertyValueElement.test.tsx.snap
webapp/src/components/propertyValueElement.test.tsx
webapp/src/components/propertyValueElement.tsx

When hitting escape, the value in state gets reset to the property value from state. However, PropertyValue may be null. Value is not expected to be null. If null, set to empty string. 
Fixes https://github.com/mattermost/focalboard/issues/1441

make sure setValue receives empty string

---

webapp/src/app.tsx

Fixes an issue where the registration token is removed from the URL. This removal results in the registration failing.
Fixes https://github.com/mattermost/focalboard/issues/1448

GH-1448 - Only call history replace if a plugin

---

webapp/src/app.tsx

Removes the history replace for legacy plugin mode, fixing the shared boards URLs in the plugin.
Fixes https://github.com/mattermost/focalboard/issues/1438

Move app history replace to happen only if not in plugin legacy mode

---

webapp/src/pages/boardPage.tsx

This PR checks `board` and `activeView` for `null`s when tracking the view shared board event.
Fixes https://github.com/mattermost/focalboard/issues/1729

Check nulls on board and active view when tracking telemetry events

---

server/model/blocktype.go
server/utils/utils.go

The recently added `BlockType2IDType` method was put into `utils` but created a cyclic dependency with `model`.  Things in `utils` should not depend on `model`.  This PR moves the method to `model`.
NONE

Move BlockType2IDType from utils to model

---

server/services/store/sqlstore/sqlstore.go

Modify how the store is initialized not to fail in case the templates are not initialized correctly, but to log the error and continue normally.
Fixes https://github.com/mattermost/focalboard/issues/1515

Modify store creation not to fail on template initialization failure

---

webapp/src/app.tsx
webapp/src/pages/boardPage.tsx
webapp/src/utils.ts

This PR redirects the user to the new plugin routes if it detects they're visiting an old legacy board URL.

Redirect to new routes when visiting a board with the legacy ones

---

webapp/src/store/initialLoad.ts

When a workspace is not defined, the api call returns an `undefined` workspace, not an error. This PR updates the initial load to throw an error if the workspace is not returned. 
https://github.com/mattermost/focalboard/issues/1685

GH-1685: Error if workspace is undefined

---

website/site/content/download/mattermost/_index.md

Add utm_source and campaign to website links to the main mattermost website, in order to better track conversions.

Add utm_source and campaign for links to main site

---

mattermost-plugin/server/plugin.go

This PR adds unfurl meta-data when creating @mention notification posts.  This includes support for unfurling of inline links, meaning any posts with inline links will now unfurl.
Fixes https://github.com/mattermost/focalboard/issues/1692

GH-1692: Show card preview in @mention notification DM

---

webapp/src/app.tsx

Only allow routes without workspace prefix if you are in non-plugin mode

---

mattermost-plugin/webapp/src/index.tsx
webapp/src/utils.test.ts
webapp/src/utils.ts
webapp/src/wsclient.ts

The new version banner is showing on every plugin update, as there is no way to distinguish which plugin has been changed in the websocket message. This PR compares the new Boards version with the current one and only shows the version banner in that case.
For the cases where an update happens and the interface is refreshed, the previous fix would not work because of the plugin lifecycle, so we trigger a delayed reconnect as a temporal solution so the interface doesn't become unresponsive.
A more complete solution would be to ACK the websocket subscription message so the plugin can retry until the server acknowledges the subscription and could show a warning in the meantime.

Shows the version change banner only on plugin update and tries to reconnect when the interface is refreshed

---

webapp/cypress/integration/createBoard.js
webapp/src/components/kanban/kanbanColumnHeader.tsx

* Fix the issue where clicking on the + button at the top of a board group wouldn't open the newly-added card
#1694

[GH-1694] Fix the issue where clicking on the + button at the top of a board group wouldn't open the newly-added card

---

webapp/src/components/kanban/calculation/calculationOptions.test.tsx
webapp/src/components/kanban/calculation/calculationOptions.tsx

Fixed a bug causing duplicate date related menus to appear in kanban calculations
Fixes #1801

Fixed a bug causing duplicate date related menus to appear in kanban calculations

---

mattermost-plugin/server/plugin.go

Replaces **RAW** Focalboard Card links with `<Jump To Card>` unlocalized
Fixes https://github.com/mattermost/focalboard/issues/1805 
Concluded Solution (from above Issue)

GH-1805: Replace unfurl link with card title

---

mattermost-plugin/Makefile
mattermost-plugin/plugin.json
mattermost-plugin/server/manifest.go

Adding the linux/darwin arm64 targets, we start building arm64 for the server and will start adding the targets for the plugins for the ones we prepackage in the build
related to: https://github.com/mattermost/mattermost-server/pull/18491
related to https://mattermost.atlassian.net/browse/DOPS-633

dist: build linux/darwin arm64 targets

---

webapp/src/components/calendar/fullcalendar.scss
webapp/src/components/kanban/kanbanCard.scss
webapp/src/components/table/table.scss

GH-1051 - Aligning card title with emojis
Fixes https://github.com/mattermost/focalboard/issues/1051

GH-1051 - Aligning card title with emojis

---

website/site/content/fwlink/feedback-boards.html
website/site/content/fwlink/feedback-focalboard.html

The feedback link was already passing the version number. This change passes that along to the feedback form for recording. This update is for both Boards and Focalboard. To test, you may beed to clear your browser cache.
#1908

Fix #1908. Pass version to feedback form.

---

mattermost-plugin/server/notifications.go
server/services/notify/plugindelivery/plugin_delivery.go
server/services/notify/plugindelivery/user_test.go

This PR ensures that users mentioned on a card that are not members of the channel do not get notified.  This is a silent fail, a if the author typed a non-existent user e.g. `@nouser`
Fixes https://github.com/mattermost/focalboard/issues/1879

Don't notify @mentioned users who are not members of channel

---

website/site/content/download/mattermost/latest-plugin/_index.md

This PR adds a section on the install instructions to enable Reliable Websockets.

Add a note to enable reliable websockets on plugin install

---

webapp/src/components/markdownEditorInput/markdownEditorInput.tsx

Don't set focus for `MarkdownEditorInput` on mount if it is not in editing state.
Also fixes `at-mention` popup appearing in top-right corner of screen after re-focus.
Fixes #1946
Fixes #1877

[GH-1946] Fix losing focus for the card title in the dialog

---

webapp/src/components/centerPanel.test.tsx
webapp/src/components/viewHeader/viewHeader.test.tsx
webapp/src/components/viewHeader/viewHeaderSearch.test.tsx
webapp/src/components/viewHeader/viewHeaderSearch.tsx

Added a state to search component that stores the viewId and when the view is changed the search is cleared. Let me know if there is any better approach / improvement to this approach.
Fixes #1730.

[GH-1730]: Clear search on view change

---

server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/data_migrations_test.go

I know this solutions looks wrong and brittle, but the key point is, it is really hard to find the ID in the whole fields set by coincidence, so looks like it is "safe enough", and simple enough. Because this is a "one time thing" that only apply, and only on the duplicated ids. I think is acceptable.

Include migration for content order on unique id migration

---

webapp/cypress/integration/createBoard.ts
webapp/src/components/__snapshots__/workspace.test.tsx.snap
webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
webapp/src/components/sidebar/sidebarBoardItem.scss
webapp/src/components/sidebar/sidebarBoardItem.tsx
webapp/src/styles/main.scss

GH-1872 - Updating octo-icon font weight
Fixes https://github.com/mattermost/focalboard/issues/1872
PR replacing https://github.com/mattermost/focalboard/pull/1976 with updated unit tests and cypress test

GH-1872 - Updating octo-icon font weight

---

webapp/src/pages/errorPage.tsx

Fixes `/error` page button to follow base URL.
Fixes #1883 
1. Set up focalboard on subpath
1. Visit `/<subpath>/error` and click button
1. Page should now be `/<subpath>/login` (instead of `/login`)

[GH-1883] Fix error page button to follow base URL

---

server/server/server.go
webapp/src/components/properties/lastModifiedAt/__snapshots__/lastModifiedAt.test.tsx.snap
webapp/src/components/table/__snapshots__/table.test.tsx.snap

Previously, we try to unlink the existing admin local socket on startup, even if the file doesn't exists. This results in a confusing error log, even though it doesn't cause a failure. The change is to only try to unlink the socket file if it exists.
#1745

Fix #1745. Delete socket only if it exists

---

webapp/src/components/live-markdown-plugin/inline-styles/italicStyleStrategy.ts

The RegEx compiler throws an unhandled error on Safari because it doesn't support Lookbehinds. Change is to catch the exception and use an alternative, simplified regex.
Note: The alternative doesn't support complex nested bold and italics fully (e.g. ***italic* and bold** **bold and *italic***), but even the original had some issues. Those are rare, and only affect the preview (final rendering with markedjs should be correct), so leaving that for a future improvement (contributions welcome!).
#1999 and #2002.

Fix #1999, fix #2002: Alt italics regex without lookbehind

---

server/services/store/sqlstore/data_migrations.go

Fix for error when updating postgres from prior version. 
```
Unable to restart plugin on upgrade., error initializing the DB: error running categoryID migration: pq: unexpected Parse response 'C'
```
Based on this article is was due to `rows` object not being closed. 
https://kecci.medium.com/resolved-pq-unexpected-parse-response-c-postgres-golang-8a2fdf90a74b

close rows inside transaction

---

server/api/api.go
server/app/blocks.go
server/integrationtests/subscriptions_test.go

Investigating a crash reported in MM cloud was traced to a DeleteBlock API call from the client.  The block was already deleted by the time the request hit the server.  I can see several ways this can happen:
- multiple people deleted a block at the same time
- single user trying to delete a block a second time before receiving the result from the first
The main issue is that `sqlstore.getBlock` returns a nil block and nil error when the block id doesn't exist.  Some callers of this API only check the error and either crash or don't crash completely by accident.  For example, `PatchBlock` will crash (or not) based on timing.  `PatchBlocks` will silently fail patching the batch and return success to the client.
A ticket exists to have store APIs that return a single entity return a …

fix crash in DeleteBlock

---

Makefile

This PR makes testing all databases the default.  `make server-test` will test sqlite, mysql, and postgres.  
If you want the fast unit test cycle, use `make server-test-sqlite` 
NONE

make testing all databases the default

---

server/api/api.go
server/model/block.go
server/model/block_test.go

Fixed a bug where block IDs weren't being updated in `contentOrder`. When we updated the block IDs, we weren't updating them in `contentOrder` array, causing blocks to point to incorrect blocks belonging outside the current workspace.
Fixes #2017

Fixed a bug where block IDs weren't being updated in `contentOrder`

---

server/model/notification.go
server/services/notify/notifysubscriptions/diff.go
server/services/notify/notifysubscriptions/diff2slackattachments.go
server/services/notify/notifysubscriptions/notifier.go
server/services/notify/notifysubscriptions/util.go
server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/migrations/bindata.go

This PR addresses an issue with card change notifications when multiple users are editing a card at the same time.  Before this PR, only the first user to start editing would be listed in the notification.  After this PR, all authors of a card diff are listed.
Also, when comments are added, the author of the comment is included with the individual comment.
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/150d1464-6d59-4c39-810f-ee201439dbaf/c1dawrhr97frq381xkh94uno9ir

List all authors of a card diff in the notification

---

webapp/src/components/markdownEditorInput/markdownEditorInput.tsx

Fix for https://github.com/mattermost/focalboard/issues/2036 causes comments to be entered backwards. This PR fixes that issue while keeping the prior fix intact.
Fixes https://github.com/mattermost/focalboard/issues/2075

fix comments being set backwards

---

webapp/src/wsclient.ts

This appears to be a timing issue in JS / React:
1. UseEffect in Boardpage.tsx subscribes and unsubscribes to workspace changes on the websocket (wsClient)
2. The cleanup routine returned from useEffect does the unsubscribe
3. With the Mac App (single-user), there's a pattern of useEffect, useEffect-cleanup, useEffect
4. However, in that last useEffect call, wsClient.state is 'init' (on [this line](https://github.com/mattermost/focalboard/blob/main/webapp/src/pages/boardPage.tsx#L206)), so subscribe isn't called
5. This is because wsClient is still somewhere in the [opening routine](https://github.com/mattermost/focalboard/blob/main/webapp/src/wsclient.ts#L259).
The fix is to update `wsClient.state` at the beginning of `ws.onopen`.
I've only observed this happening in the Mac App, and not …

Gh 2077 mac app update

---

webapp/src/components/markdownEditorInput/markdownEditorInput.tsx

Fix for https://github.com/mattermost/focalboard/issues/2036 causes comments to be entered backwards. This PR fixes that issue while keeping the prior fix intact.
Reverts https://github.com/mattermost/focalboard/issues/2076
Fixes https://github.com/mattermost/focalboard/issues/2075

updated fix for comments display backwards

---

server/services/notify/notifysubscriptions/diff2slackattachments.go
server/services/notify/notifysubscriptions/notifier.go

This PR fixes a bug where card links in notifications always pointed to the card used in the first notification since server boot.  The board and card pointers were being cached in a template via custom format method.  The custom formatter had an enclosure containing the pointers.
Fixes https://github.com/mattermost/focalboard/issues/2092

Fix card link in notifications

---

server/model/properties.go

This PR fixes property change formatting for notifications, specifically for `Date` and `Multiselect`.  
https://github.com/mattermost/focalboard/issues/2094

Fix prop change formatting for date & multiselect

---

mattermost-plugin/webapp/webpack.config.js
webapp/src/app.tsx
webapp/src/components/__snapshots__/shareBoardComponent.test.tsx.snap
webapp/src/components/shareBoardComponent.test.tsx
webapp/src/components/shareBoardComponent.tsx
webapp/src/pages/welcome/__snapshots__/welcomePage.test.tsx.snap
webapp/src/pages/welcome/welcomePage.test.tsx
webapp/src/pages/welcome/welcomePage.tsx
webapp/src/utils.ts

Fixes #1766
Fixes #2032
This fixes the problem, but doesn't sorted out the multiple ways of getting the URLs.

Moving the history instance creation after the plugin initialization (to honor the SiteURL config)

---

server/model/properties.go
server/services/notify/notifysubscriptions/diff.go

This PR ensures that usernames appear in card change notifications for `person` property type.  `Date` and `multiselect` were fixed via https://github.com/mattermost/focalboard/pull/2110
Fixes https://github.com/mattermost/focalboard/issues/2094

Resolve usernames for `person` property type

---

webapp/src/components/__snapshots__/topBar.test.tsx.snap
webapp/src/components/__snapshots__/workspace.test.tsx.snap
webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
webapp/src/components/sidebar/sidebarUserMenu.tsx
webapp/src/components/topBar.tsx
webapp/src/constants.ts
webapp/src/pages/dashboard/__snapshots__/dashboardPage.test.tsx.snap

Replace the version display with the release Month+year. Show the version number on hover.
#2136

Fix #2136. Show release month+year for version.

---

README.md

Cleaned up the Try Focalboard section, and added direct links to the Mac and Windows App Stores.

Update readme: Personal Desktop links

---

webapp/html-templates/page.ejs

There is no file `easymde.min.css` after switching from `react-simplemde-editor` to `draft-js`
No ticket.

Remove link to deleted css file

---

Makefile

Hi again! I had some issues running the `make mac-app` on my mac with the m1 chip - it is building the app here now. Would be nice to have some feedback from people with a amd64 GOARCH to make sure I didn't break anything.

Fix mac m1 chip build, get architecture during make mac-app. Fixes #2160

---

webapp/.eslintrc.json

There are several webapp files that exceed the default ESLint max-lines rule.  This PR disables the rule to avoid polluting the VSCode problems view with these warnings.
NONE

Disable `max-lines` ESLint rule

---

website/site/content/download/mattermost/_index.md
website/site/content/download/personal-edition/_index.md
website/site/content/download/personal-edition/desktop.md
website/site/layouts/partials/hero.html

Update several download links on the website, including the App Store links (and added the App Store icons) and Mattermost. Also streamlined and tweaked some of the wording.
Note: Changes are live on [focalboard.com](https://www.focalboard.com/) now. You can review the changes there (refreshing your browser may be needed to clear the cache).

Website 012422 download links

---

server/services/notify/notifysubscriptions/notifier.go
server/services/store/sqlstore/notificationhints.go

This PR fixes an issue where errors are logged when multiple nodes in a cluster try to process a notification hint at the same time. This is an expected condition and should not error.
Fixes https://github.com/mattermost/focalboard/issues/2165
Issue was reported here: https://community.mattermost.com/core/pl/r7zfhdrqnidu8pdf9tk8dgr4ro

Don't log error msg when multiple nodes try processing a notification hint

---

server/ws/plugin_adapter.go

Changes an error log to a debug log as is expected if plugin restarts.
Fixes https://github.com/mattermost/focalboard/issues/1900

GH-1900 - change log from error to debug

---

docker/README.md

As mentioned in the last comment on #670, there is an error if you run the Docker image with the instruction of the current readme, mounting a directory as `/data`.
This error (`unable to open database file: no such file or directory`) arises if the host directory is not owned by the user `nobody`.
WIth this PR, I propose to add this information to the README, as well as the `chown` command in the code snippet.

Add `chown` for nobody in the docker run example

---

webapp/src/blocks/__snapshots__/board.test.ts.snap
webapp/src/blocks/board.test.ts
webapp/src/blocks/board.ts
webapp/src/mutator.ts
webapp/src/octoClient.ts

Reimplements the function `insertPropertyTemplate`, `duplicatePropertyTemplate`, and `changePropertyTypeAndName` to use the boards API.
Also completed the implementation of patchBlocksAndBoards() and use that implementation.
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/v3ng1gwe7wtfaijukrhp8siwcpy/ci5zu37mhw7bjbe6ppyi6ra3jow

Update property template mutators to use boards API

---

server/model/properties.go

This PR fixes a panic when resolving model.User for `person` property types when the user is not found (e.g. board imported from a different server).  The `GetUserByID` API can return a nil user and nil error.
NONE

Fix panic in PropDef.GetValue for `person` property types.

---

webapp/src/pages/boardPage.scss

Fixed a bug causing double scroll bars to appear
Fixes #2211

Fixed a bug causing double scroll bars to appear

---

webapp/src/archiver.ts

Use correct file extension when exporting archives (`.boardarchive`)
Fixes https://github.com/mattermost/focalboard/issues/2239

Fix export archive file extension

---

webapp/src/components/markdownEditor.scss

Fixed a bug where the user cannot edit description block if only a space.
Fixes #2063
The problem was that only a space in the text, the HTML element didn't take any height, so the user couldn't click on the element to trigger an edit.

Fied a bug where user Cannot edit description block if only a space

---

mattermost-plugin/server/plugin.go
server/ws/helpers_test.go
server/ws/plugin_adapter.go

This PR reduces noise in the log output by changing `BroadcastingBlockChange` and `BroadcastingSubscriptionChange` log events from `info` to `debug`.
The logger calls are also changed to use the PluginLogAdapter like the rest of the FB server.  This is in preparation for a future PR on MM server to accept raw Logr records and preserve the true stack trace.
Fixes https://github.com/mattermost/focalboard/issues/2246

Reduce noise in logs

---

webapp/src/store/contents.ts

This PR adds a null check which was crashing the client after creating a board from certain templates.
fixes https://github.com/mattermost/focalboard/issues/2238

Fixes "Something went wrong" error when selecting certain templates

---

mattermost-plugin/webapp/src/index.tsx
mattermost-plugin/webapp/src/types/mattermost-webapp/index.d.ts
webapp/src/telemetry/telemetryClient.ts

This reverts commit 7e0fb26875d6eaf63b5df22cfd568a313ab9e622.
Reverts code change for adding "Boards" to the Channel Introduction. The mattermost-webapp code did not make the cutoff. 
This only needs reverted in the 'release-0.14' branch. The Main branch is fine as the code now exists in mattermost-webapp.
Fixes https://github.com/mattermost/focalboard/issues/2251

Revert "implement registry for channel intro button (#2181)"

---

webapp/src/components/table/calculation/calculationRow.tsx

A change was made in v0.12 to start using the views "visibleProperties" to define the order of properties. Previously, all views based order on the boards "cardProperties" order.
This PR updates the calculationRows to use the view's "visibleProperties".
Fixes https://github.com/mattermost/focalboard/issues/2257

GH-2257: Calculation column order to be based on view

---

mattermost-plugin/webapp/src/index.tsx

When mattermost is installed on a subdomain (e.g. `mattermost.example.com`), rudder parses the top-level domain and sets their cookies using a general `.example.com` making the cookie available in every subdomain. This PR ensures the cookie is set to the actual subdomain by parsing SiteURL from the config
Same fix on the webapp https://github.com/mattermost/mattermost-webapp/pull/9764
Related to https://mattermost.atlassian.net/browse/MM-36643

[MM-36643] Use Mattermost SiteURL to determine rudder cookie domain

---

.github/workflows/dev-release.yml
.github/workflows/prod-release.yml
README.md

Update GitHub workflows to use macOS 11 and Xcode 13.2.1, to support latest features for Mac.

GitHub: workflows: Use macOS 11 and Xcode 13.2.1

---

mac/Focalboard.xcodeproj/project.pbxproj
mac/Focalboard/DownloadHandler.swift
mac/Focalboard/ViewController.swift

Implement the new (for Big Sur) WKDownloadDelegate to handle downloads. Note that this bumps the macOS requirement to 11.3 (up from 10.14).
#2333

Fix #2333. Handle export in Mac App

---

webapp/src/components/cardDetail/cardDetailProperties.tsx
webapp/src/components/modal.tsx
webapp/src/components/properties/dateRange/dateRange.test.tsx
webapp/src/components/properties/dateRange/dateRange.tsx
webapp/src/components/propertyValueElement.tsx

Usage of property value in key construction leads to unmount/remount for property value component when the value is changed.
This can sometimes cause a [failure in Cypress test](https://github.com/mattermost/focalboard/runs/5097312160?check_suite_focus=true) `cardURLProperty.ts` because the button that was found by Cypress will be detached from DOM after remount of react component.
No linked ticket.

Don't use property value for key construction.

---

.github/workflows/dev-release.yml
.github/workflows/prod-release.yml

Revert to use the Windows 2019 image for GitHub builds for now. Note that `windows-latest` just [changed to Server 2022](https://github.com/actions/virtual-environments/issues/4856), which caused this build break.
#2346

Fix #2346. Revert to Windows 2019 for GitHub actions

---

server/api/api.go
webapp/src/components/content/textElement.tsx

Image Fix -
octoClient image calls have changed, update the API to match the octoClient calls for images.
Text Fix -
Pass BoardID to mutator for BlockTitleChange
Fixes https://github.com/mattermost/focalboard/issues/2356
And

Fix Image and text Elements

---

server/services/store/generators/main.go
server/services/store/generators/transactional_store.go.tmpl
server/services/store/mockstore/mockstore.go
server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/public_methods.go
server/services/store/sqlstore/sqlstore.go
server/services/store/store.go
server/services/store/storetests/blocks.go

We expect to prevent the locking problem detected by some users in the #2300
issue by removing the transactions while using the sqlite database.
Fixes #2300

Removing transactions from sqlite backend

---

server/api/api.go
webapp/src/app.tsx
webapp/src/pages/welcome/welcomePage.tsx
webapp/src/store/users.ts

This fixes for #2430:
* Avoid null ref errors
* Skip Welcome screen for Personal Desktop (single-user)
* No-op on the new config and onboard APIs for single-user mode
#2430

Fix for #2430. Bypass Welcome screen for Personal Desktop.

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

In case a user is not found, at present unreadable and long UUIDs are shown which kill the look and feel of the application. This patch replaces the UUID with a more explanatory string.

Shows "(Deleted User)" instead of UUID when user not found

---

.github/workflows/ci.yml
.github/workflows/dev-release.yml
.github/workflows/prod-release.yml

Running `npm ci` instead of `npm install` essentially verifies dependencies match the intended versions and makes the build fail if they don't match, please see https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci#53325242 and the npm docs for more information.

Replace `npm install` with `npm ci` to ensure dependencies are properly pinned during CI/CD

---

webapp/src/pages/boardPage/boardPage.tsx
webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx

Fix problem with viewId 0 in the URL

---

webapp/src/components/centerPanel.scss

GH-2496 - Updating board title truncation issue
Fixes GH-2496

GH-2496 - Updating board title truncation issue

---

webapp/src/components/properties/dateRange/dateRange.scss

Not sure if this was regression or if it was ever fixed completely earlier. We may have still been displaying "empty" in the cell in which case the issue would not be present. 
The issue now is with empty date range cells. If you fill in a Data Range via the card view, you can edit the date in the table view. However, if there is no cell data the button height is 0px and cannot be clicked. 
This PR sets the button within a data range to have a minimum width, allowing it to be clicked.
Fixes https://github.com/mattermost/focalboard/issues/2258

GH-2258 - set min-height on empty date to allow click

---

server/api/api.go
server/api/archive.go
server/model/user.go
server/swagger/swagger.yml

Fixed broken comments and added missing ones. `make swagger` works again now. A few notes and follow-ups:
* The Swagger documentation is currently incomplete - e.g. output schema of Onboard is missing (as one example)
* The Swagger docs are likely out of date  on main
* I did not check in the large index.html change with this, as we will likely need to update again, and not sure if there's a better alternative to checking in the generated docs.
* What's a better process to keep the API docs in sync?
#2507

Gh 2507 fix make swagger

---

webapp/src/pages/boardPage.tsx

Don't display the workspace if there is no board and it is a read-only view.
The original desired fix was to redirect to the error page. Unfortunately, that wasn't going to work without redesigning the page, as the first time through the board is not yet defined and a redirect causes no boards to display.
Fixes https://github.com/mattermost/focalboard/issues/2457

GH-2257: Don't display template page if readonly and access revoked

---

webapp/src/components/calculations/__snapshots__/options.test.tsx.snap
webapp/src/components/calculations/options.tsx
webapp/src/components/kanban/__snapshots__/kanban.test.tsx.snap
webapp/src/components/kanban/calculation/__snapshots__/calculation.test.tsx.snap
webapp/src/components/kanban/calculation/__snapshots__/calculationOptions.test.tsx.snap
webapp/src/components/kanban/kanban.tsx

Fixed bug with scroll jumping when the card is opened:
- avoid remounting of `ScrollingComponent` for each render of `Kanban` component
- property `autoFocus` set to false for `CalculationOptions` because it triggers `blur` event for the button in Jest tests and closes the menu
- snapshots for tests with `CalculationOptions` updated
Fixes #2396

[GH-2396] Fix scroll jump for kanban board

---

.github/workflows/ci.yml

This is for speed up the tests, I'm not 100% sure if this has other implications. @wiggin77 can you confirm this is correct?.

Run make server-test-sqlite to run only against sqlite for that part of the job

---

server/model/board.go

Maintain the order of existing card properties on a patch. The order is used for display.
#2589

Fix #2589. Maintain cardProperty order on patch

---

server/integrationtests/board_test.go
server/services/permissions/localpermissions/localpermissions.go
server/services/store/sqlstore/util.go

The `cache=shared` pragma required by in-memory sqlite database creates more opportunity for database locked errors.  Adding a 5 second wait/timeout helped but still resulted in flaky results.  Moving back to a file based unit test is safer since each test gets a completely new instance and is impervious to the timing of the previous close within the driver.
I'm hoping the memory caching that sqlite does, and the fact unit tests create very small databases, and the parallelization of the unit tests will result in CI jobs that are not much slower.  **Update: just under 2 minutes was added to CI job.**
The temporary database file is cleaned up on test teardown.
NONE

Revert in-memory unit tests for sqlite

---

server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql

To maintain access contron on templates, we need to add entries into `board_members` table during the migration from workspace to teams. Currently, it was not being done for templates. This PR removes that condition and allows adding board memberships for templates. A later PR that will fix the entire issue in #2370 will need this work as a base.
Completes data migration part of https://github.com/mattermost/focalboard/issues/2370, not the whole issue.

Updated SQL migration to insert board memberships for templates

---

server/api/api.go

Allow `handleServeFile` to accept a readToken.
Allows read-only SharedBoards anon user to view images
Fixes https://github.com/mattermost/focalboard/issues/2678

GH-2678 Update handleServeFile to allow readtoken

---

server/app/boards.go
server/app/subscriptions.go
server/services/notify/notifysubscriptions/subscriptions_backend.go
server/services/notify/service.go
webapp/src/octoClient.ts
webapp/src/pages/boardPage/websocketConnection.tsx
webapp/src/wsclient.ts

This PR fixes the Follow button which was broken during the Permissions branch merge and refactor of boards page.
- websocket events for subscription changes were not being sent
- webapp was filtering out websocket events based on undefined teamID.
fixes https://github.com/mattermost/focalboard/issues/2443

GH-2443  - Fix broken Follow button

---

webapp/cypress/integration/loginActions.ts
webapp/src/pages/errorPage.tsx

This PR ensure the error page is not displayed for personal server or desktop when not logged in.  User is redirected to the login page instead.
fixes https://github.com/mattermost/focalboard/issues/2534

GH-2534: Don't show error page for Personal Server when not logged in

---

server/api/api.go

Removes the ability to use a read token from `handleDuplicateBoard` and `handleDuplicateBlock`
Fixes https://github.com/mattermost/focalboard/issues/2668

GH-2668: Remove read token check from unnecessary functions

---

server/api/api.go
server/api/archive.go
server/api/auth.go

Returns a 501 for those apis that should not be called when running as a plugin.
Fixes https://github.com/mattermost/focalboard/issues/2667
Fixes https://mattermost.atlassian.net/browse/MM-40553

GH-2667: Update apis to return 501 if not available for plugin

---

server/api/api.go
server/app/onboarding.go
server/app/templates.go
server/app/templates_test.go
server/model/user.go

Permission Checks for teamID = '0' fails for non admin users. 
When retrieving GlobalTemplates, don't check team permissions.
Fixes https://github.com/mattermost/focalboard/issues/2712

GH-2712:Don't check team permission for GlobalTeamID

---

server/services/notify/notifymentions/mentions_backend.go

When a `@` appeared in card text followed by something other than a username, an attempt was made to subscribe the non-user to the card.  This resulted in a warning emitted to the logs.  This PR corrects that.   e.g. a default template includes the phrase `to @mention teammates`
NONE

Don't warn when  appears in card followed by text that is not a username

---

Makefile
server/app/blocks.go
server/app/templates.go
server/integrationtests/board_test.go
server/integrationtests/permissions_test.go
server/model/user.go
server/server/server.go
server/services/notify/notifymentions/mentions_backend.go
server/services/store/sqlstore/templates.go
server/utils/debug.go

This PR speeds up unit testing (and integration testing) by selectively initializing default templates only for tests that need them.  Some log noise is also removed.
CI went from ~30 minutes to 14 minutes.
fixes https://github.com/mattermost/focalboard/issues/2745

GH-2745  Don't init default templates when unit testing

---

server/ws/server.go
server/ws/server_test.go

The websockets implementation was using the wrong single user ID when deciding if a user was subscribed to a team, hence not sending the corresponding team updates to the interface.
https://github.com/mattermost/focalboard/issues/2731

Use the right single user ID on the WS implementation

---

server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql

SQLite was not setting a default value on migrated templates for their version, causing the scanner to fail when getting `NULL`s for integer values.
Fixes #2736

Add coalesce to template version migration

---

.vscode/launch.json
Makefile
mac/README.md
win-wpf/README.md

Added a readme with tips on debugging the Mac and Windows app, plus running the server in single-user mode.
Also added a `Go: Launch Single-user Server` option to VSCode's launch.json.

Add readme for Mac and Win apps

---

server/services/store/sqlstore/migrations/000018_populate_categories.up.sql
server/services/store/sqlstore/migrations/000019_populate_category_blocks.up.sql

Fixes #2773
@sbishel @wiggin77 This is the quickest and cleanest fix IMO. The data migration anyways updates the IDs to our standard UUID format, so it doesn't really matter what we use in the SQL migration as long as its a varchar.
Tested on both MySQL v5.7 and v8.

Avoided using UUID() as function param for MySQL migration

---

webapp/src/octoClient.ts

Prior to permissions release, the `api/v1` was not included in the file upload path. This was fixed in the permission branch, but the octoclient was never updated. This PR updates the octoclient to include that in the path.
Fixes https://github.com/mattermost/focalboard/issues/2759

GH-2759 - fix path to file api

---

server/client/client.go
server/integrationtests/clienttestlib.go
server/integrationtests/export_test.go
webapp/src/csvExporter.ts

This PR fixes a bug where `#` in a block title breaks export to CSV.  The issue is that CSV export is done client side, and the technique used is to stuff the CSV contents into a data URL.  The data URL cannot contain `#` because that is a special character that ends the path (or in this case data) portion of the URL.  Everything after that gets truncated.
**BONUS:**  added an export archive unit test.
fixes https://github.com/mattermost/focalboard/issues/2744

GH-2744 Fix export with hash sign (#) in block title breaks export to CSV

---

server/api/archive.go
webapp/src/components/globalHeader/__snapshots__/globalHeaderSettingsMenu.test.tsx.snap
webapp/src/components/globalHeader/globalHeaderSettingsMenu.tsx

Follow up to https://github.com/mattermost/focalboard/pull/2776 to remove the export archive option from plugin mode. A redundant check on the API has been removed as well as cleanup.
Related to https://github.com/mattermost/focalboard/issues/2672
Fixes https://github.com/mattermost/focalboard/issues/2780

Remove export archive from plugin header

---

webapp/src/components/cardDialog.tsx
webapp/src/components/gallery/gallery.test.tsx
webapp/src/components/gallery/galleryCard.test.tsx
webapp/src/components/gallery/galleryCard.tsx
webapp/src/components/kanban/kanbanCard.tsx

Hides instances of the `Copy link` button for `single-user` installs e.g. Personal Desktop.
closes #2337

fix: hide 'Copy link' for `single-user` installs

---

webapp/cypress/integration/createBoard.ts
webapp/src/components/markdownEditorInput/markdownEditorInput.tsx

I fixed the issue that the title is not focused when a card is created.
It seems that `markdownEditorInput` used in `CardDetatilContents` triggered a problem.
`onChange` event from `Editor` component is triggered even when the component is mounted.
It re-renders the component, so the `title` component loses the focus.
I added a guard to `onEditorStateChange` function, so the logic will not be executed when an old state is equal to a new state. 
I added a cypress test to check if it works.
https://user-images.githubusercontent.com/59413880/163104968-60f84558-a694-4fc6-9b42-76cd886ba4e0.mov
Closes #2575

GH2575 - Focus title when card is created

---

experiments/webext/src/utils/networking.ts
server/admin-scripts/reset-password.sh
server/api/api.go
server/api/archive.go
server/api/auth.go
server/client/client.go
server/main/doc.go
server/swagger/README.md
server/swagger/docs/html/index.html
server/swagger/swagger.yml
webapp/cypress/support/api_commands.ts
webapp/src/octoClient.ts
website/site/content/guide/admin/_index.md

Migrates all api endpoints from the `v1` to the `v2` namespace. The PR updates the swagger comments as well, as we were generating bad URLs from them, having them prefixed with `/api/v1` (see [doc.go](https://github.com/mattermost/focalboard/blob/5afa8699e1780c5a79c359b4588a291b0234018d/server/main/doc.go#L7)) and then the comment on each endpoint would be prefixed as well, generating URLs and examples in the resulting docs starting with `/api/v2/api/v2/...`.
Closes https://github.com/mattermost/focalboard/issues/2754

Update focalboard endpoints to v2 namespace

---

mattermost-plugin/server/notifications.go
mattermost-plugin/server/plugin.go
server/app/blocks.go
server/app/boards.go
server/services/notify/notifymentions/delivery.go
server/services/notify/notifymentions/mentions_backend.go
server/services/notify/notifymentions/store.go
server/services/notify/notifysubscriptions/store.go
server/services/notify/notifysubscriptions/subscriptions_backend.go
server/services/notify/plugindelivery/mention_deliver.go
server/services/notify/plugindelivery/plugin_delivery.go
server/services/notify/plugindelivery/user.go
server/services/notify/plugindelivery/user_test.go
server/services/notify/service.go
server/utils/callbackqueue.go

This PR implements [permissions spec](https://docs.google.com/document/d/1HOnoB87WZojqplpB6XGbtKsLuqjG8h-8CbJpmWsRfM4/edit#bookmark=id.7k6tbu6a6odp) for mentions.
- public boards: admin, editor, commenter can mention team members and auto-add them to board; guests can mention board members
- private boards:  admin, editor, commenter, guest can mention board members
- viewers cannot mention
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/150d1464-6d59-4c39-810f-ee201439dbaf/ciu68wqtbp3nuxnrt9o6db86htr

Implement permissions specs for mentions.

---

mattermost-plugin/server/plugin.go

A previous [PR](https://github.com/mattermost/focalboard/pull/2758) changed the Plugin config field `ServerRoot` to drop the `/plugins/focalboard` path.  This broke public shared board links.  This PR reverts that change.
fixes https://github.com/mattermost/focalboard/issues/2789

revert ServerRoot path change

---

webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.test.tsx
webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx

This PR ensures that permissions are respected in the template selector when displaying Delete and Edit icons for a template.
fixes https://github.com/mattermost/focalboard/issues/2812
fixes https://github.com/mattermost/focalboard/issues/2803

GH-2812 Hide delete template and edit template icons unless user has permission

---

server/services/store/sqlstore/boards_and_blocks.go

Currently all boards created from public templates are public (because the templates are public). This PR updates the duplication logic to set boards created from a template to private boards.
Fixes https://github.com/mattermost/focalboard/issues/2798

GH-2798 - make board private when created from template

---

server/services/store/sqlstore/boards_and_blocks.go
webapp/src/components/calendar/fullcalendar.scss

The `+ more` button when displayed on "today" was displaying as transparent, because `fs-today` was taking presidence over `fs-popup`.
Rather than setting as transparent, unset the background for the grid component today. Leaving `fs-popup fs-today` unchanged.
Fixes https://github.com/mattermost/focalboard/issues/1871

GH-1871 fix background for today

---

server/api/api.go
server/integrationtests/sharing_test.go
webapp/src/components/shareBoard/shareBoard.test.tsx
webapp/src/components/shareBoard/shareBoard.tsx

When displaying shared board menu, check if user has permissions before calling API. Otherwise, API logs error and return error unnecessarily. 
If "sharing" is not found. That is an expected case and no reason to log error.
https://github.com/mattermost/focalboard/issues/2808

GH-2808: fix some logging issues with share board.

---

mattermost-plugin/webapp/src/index.tsx
webapp/src/pages/boardPage/boardPage.tsx

Fixes setting the following button on a card. Currently if going directly to a card via a URL the following information is not loaded.
In addition in order to duplicate the issue, I had to provide a fix where if going directly to the card via a URL, you were automatically redirected to the team.
Fixes https://github.com/mattermost/focalboard/issues/2815
Fixes https://github.com/mattermost/focalboard/issues/2783

GH-2815 fix for following button on card

---

server/api/api.go
server/app/boards.go
server/services/store/mockstore/mockstore.go
server/services/store/sqlstore/public_methods.go
server/services/store/store.go
server/services/store/storetests/boards.go

Fixed some instances of search board method being called with extra params

Removed teamID from search API

---

Makefile
mattermost-plugin/server/configuration_test.go
mattermost-plugin/server/plugin_test.go
server/api/api.go
server/integrationtests/clienttestlib.go

This PR enables unit testing for plugin when running locally via `make server-test` or CI.  Also fixes broken unit tests.
NONE

Include plugin unit tests in CI via makefile; fix unit tests

---

server/app/app.go
server/app/boards.go

This PR fixes an issue where authors are not auto-subscribed to cards when duplicating boards (from template or regular board).
This PR also ensures that boards app APIs use the same notifications thread pool as blocks.
fixes https://github.com/mattermost/focalboard/issues/2895

GH-2895  Call notification engine when duplicating boards

---

server/services/notify/notifymentions/mentions_backend.go

Logs were getting extra errors when mentioning users on private boards that did not have permission to receive them.  This PR reduces those to a debug level.
Old
```
error [2022-04-22 12:20:07.702 -04:00] Error delivering notification                 caller="app/plugin_api.go:940" plugin_id=focalboard backend=notifyMentions action=add block_id=a1btjsijhztggdq8rugi167zyhr error=""MError:
cannot deliver notification for @bart: e43dfcnrbbrm8r4oyeu7h9uj1y cannot mention non-board member idrt3zccs3gqpec94wt9fagzdw : mention not permitted
1 errors total.
```
New
```
debug [2022-04-22 13:12:14.885 -04:00] Cannot deliver notification                   caller="app/plugin_api.go:934" plugin_id=focalboard user=bart error=""e43dfcnrbbrm8r4oyeu7h9uj1y cannot mention non-board member …
```

Reduce log level when delivering notifications with permissions error

---

mattermost-plugin/webapp/src/index.tsx

Fixes #2027
On the Mattermost desktop app, navigation in boards doesn't work if you are on a subpath. This PR, along with fixes in the latest unreleased desktop app fixes this issue.
To test this, you need to install the desktop app from the `master` branch, or download the latest nightly from [Desktop Builds](https://community-daily.mattermost.com/core/channels/desktop-builds) channel.
Thanks a ton, @devinbinnie for looking into this 🙌

Fixed a bug preventing any navigation in Mattermost desktop with subpath

---

server/api/api.go

An update was made to reduce logging, so when a Sharing object isn't found, an empty object is returned rather than an error. However, the code that creates the token is dependent on the Sharing object being `undefined`, not an empty object.
This PR updates the return to return nothing, instead of an empty object, so the Sharing object is `undefined`.
Fixes https://github.com/mattermost/focalboard/issues/2894

GH-2894- Fix missing readonly token

---

server/ws/plugin_adapter.go
server/ws/plugin_adapter_test.go

The plugin WS server now checks for team access when getting the users connected and subscribed to a team or a board to filter out possible connections whose users are not members of the team anymore but have a subscribed listener.
Fixes https://github.com/mattermost/focalboard/issues/2671

Add membership check when getting team listeners

---

server/services/store/sqlstore/board.go
server/services/store/sqlstore/sqlstore.go
server/services/store/sqlstore/util.go

This PR sets a flag on the store marking if it has the `binary_parameters` set and creates a utility function that should be used to marshal the contents of the `jsonb` fields and will append the `0x01` byte to them if required as per the spec.
As a follow up, I will abstract these methods in the server code and import them directly to avoid code repetition.
Fixes https://github.com/mattermost/focalboard/issues/2850

Handle jsonb fields on postgres with binary_parameters set

---

webapp/src/errors.ts
webapp/src/store/initialLoad.ts

If a read-only token is invalid, an unauthorized user is left on the "Create Board" screen. This PR creates and handles an error when a read-only board is not returned. (ie. an invalid read-only token). 
Fixes https://github.com/mattermost/focalboard/issues/2896

GH-2896 - Error on invalid token

---

linux/main.go
server/integrationtests/clienttestlib.go
server/main/main.go
server/server/server.go
server/services/store/sqlstore/migrate.go
server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql
server/services/store/sqlstore/params.go
server/services/store/sqlstore/sqlstore.go

This PR initialises the store with a `singleUser` parameter that is in the end passed to the migrations. It also modifies the board members initial migration to operate differently if running in single user mode.
Fixes https://github.com/mattermost/focalboard/issues/2876

Initialise the store with a single user flag and pass it to the migrations

---

webapp/src/blocks/board.ts
webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
webapp/src/components/__snapshots__/workspace.test.tsx.snap
webapp/src/components/centerPanel.tsx
webapp/src/components/shareBoard/__snapshots__/shareBoardButton.test.tsx.snap
webapp/src/components/shareBoard/shareBoardButton.test.tsx
webapp/src/components/shareBoard/shareBoardButton.tsx

The share button should rotate icons between the globe and lock if the board is Private or Open. This PR implements that functionality. Prior to this, only the Globe icon was ever shown.
Fixes https://github.com/mattermost/focalboard/issues/2872

GH-2872 - Implement private icon on Share button

---

server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql

This PR adds a migration to take boards that come from either group channels or direct message channels and make them private boards.
Fixes https://github.com/mattermost/focalboard/issues/2923

Add migration to ensure all boards are either open or private

---

server/services/store/sqlstore/data_migrations.go
server/services/store/sqlstore/migrate.go
server/services/store/sqlstore/migrations/000017_add_teams_and_boards.up.sql

The teamless boards data migration was relying on boards of type `D` and `G`, that were removed as part of https://github.com/mattermost/focalboard/pull/2928. This PR reverts said patch, fixes the query that fetches teamless boards and cleans a bit the data migration code, moving the migration itself to the `data_migrations.go` file and ensuring migration and schema version keys are consistently named and placed.
The actual fix for the teamless data migration in MySQL is https://github.com/mattermost/focalboard/pull/2942/commits/5c5a2bb8988cb7b781ec39754352d87482682db5
Fixes https://github.com/mattermost/focalboard/issues/2941

Move teamless data migration with the rest of data migrations and update teamless boards query

---

webapp/src/components/sidebar/__snapshots__/registrationLink.test.tsx.snap
webapp/src/components/sidebar/registrationLink.test.tsx
webapp/src/components/sidebar/registrationLink.tsx

The Personal Server 'invite users' URL wasn't showing the base URL, just the `/register?t=xxx`. It looks like there was a change during the permissions branch that updated the behavior of `Utils.buildURL` to return _only_ the `path` argument if it's _not_ a plugin instance, even if the `absolute` arg is present. I followed the existing conventions to use the builtin `URL` type + constructor to create a properly formatted URL string.
closes #2898

fix: personal server invite link omitted base URL

---

server/services/store/sqlstore/migrate.go

This PR reuses the server mechanism to remove the MySQL timeout from the connection string to bypass timeouts when running migrations.
A couple of follow up PRs will come later making the server method public for it to be used in Focalboard instead of duplicating the implementation.
Fixes https://github.com/mattermost/focalboard/issues/2946

Remove timeout from MySQL migrations

---

webapp/cypress/integration/createBoard.ts
webapp/src/components/centerPanel.scss
webapp/src/components/iconSelector.scss
webapp/src/components/shareBoard/shareBoardButton.scss
webapp/src/components/shareBoard/shareBoardLoginButton.scss
webapp/src/components/topBar.scss
webapp/src/components/viewHeader/viewHeader.scss
webapp/src/components/viewTitle.scss
webapp/src/components/viewTitle.tsx
webapp/src/styles/_typography.scss
webapp/src/widgets/buttons/button.scss

GH-2927 - Reducing header size for boards
Fixes #2927

GH-2927 - Reducing header size for boards

---

webapp/src/store/cards.ts

Some older cards may have Select property set to null. Newer cards have the property removed rather than its value set to null. Add a check for the propertyValue being null.
Fixes https://github.com/mattermost/focalboard/issues/2970

GH-2970 - Check for propertyValue not null

---

webapp/src/pages/boardPage/websocketConnection.tsx

When following/unfollowing card, the subscriber id is compared to me?id. However, we weren't rebuilding that function after me.id gets set.
Fixes https://github.com/mattermost/focalboard/issues/2995

GH-2995- Fix for following

---

mattermost-plugin/server/manifest.go
webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx

Fixes #2945
1. The issue wasn't just with other users but with your own use as well once you start switching between teams.
2. The issue occurs when you delete the last viewed board of a team, or the first board in the first category (in order of appearance in the sidebar).

Fixed incorrect navigation bug

---

server/services/store/sqlstore/boards_and_blocks.go

When duplicating a board, a "copy" suffix should be added. Followed the same logic as is v0.15.  So when a template is created from a board the title is changed to "New board template".
As we do not have server localization yet. These are unlocalized.  However, they were in the release-0.15 code as well.
https://github.com/mattermost/focalboard/blob/release-0.15/webapp/src/mutator.ts#L793
Fixes https://github.com/mattermost/focalboard/issues/2978

GH- 2987 - Add "copy" to board title when duplicated

---

webapp/src/components/cardDialog.tsx
webapp/src/store/boards.ts

Fixes #2886
The issue was that we were adding new board members to the store who weren't part of the previous board, but not removing old users, who aren't part of the new board.

Displayed only board members in autocomplete

---

mattermost-plugin/plugin.json
mattermost-plugin/server/manifest.go

Update plugin.json to have updated `min_server-version`. Then ran build to ensure manifest.go got updated.

update min version in Plugin and build

---

mattermost-plugin/server/notifications.go
server/services/notify/notifysubscriptions/delivery.go
server/services/notify/notifysubscriptions/notifier.go
server/services/notify/plugindelivery/mention_deliver.go
server/services/notify/plugindelivery/plugin_delivery.go
server/services/notify/plugindelivery/subscription_deliver.go
server/services/notify/plugindelivery/user_test.go

There have been reports of notifications not being delivered due to an error message suggesting that the user and bot do not share a common team.  This is required to open a direct channel.  This PR ensures the bot is added to the team.
I reviewed how Playbooks handles this since they do not seem to have any issues with bots generating channel messages.  Playbooks adds the bot to the team and channel every time a playbook is created, regardless of whether the bot is already a member.  This PR emulates that by adding the bot to the team every time a notification batch is to be sent.
Some potential issues that this addresses:
- team is created after the plugin `OnActivate` 
- `EnsureBot` is called during `OnActivate` but only adds the bot to one of several teams
Possibly addresses …

GH-2469 Add board-bot to team

---

Makefile
mattermost-plugin/Makefile
server/services/store/sqlstore/util.go
server/utils/debug.go
server/web/webserver.go

This PR standardizes the environment variables so they are always prefixed with `FOCALBOARD_`.
This PR does **not** extract the env vars into a const file since all but two vars are via Viper's config file overrides or are simply defined and used by the makefile.
https://community.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/150d1464-6d59-4c39-810f-ee201439dbaf/c8erwyx3h37bxxkh31bozt1iyfc

Standardize env variable naming

---

.gitignore
mattermost-plugin/server/notifications.go
server/services/notify/notifymentions/mentions_backend.go
server/services/notify/notifysubscriptions/delivery.go
server/services/notify/notifysubscriptions/notifier.go
server/services/notify/notifysubscriptions/subscriptions_backend.go
server/services/notify/plugindelivery/mention_deliver.go
server/services/notify/plugindelivery/plugin_delivery.go
server/services/notify/plugindelivery/subscription_deliver.go
server/services/notify/plugindelivery/user_test.go

This PR backports several fixes for the notifications service.
- ensure Bot is member of team (https://github.com/mattermost/focalboard/commit/1ff28087f8fb03d5abcb2d5184ded8e70cfc60e3)
- Don't warn when `@` appears in card followed by text that is not a username (https://github.com/mattermost/focalboard/commit/68b623ff29d533afcf8b8c4be4d82a3e986c8976)
- fix panic when creating new card in notifysubscriptions (https://github.com/mattermost/focalboard/commit/ba71ecd43ba061d255de347b5e57e48f583323e3)
**NOTE** some code was added to fetch teamIDs that does not appear in `main` nor .015
fixes https://github.com/mattermost/focalboard/issues/3039

GH-3039 - Backport notify fixes

---

server/app/templates.go

Removes one view from the Roadmap Template.
You can see the change in the [PR for main](https://github.com/mattermost/focalboard/pull/3080), as it builds it from JSON.
Fixes https://github.com/mattermost/focalboard/issues/3053

Update templates 7.0

---

webapp/src/components/__snapshots__/cardDialog.test.tsx.snap
webapp/src/components/__snapshots__/confirmationDialogBox.test.tsx.snap
webapp/src/components/__snapshots__/dialog.test.tsx.snap
webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelectorItem.test.tsx.snap
webapp/src/components/dialog.scss
webapp/src/components/dialog.tsx
webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap

If I drag a component in `Dialog` and release the mouse outside of `Dialog`, `Dialog` closes.
It's because the logic that checks `e.target` and `e.currentTarget` is executed when `mouse up` is triggered. ('click' event includes `mouse down` and `mouse up`).
I added `onMouseDown` event, so `isBackdropClicked` is decided when we `mouse down` .
When we `click`(`mouse up`),  `prop.onClose` is executed if `isBackdropClickedRef.current` is true.
https://user-images.githubusercontent.com/59413880/163673465-fcf29b8a-4c13-42ef-9514-4577392023d5.mov
https://user-images.githubusercontent.com/59413880/163673518-4fc2d648-bd20-4cee-9769-0a7643e3b784.mov
Fixes #1919

GH-1919 fix unexpected dialog close

---

webapp/package.json

Adds a script to the `webapp/package.json` file to simplify the process of starting up the server and opening Cypress in interactive mode for debugging purposes.
If a developer wants to run a Cypress test in interactive mode, they can just execute the following command:
`cd webapp && npm run cypress:debug`

Add cypress:debug script to webapp/package.json

---

webapp/src/components/table/table.tsx

Dragging a card from one group to anther and then dragging back to the original group did now work because OnDropToCard did not get updated when cards collection changed. Therefore is was using the old collection and thus had its group to original group. 
Fixes https://github.com/mattermost/focalboard/issues/2992

GH-2992 - Drag drop card to groups doesn't work

---

server/services/store/sqlstore/board.go
server/services/store/sqlstore/data_migrations.go
server/services/store/sqlstore/legacy_blocks.go

Fixed a bug where migrations didn't run on a clean DB

---

server/swagger/README.md

Add an example of how to login and auth to the API docs.
#3072

Fix #3072. Add docs on how to auth to API readme.

---

server/api/api.go
server/app/app.go
server/app/blocks.go
server/app/blocks_test.go
server/app/cloud.go
server/app/cloud_test.go
server/client/client.go
server/model/block.go

This PR checks if cloud limits should apply before accepting patch requests, and rejects them if they refer to a card that is limited

Forbid updating limited cards

---

server/services/store/sqlstore/blocks.go
server/services/store/storetests/blocks.go

This PR prevents the API from fetching blocks that belong to deleted boards
Fixes https://github.com/mattermost/focalboard/issues/3134

Don't fetch blocks that belong to deleted boards

---

webapp/src/components/viewMenu.test.tsx
webapp/src/components/viewMenu.tsx

When duplicating a view, the cloud limits should be checked. Just as when adding a view.
Fixes https://github.com/mattermost/focalboard/issues/3116

GH 3116 Check cloud limits when duplicating view

---

webapp/cypress/integration/createBoard.ts
webapp/src/mutator.ts

Custom templates created from global templates are now able to be edited/deleted in the UI.
Fixes #3061 
https://user-images.githubusercontent.com/6335792/170309728-685a5b18-a137-4386-9751-efafdd318835.mov

fix(webapp): template from global is modifiable

---

webapp/src/components/messages/cloudMessage.tsx

If accessing a read-only board with a logged in user, the cloud message appears. Needed to add a check for `isFocalboardLegacy()` path. Since the user may be logged in and read-only boards don't return as plugins. 
Fixes https://github.com/mattermost/focalboard/issues/3135

GH-3135 ReadOnly banner fix

---

webapp/src/components/properties/user/user.tsx

Filters out bots for displaying the enumerable `options` in the `Person` property value selector.
Fixes #3144

fix: filter bots in person property select

---

webapp/src/components/table/tableRow.scss

Deletes the `.action-cell` CSS `background-color` to allow for a proper cascade—previously a UI regression.
Closes #3081.

fix: delete `.action-cell` CSS bg color

---

.gitattributes

Git attributes for ignoring `website` and `swagger docs` in linguist added.
Currently this repo page shows this distribution of the languages:
which is a bit misleading because of auto generated documentation.
With the proposed changes it looks like this:

Git attributes for linguist

---

webapp/src/components/centerPanel.tsx
webapp/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
webapp/src/components/messages/cloudMessage.test.tsx
webapp/src/components/messages/cloudMessage.tsx
webapp/src/store/users.ts
webapp/src/userSettings.ts

Fixes two issues - Personal server was not storing setting for hiding the cloud message, so the message never went away and the "Share" button was also being displayed.
Fixes https://github.com/mattermost/focalboard/issues/3217
Fixes https://github.com/mattermost/focalboard/issues/3216

Personal server fixes for cloud message

---

webapp/src/components/workspace.tsx

Fix flickering when switching views: use redux state for rendering instead of the router match params.
Fixes #3211

[GH-3211] Fix switching of views

---

webapp/src/components/messages/__snapshots__/cloudMessage.test.tsx.snap
webapp/src/components/messages/cloudMessage.test.tsx
webapp/src/components/messages/cloudMessage.tsx
webapp/src/store/users.ts
webapp/src/userSettings.ts

Fixes two issues - Personal server was not storing setting for hiding the cloud message, so the message never went away and the "Share" button was also being displayed.
Forward port of https://github.com/mattermost/focalboard/pull/3227
Fixes https://github.com/mattermost/focalboard/issues/3217
Fixes https://github.com/mattermost/focalboard/issues/3216

fixes for personal server app notification (#3227)

---

webapp/src/route.tsx

Adds a check to see if the clientConfig object is null or empty.
If null or empty clientConfig then sets the disableTour to false.
Related Issue: #3236
Signed-off by: imasdekar <imasdekar@disroot.org>

fix: handles null or empty clientConfig

---

server/integrationtests/boards_and_blocks_test.go
server/model/boards_and_blocks.go
server/model/boards_and_blocks_test.go

When trying to delete a new property with no values, an error is thrown because there are no blocks to patch only a board. Remove the check for blocks length > 0
Fixes https://github.com/mattermost/focalboard/issues/3050

GH-3050 - Fix deleting empty property

---

webapp/src/components/onboardingTour/tourTipRenderer/tourTipRenderer.tsx

Adds a check to see if the clientConfig object is null or empty.
If null or empty clientConfig then sets the disableTour to false.
Fixes: #3259
Signed-off by: imasdekar <imasdekar@disroot.org>

fix: handles clientConfig causing board error

---

README.md

- Updates the readme to add instructions for running the prebuild step for standalone desktop app dev setup
Related Issue: #3221
Signed-off by: imasdekar <imasdekar@disroot.org>

update: instructions for prebuild for dev setup

---

Makefile

Disabled `-race` test for Sqline for all OS as race tests are running fine on MySQL and Postgres even on Windows.
This is only a WIndows + Sqlite issue.
Fixes #3281

Disabled Race Test for SQLite

---

Makefile

Added an `FB_PROD` flag to build the server for x86 on Mac for production. This will support both Apple Silicon (M1, M2, etc.) and legacy x86 Macs.
#3277

Gh3277 x86 mac prod build

---

server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql

- Fixes an issue with migrations for v7.2 on Community clone.
- On community, some boards don't have a `description` field in their json properties. This PR adds a `COALESCE` around the descriptions during migrations.
Partially fixes -
https://github.com/mattermost/focalboard/issues/2994

add coalesce around boards description

---

webapp/cypress/integration/cardURLProperty.ts

Fix Cypress test `cardURLProperty`:
- during the creation of a new board view and switching to it there are many API requests executed in effects for `BoardPage` component
- some requests trigger additional rerendering of the `BoardPage` component
- Cypress starts to work with the `BoardPage` immediately when on its first render
- additional rerenders after requests can lead to remount of some components related to menu
- so in order to workaround the issue waiting for the last request (which is `getUser`) was introduced in the Cypress test
- after this last request `BoardPage` component doesn't have additional rerenders and Cypress should not have issues with detached elements 
Fixes #3318

[GH-3318] Fix flaky cypress test

---

server/model/block.go

Added BoardID to limited card in order for getCurrentBoardHiddenCardsCount() to work.
Without fix, cards are hidden, but HiddenCard Count button and modal were not displayed.

Cloud Limit Fix - add BoardID to limited card

---

webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
webapp/src/components/sidebar/sidebarBoardItem.scss
webapp/src/components/sidebar/sidebarBoardItem.test.tsx
webapp/src/components/sidebar/sidebarBoardItem.tsx

Fixes LHS board title alignment by rendering a default (`<BoardIcon>`) icon if there is not a custom one set.
closes #2958

fix: render default LHS board icon

---

mattermost-plugin/server/data_retention_test.go
server/app/blocks_test.go
server/app/files_test.go
server/app/helper_test.go
server/app/teams_test.go
server/auth/auth_test.go

This PR removes all calls to `mockController.Finish()` avoiding redundant calls and early finishes, that were causing test expectations not to be checked. It includes as well the fixes for the failing tests
https://community-daily.mattermost.com/boards/workspace/qgsck6cts3fwpqwyjiupjm5cde/b4ctmm917q3rzdfi451qtuxjzcw/v4mi5d7u6afbhfrks5783gbmj9o/ce11bfa5yjib63ck8iu8hgrkmdr

Fix mock early finish issue on test helpers

---

webapp/src/components/shareBoard/shareBoard.scss

Allows the user list on the share dialog to overflow outside of the modal bounds—particularly useful when sharing templates as there's less content inside the modal already.
closes #2950

fix: share modal user list overflow out of dialog

---

server/services/store/sqlstore/migrate.go

This PR updates the ID of the lock that boards uses at migration time so it's different from the one Mattermost uses

Updates the id of the migration lock

---

server/services/store/sqlstore/data_migrations.go

This PR uses optimizes the category migration to use `.Exec` on update queries instead of `.Query`, as we're not expecting any data in return

Replace query with exec on database update queries

---

server/services/store/sqlstore/data_migrations.go
server/services/store/sqlstore/migrations/000019_populate_categories.up.sql
server/services/store/sqlstore/migrations/000020_populate_category_blocks.up.sql

This PR replaces the approach of creating the categories and category boards on a migration and updating their IDs on a data migration with one that directly generates that data in a data migration. This new approach inserts the data in batches of 1000 values at a time, which combined with the speed of the inserts makes the whole migration way faster.

Move category creation and UUID update to a more performant data migration

---

.github/workflows/lint-server.yml
mattermost-plugin/build/gowork/main.go
mattermost-plugin/product/api_adapter.go

Make changes to the adapter WRT https://github.com/mattermost/mattermost-server/pull/20674

Update product adapter for changes in the UserService

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

Cherry pick of #3378 on release-7.2.
```release-note
NONE
```
Manually cherry picked because it was dependent on https://github.com/mattermost/focalboard/pull/3381, which will not be cherry picked.
Simply needed the import statement.

Manual cherry pick of #3378

---

server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql

The boards creators weren't added as administrators of the boards during the
migration (only the admin administrators), but this PR adds also the creator as
a new admin.
This is done only if the user is still a member of the channel, keeping this
way the original behavior of boards (In 7.1 if you leave the channel, doesn't
matter if you were the creator, you are no longer member of the board).

Add the creator of the board as a administrator of the board if it still belongs to the channel

---

website/site/content/guide/admin/_index.md

By default, the feature to share a board as view-only to the public as shown [in the user guide](https://www.focalboard.com/guide/user/#sharing-boards) is disabled. In order to enable it, the `enablePublicSharedBoards` property needs to be set to `true` in `config.json`. However, this property isn't documented in the Administrator's Guide. 
A previous issue (https://github.com/mattermost/focalboard/issues/1419) suggested this addition; I don't believe it was ever done, so here it is!

Add enablePublicSharedBoards to admin guide

---

webapp/src/pages/boardPage/boardPage.tsx

Resets `useWebSockets` when me changes.
Fixes https://github.com/mattermost/focalboard/issues/3463

reset when me changes

---

.github/CODEOWNERS

This PR removes the contents of the CODEOWNERS file so that the `Core Focalboard` group is not auto-assigned as reviewer on every PR.
NONE

Remove contents of CODEOWNERS file

---

webapp/src/wsclient.ts

This PR replaces the old `mattermost-webapp` lifecycle hooks with the new ones, allowing for both clients to be active at the same time without causing any problems to each other.
There is no need to unregister the listeners because with the `WithWebSockets` components we control that the websocket singleton only gets initialized once, and the `close` function never gets called.
As a follow up, we will have to update the minimum required version (https://github.com/mattermost/focalboard/issues/3484)

Update websocket client to use the new websocket lifecycle hooks

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

UserList query was failing because the query was not using the alias in the JOIN clause.

Update query to use alias

---

webapp/src/components/sidebar/__snapshots__/sidebarBoardItem.test.tsx.snap
webapp/src/components/sidebar/sidebarBoardItem.scss
webapp/src/components/sidebar/sidebarBoardItem.tsx

Updating the default boards icon from the board view icon to the boards official ion.
Fixes #3461 
Decided to keep the icon white to be consistent with channels.

GH-3461 - Updating boards default icon

---

server/api/api.go

This PR addresses a panic that happened on community instance during shutdown as reported by SRE.  While plugins were shutting down, as part of server shutdown, a `TeamBoardsInsights` call was received.  The insights call failed, which routes to an `errorResponse` call.  The `errorResponse` tried to write to a response that was already dead, which caused a panic.
Team insights call:
```
{"timestamp":"2022-08-02 07:06:43.608 Z","level":"debug","msg":"github.com/mattermost/focalboard/server/api.(*API).handleTeamBoardsInsights(0xc0005fe400, 0x1464408, 0xc000b5fa90, 0xc000789c00)","plugin_id":"focalboard"}
{"timestamp":"2022-08-02 07:06:43.608 Z","level":"debug","msg":"\tgithub.com/mattermost/focalboard/server@v0.0.0-20210525112228-f43e4028dbdc/api/api.go:217 +0x80c","plugin_id":"focalboard"} …
```

Avoid panic in request error handling

---

webapp/src/components/calendar/fullCalendar.tsx
webapp/src/components/calendar/fullcalendar.scss
webapp/src/styles/_z-index.scss

This PR `unset`s some `z-index` values that Full Calendar sets to prevent the "..." action menu from being overlapped by adjacent events in Calendar view.
I went through a couple iterations to get to this solution, but it ended up being the last "hacky" (subjectively) even though it is overriding CSS from a vendored dependency. For some context, other "solutions" I tried:
1. Reverse the event render order in Full Calendar and then use flexbox to reverse it. This didn't work with multi-day events along with the "show more" calendar widget.
2. Use a SCSS `@for` loop to set descending `:nth-child` `z-index` values e.g. https://stackoverflow.com/a/36609688
Before:
After:
closes #3425

fix: Calendar card "..." action menu overlapping behind adjacent cards

---

Makefile

This PR ensures that the `go.work` generated by Makefile does not include an entry for `enterprise` repo by default.  Most developers won't have or need `enterprise`. Those that do can add `EXCLUDE_ENTERPRISE=false` to their environment vars and regenerate the `go.work` file.
This won't be added to the developer docs since it does not apply to most developers, but will be communicated in the appropriate channels.
NONE

Exclude enterprise from go.work by default

---

mattermost-plugin/plugin.json

Cherry-pick for `release-7.2` corresponding to https://github.com/mattermost/focalboard/pull/3536

update min server version to 7.2 (#3536)

---

server/api/api.go
webapp/src/components/shareBoard/channelPermissionsRow.tsx
webapp/src/components/shareBoard/shareBoard.tsx

Now we can show DMs and GMs in the channel asociation of a board
Fixes #3521

Showing properly channel association in DMs and GMs

---

server/model/block_test.go

PR for a unit test to generate block ID for defaultTemplateId when duplicating the block.
Fixes https://github.com/mattermost/focalboard/issues/3478

Unit test to GenerateBlockId for defaultTemplateId

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

mattermostauthlayer.GetMemberForBoard was returning nil,nil when an error occurred as it was only checking the IsErrNotfound case.  This caused a panic further up the stack (HasPermissionToBoard) in that it expected a valid member returned if err==nil.
This should be added to 7.2 as well. 
NONE

Fix panic caused by returning nil,nil in GetMemberForBoard

---

webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap

A cherry-pick from main was displaying `v7.3.0`, which was correct on `main`. Updated for `release-7.2` back to `v7.2.0`

Fix cypress from bad cherry-pick

---

webapp/src/components/shareBoard/teamPermissionsRow.tsx

This PR removes the Admin option from the selector of roles for the minimum
role in the team.
Fixes #3243

Removing the Admin role option from team minimum role

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

To show the boards with syntetic memberships in the search results we need to
add the channel membership relation to the query. This only affects the plugin
mode so it is place in the mmauthlayer store layer.
Fixes #3515

Show boards with syntetic membership

---

mattermost-plugin/webapp/src/components/boardSelector.test.tsx
mattermost-plugin/webapp/src/components/boardSelector.tsx
server/api/api.go
server/integrationtests/permissions_test.go
webapp/src/octoClient.ts

I need to allow the system to search only for linkable boards (that are the ones that you have permissions to manage roles in it).
Fixes #3509

Allow to search only for linkable boards

---

server/services/store/sqlstore/data_migrations.go
server/services/store/sqlstore/migrate.go

After this changes, the `TeamLessBoardsMigration` will check the team and the team membership of the users to discard deleted entities when cosidering what team to assign a board to.
Function names updated for consistency with the rest of the migrations.
PR labelled as `Do Not Merge` as I want to run some more tests focused on deleted memberships tomorrow. Please review the approach as it's code completed.
Fixes #3588

Update teamless boards migration to check for deleted entities

---

webapp/src/components/boardsSwitcherDialog/__snapshots__/boardSwitcherDialog.test.tsx.snap
webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.scss
webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.test.tsx
webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx

Retrieves categories and adds the boards categories to the "Find Boards" search results.
Fixes https://github.com/mattermost/focalboard/issues/3620

Add category to the board search

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go
server/services/store/sqlstore/board.go

Moving multiple word search to "And" rather than "Or". Or is causing too many matches
Fixes https://github.com/mattermost/focalboard/issues/3564

GH-3564: Change boards search to "all" words

---

server/ws/plugin_adapter.go
server/ws/plugin_adapter_cluster.go

Fixes #3559
The issue was that the WS event for notifying change of a board's category was being sent to all users in team. It should be sent only to the user who performed the action. In this PR I've reduced the WS event's scope only to the correct user for both direct WS event and events received via cluster.

Restricted scope of board-category change WS event to correct user

---

webapp/src/components/viewHeader/newCardButton.tsx

Some boards created from earlier templates have an invalid `defaultTemplateID`. This PR will make sure the templateID exists before using it as the default.
Fixes https://github.com/mattermost/focalboard/issues/3597

GH-3597 Make sure template exists before creating card

---

server/api/auth.go

The rest api for changing password is not needed for plugin mode.  This PR ensures it does not get registered when in plugin mode.
See https://github.com/mattermost/focalboard/pull/3624#discussion_r942309325
NONE

Move rest API for changepassword to personal server route

---

mattermost-plugin/webapp/src/components/rhsChannelBoards.test.tsx
mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
server/ws/plugin_adapter.go
webapp/src/store/boards.ts

Before some events weren't handled correctly as part of the websocket handling.
Also I ensured whenever you notify a membership change it alwasy notify the
user itself, doesn't matter if that memberships belongs to the boards that you
are monitoring.
Fixes #3573

More robust RHS handling of websocket events

---

server/services/store/sqlstore/data_migrations.go
server/services/store/sqlstore/legacy_blocks.go
server/services/store/sqlstore/migrate.go

This data migration fetches all boards whose owner has a deleted membership on the board's team and fixes them by processing them again, this time with the fix applied to the `getBestTeamForBoard` function that skips deleted teams and team memberships
Fixes https://github.com/mattermost/focalboard/issues/3588

Adds data migration to clean badly assigned boards

---

mattermost-plugin/webapp/src/index.tsx

This has been a painful bug.
The root cause is we have logic within `mattermost-plugin/webapp` to do `.subscribe()`-ing to both the Mattermost redux store & the Focalboard redux store and keep a few specific items in sync. For this bug, we we're focusing on the current team ID.
Previously, when syncing, if the current team ID changed we would re-`.push()` the URL to go to the team, even if we were already on a URL for the same team. This was causing a sort of race/circular condition where depending on how the stores sync'd up it might associate the `lastBoardId` with an incorrect `teamId` and it all breaks subtly by rendering the template selector.
This change _should_ fix the above case however we've seen some instances of navigating Boards -> Channels -> Boards not rendering the last …

fix: don't re-.push() the URL if already on teamId

---

webapp/src/components/workspace.tsx

The desktop app was using a different approach (instead of open in a new tab it
opens it directly in the current tab) that makes the current board something
that exists so it wasn't changing when the url was there, so I now force to
show the template selector whenever you are creating a new board from a
channel.
Fixes #3572

Fixing create-board from board selector in desktop app

---

webapp/src/pages/boardPage/teamToBoardAndViewRedirect.tsx

Credit to @sbishel. ✨ 
This changes behavior to always try and use the `lastBoardId` for a given `teamId` that is persisted in localStorage. Now, when switching between teams the last board + view will be shown instead of template selector.
Similar to #3651, we're confident enough in these changes locally that we're looking to get this merged in, another RC cut, and test on the bugbash server.
cc @ogi-m if you're able to help validate this fix
closes #3654

fix: always try the `lastBoardId` when switching teams

---

webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
webapp/src/components/shareBoard/teamPermissionsRow.test.tsx
webapp/src/components/shareBoard/teamPermissionsRow.tsx

Cherry pick of https://github.com/mattermost/focalboard/pull/3672 on release-7.2.
* Only allow viewer role in temaPermissionRow for templates
* set type
Co-authored-by: Scott Bishel <scott.bishel@mattermost.com>
Co-authored-by: Mattermod <mattermod@users.noreply.github.com>

CherryPick - Only allow viewer role in temaPermissionRow for templates (#3672)

---

webapp/src/components/shareBoard/__snapshots__/teamPermissionsRow.test.tsx.snap
webapp/src/components/shareBoard/teamPermissionsRow.tsx

Add a conditional to only render `Viewer` on a (custom) template sharing dialog, not on a board. Notice this is direct to 7.2 w/ no cherrypick. I discussed this with @wuwinson and we agreed that `main` is working as expected for 7.3, which will have more roles e.g. `Commenter`.
closes #3678

fix: `Viewer` only on a template, not board

---

webapp/i18n/en.json
webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx

Hi! So, this PR is related to PR #3577, I tried following the steps as instructed, but I think I messed up in the merging part and the PR got closed 😅. I'm kinda new to Open Source contributions outside of my own repos. Also, sorry for the late reply on this.
Summary
Fix templates with empty name are shown as empty on the template list
- When no name is specified for a certain template, now the default name for untitled templates is displayed to the user.
- Changes the default name for untitled templates in english to just "Untitled"
Ticket Link
Fixes https://github.com/mattermost/focalboard/issues/3400

Fix Templates with empty name are shown as empty on the template list

---

server/api/api.go

Ports #3691 to 7.2 release.
n/a

fix: return `{}` user props in single-user mode (port of #3691)

---

server/api/users.go

In single-user mode, the `props` for a user was being returned as `null` and not an empty `{}` object. This was breaking the frontend due to a runtime error of trying to access the `props.hiddenBoardIDs` since `props` itself was `null`.
There will be a discrete cherrypick PR to `release-7.2`, too.
closes #3683

fix: return empty props in single-user mode

---

mattermost-plugin/product/api_adapter.go
mattermost-plugin/server/api_adapter.go
mattermost-plugin/server/boards/boardsapp.go
server/model/mocks/mockservicesapi.go
server/model/services_api.go
server/services/permissions/mmpermissions/mocks/mockpluginapi.go
server/ws/mocks/mockpluginapi.go

This PR fixes an issue setting up Boards in product mode.  The call to register the API router was missing.
This change has no effect when running as plugin.
NONE

Register API router in product mode

---

mattermost-plugin/product/boards_product.go
mattermost-plugin/server/plugin.go
server/main/main.go
server/model/version.go

This change prints the same information that the standalone instance does on plugin activation

Print log server information on plugin run

---

webapp/src/wsclient.ts

Check that ws is readyState. This will hopefully fix periodic Cypress Test failures. I was not able to reproduce the failures locally to ensure this fixed it.
Fixes https://github.com/mattermost/focalboard/issues/3589

GH-3589 - Make sure websocket is ready, fix for Cypress failures

---

server/app/blocks.go
server/app/export.go
server/services/permissions/mmpermissions/mocks/mockpluginapi.go
server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/boards_and_blocks.go
server/services/store/sqlstore/public_methods.go
server/services/store/store.go
server/services/store/storetests/blocks.go
server/services/store/storetests/data_retention.go
server/ws/mocks/mockpluginapi.go

Removes duplicated logic to get blocks that belong to a board.

Remove duplicated store and app method to get blocks that belong to a board

---

server/model/block.go
server/services/store/storetests/blocks.go
webapp/src/blocks/block.ts

This PR ensures that blocks cannot change their BoardID when patching.  See https://community.mattermost.com/private-core/pl/m7f7qyd9j7f69qdr1q8zk7jixr  and  https://community.mattermost.com/private-core/pl/1zbd9t8izin4u8t4d8u43ppzsa for rationale.
NONE

Don't allow changing BoardID when patching blocks

---

server/api/blocks.go
server/app/blocks.go
server/app/blocks_test.go

This PR adds a `disable_notify` for all block APIs that can trigger subscriber notifications.  This allows for external tools using the APIs to make bulk changes without creating a notification storm.  Does not affect websocket notifications so that connected clients remain synchronized.
Part of the API improvement initiative.
NONE

Add `disable_notify` to all block APIs that can trigger notifications.

---

webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.test.tsx
webapp/src/components/kanban/kanban.test.tsx
webapp/src/components/kanban/kanban.tsx

The PR fixes the `+ New` button issue in the kanban view which was not allowing the create a card.
Fixes https://github.com/mattermost/focalboard/issues/3676

Fixed the new button error in kanban

---

mattermost-plugin/product/boards_product.go

When adding a product service to mmserver it causes a switch statement in Boards to have an incomplete set of case statements until an accompanying PR is made to Boards.  This PR relaxes that exhaustive check for the specific switch statement, otherwise anytime a new service is added to mmserver it will break Boards until the accompanying PR is merged.
NONE

Exclude exhaustive check for product services switch

---

server/integrationtests/clienttestlib.go

This PR ensures the `FOCALBOARD_UNIT_TESTING` env var is set for integration tests.  This ensures certain expected errors become warnings.
I've extracted this from the API improvements work to avoid unrelated changes in that PR.
NONE

Set FOCALBOARD_UNIT_TESTING for integration tests

---

server/services/store/sqlstore/migrations/000025_indexes_update.down.sql
server/services/store/sqlstore/migrations/000025_indexes_update.up.sql
server/services/store/storetests/blocks.go

This changes update and add some focalboard indexes to improve data access speed. The rationale for the changes is as follows:
- `focalboard_blocks (channel_id, id)` was not in use at all after the permission changes, so it doesn't make sense to keep as the PK of the table.
- `focalboard_blocks (id)` makes sense now as a PK, and improves:
- `getBlocksByIDs` (MySQL 0.215 => 0.001 | PostgreSQL 87.063 ms => 0.082 ms)
- `idx_blocks_board_id_parent_id` improves:
- `getWithParentAndType` (MySQL 0.197 => 0.001 | PostgreSQL 81.356 ms => 0.068 ms)
- `getBlocksWithParent` (MySQL 0.195 => 0.001 | PostgreSQL 93.420 ms => 0.055 ms)
- `getSubTree2` (MySQL 0.162 => 0.001 | PostgreSQL 88.920 ms => 0.092 ms)
- `getBlocksWithType` (MySQL 0.215 => 0.003 | PostgreSQL 84.725 ms => 0.055 ms)
- …

Updates db indexes to improve performance

---

server/services/store/sqlstore/sqlstore.go

These changes causes the app to error on start if the database is detected to be MariaDB

Adds a check that errors on store start if MariaDB is detected

---

webapp/src/store/boards.ts

Separated logic to handle deleted members before handling adding members. Previously deleted items would return prematurely because they already existed in `boardUsers`.
Fixes https://github.com/mattermost/focalboard/issues/3293

GH-3293 - Fix issue with deleted members not being updated via websocket

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

Adds isGuest to end of sql statement. Causing error when loading board members. 
"unable to find users: sql: expected 11 destination arguments in Scan, not 12\"","_msg":"\"unable to find users: sql: expected 11 destination arguments in Scan, not 12\""
None

fix sql statement, add 'isGuest'

---

server/model/block.go
server/services/permissions/mmpermissions/mocks/mockpluginapi.go
server/services/store/mockstore/mockstore.go
server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/public_methods.go
server/services/store/store.go
server/ws/mocks/mockpluginapi.go

This PR provides a new store API for querying blocks which accepts a `QueryBlocksOptions` struct.  This new API replaces the separate implementations of `GetBlocksWithParentAndType`, `GetBlocksWithParent`, `GetBlocksWithType`, `GetBlocksForBoard`.  Provides pagination for fetching blocks.  Also makes it easier to add new filters later.
This was extracted from the Boards API V3 work to make PR reviews easier.
Running `make generate` also created some unrelated changes.
NONE

getBlocks store API with query options

---

mattermost-plugin/webapp/src/components/boardSelector.tsx

This PR will add the functionality to close the boardSelector from the channel's RHS after selecting the board.
Fixes https://github.com/mattermost/focalboard/issues/3679

Added functionality to close boardSelector after linking board

---

server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql

Fixes #3722 typo, which was referencing non-existent lowercase tables when in plugin mode i.e. `preferences` -> `Preferences`.
n/a

fix: reference Uppercase MM tables

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go
webapp/src/components/markdownEditorInput/markdownEditorInput.tsx

Fixing bugs related to `@mention`s and Guest accounts:
- filter the in-memory board users list for private boards (where the Redux state is used, no API calls)
- fix in an invalid DB query for searching users as a guest
- handle `includePublicBoards` when getting boards for a user & team
- don't use the API search for users when `@mention`ing as a guest
closes #2604 
cc @wuwinson @jespino this should handle #3746 as-is too (intentionally not using a closing keyword there 🙂)

Fix @-mentions in boards & for guests

---

server/services/store/sqlstore/migrate.go
server/services/store/sqlstore/schema_table_migration.go
server/services/store/sqlstore/schema_table_migration_test.go

The old schema table migration code was initializing the migration engine before changing the migrations table and was mixing queries on two different database connections (the `s.db` connection and the migrations `db` connection), both things potentially causing race conditions on the applications of the migrations.
The changes on this commit take care of altering the migrations table before the morph migration engine is initialized, so we're sure that it's using the new table cleanly, and they use the same connection for all operations, better isolating the schema table migration process.
The methods `isSchemaMigrationNeeded`, `isSchemaMigrationNeededSQLite`, `getLegacySchemaVersion`, `createTempSchemaTable`, `useNewSchemaTable` and `deleteOldSchemaMigrationTable` have only been moved …

Refactor schema table migration mechanism

---

server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql
server/services/store/sqlstore/migrationstests/boards_migrator_test.go
server/services/store/sqlstore/migrationstests/fixtures/test27MigrateUserPropsToPreferences.sql
server/services/store/sqlstore/migrationstests/migration_27_test.go

This PR fixes migration 27, adds a test for the fix and the personal server/desktop migration and modifies the testing mechanism to correctly support SQLite

Fix migration 27 and update boards_migrator_test to support sqlite

---

mattermost-plugin/server/manifest.go
mattermost-plugin/webapp/src/components/boardSelector.scss
webapp/src/components/searchDialog/searchDialog.scss
webapp/src/components/viewHeader/viewHeader.scss

GH-3768 - Search icon fix
Aligning via flexbox so we don't have to manually define `top`
Fixes #3768

GH-3768 - Search icon fix

---

mattermost-plugin/server/boards/boardsapp_util.go
server/server/server.go
server/services/config/config.go

Fixes #3773
We weren't reading Mattermost's S3 timeout value. So when initialized the S3 client, the timeout used the default value of `int64`, which is 0. So upload requests timed out in 0 milliseconds.

Read Mattermost s3 timeout value and used a default if not exist

---

webapp/src/properties/multiperson/multiperson.tsx

This PR will add some corner case checks for the multiperson property i.e. when the multiperson property is checked in the kanban view, the remaining card with no multiperson should render without multiperson and should not throw any `undefined` error.
Fixes https://github.com/mattermost/focalboard/issues/3789

Added corner case check for multiperson property

---

webapp/src/components/messages/versionMessage.tsx

@justinegeffen reached out to get the URL updated in the "what's new" version banner to point to a mattermost.com permalink redirect. Because of version/release reasons, I'm setting the cherrypick to 7.2 so it rolls out with the upcoming 7.2.1 (any concerns @sbishel?) and we'll need to manually run a `/cherry-pick release-7.3` so it makes it to 7.3 as well.
I'm not sure if this is how all mattermost.com/pl/ URLs work, but I'm concerned that it's a HTTP 301 (permanent) redirect when IMHO I think it should be a HTTP 302 (temporary) redirect. I'm 5/5 on this because web browser clients will typically make the 301 request _once_ and then any subsequent requests will just be redirected at the client level i.e. cached so if the redirect location changes e.g. new docs URL then the expected …

Update version banner URL to redirect permalink

---

server/app/boards.go
server/app/boards_test.go
server/server/server.go
server/services/metrics/metrics.go
server/services/store/mockstore/mockstore.go
server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/public_methods.go
server/services/store/store.go
server/services/store/storetests/boards.go

Boards count was no longer being sent, since "boards" were removed from the blocks table. This PR implements sending boards count along with other block/user counts.
fixes https://github.com/mattermost/focalboard/issues/3797

GH-3797 Update telemetry to send boards count

---

mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx

I moved this image with the MPA changes, and Webpack is no longer able to find it on its own when running as a plugin
None

Fix broken image in plugin

---

server/services/store/sqlstore/board.go
server/services/store/storetests/boards.go

This PR is a temporary fix for main.  A recent PR made `store.getBoardsInTeamByIds` more strict in that the number of ids passed in must match the number of boards found.  This API has been returning a mismatched list for a while now but the  error was hidden.
A proper fix may be to simply allow templates to be returned in `store.getBoardsInTeamByIds`.  This PR simply reverts to yesterday's behaviour.  A ticket will be created to revisit this.
NONE

Fix broken main store.getBoardsInTeamByIds

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go
server/services/store/sqlstore/board.go
server/services/store/storetests/boards.go

Follow up to https://github.com/mattermost/focalboard/pull/3840 that moves the responsibility of ignoring the `NotAllFound` error to the caller, so in this case, the `GetBoardsForUserAndTeam` explicitly decides that if the result list is incomplete, it's ok and can be returned.
Store method is left untouched so other callers can decide not to continue if the list is incomplete.

Check on GetBoardsForUserAndTeam if the board result list is incomplete and continue if that's the case

---

webapp/src/components/shareBoard/shareBoard.tsx

Previously, the `<Select>` in the Share Board modal was only filtering on if the user was a member of the board, regardless of explicit or implicit type. This fixes the logic to include implicit members so they could be made explicit if desired.
closes #3808

fix: display non-explicit members in Share Board modal <Select>

---

server/api/users.go
server/app/auth.go
server/app/auth_test.go
server/app/onboarding.go
server/app/onboarding_test.go
server/app/user.go
server/integrationtests/permissions_test.go
server/integrationtests/pluginteststore.go
server/model/user.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go
server/services/store/mockstore/mockstore.go
server/services/store/sqlstore/public_methods.go
server/services/store/sqlstore/user.go
server/services/store/store.go
server/services/store/storetests/users.go
server/services/store/storetests/util.go

This PR updates the user store in both `sqlstore` and `mmauthlayer` to return the updated entities after inserting / patching them.
As part of this PR I'm removing all references to `User.Props`, as those were migrated to the `preferences` table and are not fetched / updated anymore. A follow up migration that actually removes the column should follow once we assert that everything is working correctly.
This PR also removes the ambiguity between Props and Preferences on the naming of the model structs and the store methods for consistency.
It could potentially fix https://github.com/mattermost/focalboard/issues/3799

Update user store to return the updated entities after inserting / patching them

---

webapp/src/wsclient.ts

This PR avoids the interface breaking completely on a failed WS message sent and prints the error that caused the failure

Catch exception on failed WS command to avoid interface from breaking

---

webapp/i18n/en.json
webapp/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
webapp/src/components/shareBoard/shareBoard.test.tsx
webapp/src/components/shareBoard/shareBoard.tsx

When sharing template, `Search for people and channels` is displayed in placeholder, but channels cannot be searched.
This PR fixes a message in placeholder.
N/A.
Following [Contributing to Mattermost without a ticket](https://developers.mattermost.com/contribute/getting-started/contributions-without-ticket/).

Fix a placeholder message when sharing template

---

webapp/src/pages/boardPage/boardPage.tsx

This error was caused due to attempting to combine a Kanban view with another board that didn't contain a "Select" property. 
When clicking on the Board Name in the sidebar, the board is initially loaded with the "CurrentView" from the redux store. If that view is a Kanban, and the board doesn't contain a "select" property an error is thrown and the board redirects to the error page.
This PR clears the "CurrentViewID" from the react store even if it is empty (''). This prevents the board from loading with an improper view.
Fixes https://github.com/mattermost/focalboard/issues/3815
Fixes https://github.com/mattermost/focalboard/issues/3780

GH-3815 Fix for Error Page redirection

---

server/api/files.go

This PR makes the `handleServeFile` endpoint behave the same way it was before the server error refactor changes.

Preserve old handleServeFile endpoint behavior after refactor

---

webapp/webpack.common.js

there is an extra point in the webpack configuration.
Before fix : 
After fix : 
_mattermost-plugin is already fixed => https://github.com/mattermost/focalboard/blob/main/mattermost-plugin/webapp/webpack.config.js#L118_
Fix #3764

fix[GH-3764]: webpack extension

---

webapp/src/styles/_markdown.scss

There is an user agent stylesheet on chrome with a `border-collapse: separate` and `border-spacing: 2px`
https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css
I reset border-collapse in `.markdown__table` to fix it
Fix #1950

[GH-1950] : Fix border-collapse user agent stylesheet

---

webapp/src/components/table/table.scss

Person autocomplete in table view fixed. The dropdown was rendering but because table cell had `overflow: hidden` styling, it was not visible. Overwrote the style for Person cell.
Fixes https://github.com/mattermost/focalboard/issues/3903

fix: Person autocomplete in table

---

webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
webapp/src/components/shareBoard/userPermissionsRow.tsx
webapp/src/widgets/menu/menu.tsx
webapp/src/widgets/menu/menuUtil.ts

Adds an option to the `openUp` util to force the alignment to the bottom and uses it to pin the roles submenu to the user permission row.
Fixes https://github.com/mattermost/focalboard/issues/3885

Pins the roles submenu to the user permission row

---

webapp/src/components/kanban/kanban.tsx
webapp/src/components/kanban/kanbanColumnHeader.tsx

I just fixed that described in #3551. It reproduced when there is only one group property which is grouping the card and it removed. In Kanban component, it has early return statement which caused the render-hook error.  I just moved it to before the return statement.
https://github.com/mattermost/focalboard/issues/3551

fix javascript error when curren group is delete

---

webapp/src/components/shareBoard/__snapshots__/userPermissionsRow.test.tsx.snap
webapp/src/components/shareBoard/userPermissionsRow.tsx

The viewer button on share dialog was misaligned due to it was missing the `empty-icon` whenever the `currentRole` is not equal to `Viewer` role. This PR fixes it. (Attaching before and after screenshots)
Before
After
Fixes https://github.com/mattermost/focalboard/issues/3865

Fix misaligned 'viewer' role on share board/template dialog

---

webapp/src/hooks/permissions.tsx

This PR fixes the permission cascade check for `minimumRole`
https://github.com/mattermost/focalboard/issues/3945

Fix useHasPermission minimumRole cascade check

---

webapp/src/components/markdownEditorInput/markdownEditorInput.tsx
webapp/src/properties/multiperson/multiperson.tsx
webapp/src/properties/person/person.tsx

Renamed variable to avoid confusion and included setting the user as Admin, since admin users can be set by other admins.
Fixes #3957

add setting admin role when add member

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

When guest users was implemented, we included a check for guest users. In order to perform that check, the user is retrieved. If the user didn't exist, an error is thrown.
When importing templates, the user 'system' is added to the board. However, because it doesn't exist as a user, it fails this check and templates are not imported.
Issue #3993 fails because of missing templates, this will fix both.
Fixes #3992
Fixes #3993

GH-3992 fix for missing templates, error when 'system' not found as user.

---

mattermost-plugin/webapp/webpack.config.js

Since we're referring to this as "boards" in the API requests when it's running as a product, I've renamed the module container to "boards" to match that
https://mattermost.atlassian.net/browse/MM-46275

MM-46275 Rename product container to 'boards' for consistency

---

Makefile
mattermost-plugin/Makefile
mattermost-plugin/webapp/package.json
mattermost-plugin/webapp/webpack.config.js

Straightforward enough. One small change other than adding the new target is a slight change to the webpack config when building as a product because the JS code was being output to the wrong place previously for a product.
https://mattermost.atlassian.net/browse/MM-46275

MM-46725 Add build-product target to compile the Boards product

---

mattermost-plugin/server/manifest.go
server/services/store/sqlstore/data_migrations.go
server/services/store/sqlstore/data_migrations_test.go
server/services/store/sqlstore/helpers_test.go
server/services/store/sqlstore/migrate.go

This PR ensures that all FocalBoard tables have the correct collation and charset settings for existing tables and any added in the future.  This is done via a final migration step that applies these settings in an idempotent fashion on every run.  
fixes https://github.com/mattermost/focalboard/issues/3871

Fix collation and charset after migrations (every run)

---

server/services/store/sqlstore/boards_and_blocks.go
server/services/store/storetests/boards_and_blocks.go

Linked channels are included when duplicating a board. This PR removes the linked channel when duplicating the board
Fixes https://github.com/mattermost/focalboard/issues/3953

Gh 3953 remove channel link duplicate

---

mattermost-plugin/webapp/src/index.tsx

When in product mode, server sends websocket events keyed to plugin id `com.mattermost.boards` and when in plugin mode they are `focalboard`.  This PR overrides the id specified in plugin.json when in product mode with the correct id.   Without this the websocket events are not processed on the client.   
Tested for product mode and plugin mode.
NONE

Set correct plugin id when in product mode

---

server/services/store/sqlstore/migrations/000027_migrate_user_props_to_preferences.up.sql

Make sure the props field in the postgresql Users table does contain a JSON hash and not some other data structure like a string or an array.
If props contains something other thatn a hash, `props - 'key'` will fail and thus the migration will fail.
This is a partial fix for #4018. 
This PR does not address the other issue mentioned, about the `dirty` column. My guess is that this is spurious issue caused by a second/old copy of focalboard in the users installation.

make sure users.props contains a hash!

---

server/services/notify/notifysubscriptions/diff2slackattachments.go

This PR modifies the generation of diffs for notifications by not replacing newlines with symbols when only adding a comment or text.  Modified text still has the old behaviour and these diffs are hard to decipher with newlines. 
See conversation here:  https://github.com/mattermost/focalboard/issues/2658#issuecomment-1087992135
Note:  a slight refactor was required for `cardDiff2SlackAttachment` as the cyclomatic complexity exceeded the linter threshold.
fixes https://github.com/mattermost/focalboard/issues/2658

Don't replace newlines with symbol when adding comment or text.

---

server/app/boards.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go
server/services/store/mattermostauthlayer/mattermostauthlayer_test.go

Updates the text displayed when linking a board to a channel.
Second fixes a bug (and adds tests) where the Boards bot would initially fail "EnsureBot", which was the reason for the card, it was implemented, but there was a but. 
Fixes https://github.com/mattermost/focalboard/issues/3941
Fixes https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/b4ctmm917q3rzdfi451qtuxjzcw/vn3tt1q8ndj87frb4uyu4936yfh/c9jwpnzupn3yw5kmbpzyhedunwo

Gh 3942 - fix bug with Boards bot, update link text

---

webapp/src/components/markdownEditorInput/markdownEditorInput.tsx

Cherry pick of #4039 on release-7.4.
```release-note
NONE
```

Automated cherry pick of #4039

---

import/asana/README.md
import/asana/importAsana.ts
import/jira/README.md
import/jira/importJira.ts
import/jira/jiraImporter.ts
import/nextcloud-deck/README.md
import/nextcloud-deck/importDeck.ts
import/notion/README.md
import/notion/importNotion.ts
import/todoist/README.md
import/todoist/importTodoist.ts
import/trello/README.md
import/trello/importTrello.ts
webapp/src/constants.ts

Noticed the URL to the [docs page for migrating](https://docs.mattermost.com/boards/migrate-to-boards.html) is referencing an old one. This properly redirects, but in that redirect the hash e.g. `#import-from-jira` is lost so the specific section isn't actually linked, just the page as a whole.
Also noticed that the READMEs for the import scripts along with the help text were still referencing the older `.focalboard` extension, so I updated those to the shiny `.boardarchive`. This was correct on the docs site so change necessary there.
cc @justinegeffen 
n/a

Update URL to docs page for migrating and reference `.boardarchive`

---

mattermost-plugin/webapp/webpack.config.js

This conflicts with https://github.com/mattermost/focalboard/pull/4026, but I didn't want it to have to depend on that one since this one's needed for 7.5 and the other one isn't.
The gist of this change is that line 119 sets the path for static images in product and non-product modes, and then line 206 overrides that only if we're serving the product for development. I would've liked to not set it and then override it below, but I couldn't come up with a better way to keep the webpack dev server setup stuff all together that I was happy with.
https://mattermost.atlassian.net/browse/MM-47562

MM-47562 Serve images from the correct URL in product mode

---

webapp/src/store/users.ts

Fixes issue where the "Welcome Screen" flashes when accessing a board using the `boards/team/xx` endpoint. Also fixes issue with "Welcome Screen" always being displayed when accessing the old `boards/workspaces/xxx` endpoint.
The issue is that the users configuration settings are now retrieved as part of "InitialLoad". So when we are initially checking `!myConfig[UserSettingKey.WelcomePageViewed]`, myConfig has not been loaded resulting in the welcome page being displayed.
This PR retrieves `getMyConfig()` as part of `fetchMe`, which is called from the App element, much earlier in the lifecycle. I initially created a separate `fetchMyConfig`, but decided on changing `fetchMe`, since I would have to call `fetchMyConfig` everywhere `fetchMe` is called.
Fixes #4007

GH-4007 Fix for welcome screen flashing

---

webapp/src/pages/boardPage/boardPage.tsx

Fixes an issue where the webapp gets into a loop calling `initialLoad`. And the first user cannot log in. As shortly after being redirected to `/register` and error occurs and redirects back to `/login`
When a new Personal Server installation is accessed, no one is logged in an error is thrown [here](https://github.com/mattermost/focalboard/blob/main/webapp/src/store/initialLoad.ts#L27).
This results in the errorPage redirecting automatically back to `/login` - https://github.com/mattermost/focalboard/blob/main/webapp/src/errors.ts#L73
~By only calling `initialLoad`, if me is defined, stops the cycle.~
New fix is to ensure we disconnect the same function as connected.
Fixes https://github.com/mattermost/focalboard/issues/4000

Personal Server - remove same function on disconnect as added on reconnect.

---

.github/workflows/ci.yml
Makefile
docker-testing/docker-compose-mariadb.yml
server/services/store/sqlstore/migrations/000018_add_teams_and_boards.up.sql
server/services/store/sqlstore/migrationstests/fixtures/test18AddTeamsAndBoardsSQLMigrationFixtures.sql
server/services/store/sqlstore/migrationstests/migration_18_test.go
server/services/store/sqlstore/sqlstore.go
server/services/store/sqlstore/util.go

This PR updates the database migrations to be compatible with both `MySQL` and `MariaDB` and adds the `MariaDB` engine to the server tests so we can quickly pick up compatibility issues.
This does not indicate that Focalboard nor Mattermost support `MariaDB`, please [check the official documentation](https://docs.mattermost.com/install/software-hardware-requirements.html#database-software) for more information.
https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/b4ctmm917q3rzdfi451qtuxjzcw/vezy9zbpm1tnmfecbuoopjgsgqc/cg9oz83jds3b58f6dzsafu3eo8r

Add mariadb tests and update database migration for compatibility

---

server/services/permissions/mmpermissions/mmpermissions.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go

GetMemberForBoard can return a nil member if the member is not found and it meets no other membership criteria. This is due to the `err` variable being reset within the `if()` clause, but no member being created.
Updated to a more specific error variable, so it will hopefully not be overwritten in the future. The function is fragile and should be rewritten.
Fixes https://github.com/mattermost/focalboard/issues/4059
Fixes https://mattermost.atlassian.net/browse/MM-47528

Fix GetMemberForBoard from returning a null member

---

mattermost-plugin/webapp/webpack.config.js

Okay, so I know this is reverting my previous PR (https://mattermost.atlassian.net/browse/MM-47562) and conflicts with previous ones as well, but I think I've finally sorted out this asset path thing for products once and for all.
Instead of telling Webpack what the final URL of images will be, we're just letting Webpack figure it out entirely by itself. It does that by using `document.currentScript` (supported on all major browsers) to find where a JS file to find where the images are located. Because of the changes I made in https://github.com/mattermost/focalboard/pull/3748/commits/b9e2263cb519376574f099c06614bcff90f4dc63, JS and images are always located in the same folder.
Because this has been a pain to get working in all cases, I went through and tested a production build with …

MM-47562/MM-47631 Just rely on Webpack for image paths in product mode

---

webapp/src/widgets/guestBadge.scss

Signed-off-by: Adithya Krishna <adikrish@redhat.com>
Added a margin-right to the guest badge to prevent text being attached or overlapped to the badge itself
Fixes https://github.com/mattermost/focalboard/issues/3939

[GH-3939] - Updated Margin for GuestBadge

---

webapp/src/components/viewHeader/viewHeader.tsx
webapp/src/widgets/buttons/button.tsx

This's the PR to fix the Bug [#533](https://github.com/mattermost/focalboard/issues/533) - Filter menu does not disappear when clicked for a second time (Board > Filter)
The revisions and considerations are:
1. In the file "\webapp\src\components\viewHeader\viewHeader.tsx", among the button of <ModalWrapper>, it sets the onClick event to always set setShowFilter(true) . This's why even though we click the filter button again, the filter menu will never disappear.
2. In order to fix it, to revise the function into setShowFilter(!showFilter)
3. However it'll still have problem, because there's the onClose event below to always set setShowFilter(false). 
4. We cannot move out the onClose with setShowFilter(false), because it's triggered when the user clicks other places in the webpage to …

Fix Bug #533 - Filter menu does not disappear when clicked for a second time (Board > Filter)

---

server/services/store/sqlstore/data_migrations.go

As of 7.4.3 the plugin fixes up any inconsistent collation or charset settings in the database (MySQL only).  It uses the Channels table to determine the current collation setting.  In the case of personal server there is no Channels table so this would fail. TBH I did not know personal server could use MySQL - I thought it was Sqlite only.  
The fix is to use a sensible default for personal server.
fixes https://github.com/mattermost/focalboard/issues/4067

Fix collation for personal server

---

mattermost-plugin/webapp/webpack.config.js

This makes it so that people who develop MM on a URL other than `http://localhost` can redefine the URL, port, and protocol that the Boards Webpack dev server runs on for MPA development. Without it sets, it still defaults to running the dev server on `http://localhost:9006`
https://mattermost.atlassian.net/browse/MM-47238
https://github.com/mattermost/mattermost-server/pull/21435
https://github.com/mattermost/mattermost-webapp/pull/11381
```release-note
NONE
```

MM-47238 Add MM_BOARDS_DEV_SERVER_URL environment variable for MPA

---

webapp/src/constants.ts

fixes issue where portuguese code in constants didn't match codes in [i18n.tsx](https://github.com/mattermost/focalboard/blob/main/webapp/src/i18n.tsx)
Fixes https://github.com/mattermost/focalboard/issues/4065

fix code for portuguese to match codes in i18n.tsx

---

mattermost-plugin/server/manifest.go
webapp/src/utils.test.ts
webapp/src/utils.ts

Fixes issue where links are encoded even thought they may already be encoded. Fix is simply decode prior to encoding. 
Fixes https://github.com/mattermost/focalboard/issues/3496

Fix double encoding

---

mattermost-plugin/build/manifest/main.go
mattermost-plugin/build/sync/main.go
mattermost-plugin/build/sync/plan/actions_test.go
mattermost-plugin/build/sync/plan/checks_test.go
mattermost-plugin/build/sync/plan/git/file_history_test.go
server/assets/build-template-archive/main.go
server/services/store/generators/main.go
server/services/store/sqlstore/util.go

Reference - https://github.com/go-critic/go-critic/issues/1019
`io/ioutils` functions have been moved to the packages `os` or `io`.
`make server-lint` was failing for me on latest `main`.

Fixed server lint issue about not using deprecated package io.ioutils

---

webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
webapp/src/components/table/__snapshots__/table.test.tsx.snap
webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
webapp/src/components/table/tableRow.scss
webapp/src/components/table/tableRow.tsx

The problem was we were always adding `margin-left: -60px`. We should not apply this property when we're not showing the delete menu.
Fixes https://github.com/mattermost/focalboard/issues/3915#event-7516604347

Remove margin on hover if table readonly

---

.gitignore
README.md

Updated the readme to reflect how to actually setup the environment locally. Also updated .gitignore to ignore the .env file that now needs to be created. 
Fixes https://github.com/mattermost/focalboard/issues/4086

[GH-4086] Doc: Personal server setup guide out of date

---

webapp/src/store/cards.ts

@michaelgamble reported a bug where searching in a specific board was crashing the frontend. There was an instance of trying to call `.map` on a _string_ for the property value of a `multiSelect` type and it was expecting an array of strings.
My concern is I'm not sure _why_ the property value was a string and not an array of strings in the first place. I'd rather fix the root cause and not a symptom.
fixes #4092

fix: convert `multiSelect` prop value to [] if required

---

webapp/src/components/centerPanel.tsx

There was 2 instances of the `viewBoard` telemetry event being emitted. One of them was _also_ in a `useEffect` with _no_ dependency array so it was being called upon mounting _plus_ after every render.
This fixes the behavior so the telemetry event is only emitted _once_ per viewing the board.
fixes #4111

fix: don't send multiple `viewBoard` telemetries

---

mattermost-plugin/webapp/src/components/rhsChannelBoards.scss
webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
webapp/src/components/cardBadges.scss
webapp/src/components/table/__snapshots__/table.test.tsx.snap
webapp/src/components/table/__snapshots__/tableGroupHeaderRow.test.tsx.snap
webapp/src/components/table/table.scss
webapp/src/components/table/tableGroupHeaderRow.tsx
webapp/src/widgets/icons/text.scss
webapp/src/widgets/menu/menu.scss

Minor UI Changes
Fixing RHS Sidebar on smaller screens
Swapping arrows on table view sections
Adjusting meta data on cards
Updating menu overflow
Fixes https://github.com/mattermost/focalboard/issues/4093
Fixes https://github.com/mattermost/focalboard/issues/4008

Minor UI Changes

---

mattermost-plugin/server/manifest.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go

The symptoms were that templates were not being updated via websockets. However, that was because the templates were being added to both `state.templates` and `state.boards`. This was due to `GetMembersForUser` returning templates, which is has to to support permissions for templates properly. 
First solution was to add a boolean and only return the templates when retrieving for member permissions. However, upon further investigation, I noticed that the function `searchBoardForUserInTeam` is all that needs to be called if public boards are requested. We only need to retrieve via direct memberships if public boards are not requested. 
This also saves an additional call, since `searchBoardForUserInTeam` already returns board objects, this removes a database call in those instances. 
Also …

Fix issues when retrieving boards

---

webapp/src/cardFilter.test.ts
webapp/src/cardFilter.ts

The PR will solve the filter issue by text for `doesn't contain`.
Fixes https://github.com/mattermost/focalboard/issues/4131

Updated the filter condition for notContains

---

mattermost-plugin/server/manifest.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go

Cherry pick of #4145 on release-7.5.
/cc  @sbishel
```release-note
NONE
```

Automated cherry pick of #4145

---

mattermost-plugin/webapp/webpack.config.js

Webpack complains about using the `https` option instead of the `server` one, so I changed that.
https://mattermost.atlassian.net/browse/MM-47793

MM-47793 Change product dev server to not use deprecated options

---

webapp/src/store/sidebar.ts

The PR adds the logic to sort all the board categories but append the system board category at the end.
Fixes https://github.com/mattermost/focalboard/issues/4138

Added logic for system board category to show last

---

server/app/import.go

Fixes a bug where the (fake) system user is added to board membership when importing default templates.  The userID is invalid and the import fails.
NONE

When importing boards, don't add user to board if system user

---

Makefile
server/services/store/sqlstore/blocks.go
server/services/store/sqlstore/data_retention.go
server/services/store/sqlstore/sqlite.go

This PR ensures that the `go-sqlite3` package is only included when the `sqlite3` build tag is specified.  This tag is automatically included for all Focalboard makefile targets, but not included when building in product mode from mm-server.
This fixes an issue with running mm-server on Ubuntu 18.04 which includes an older version of glibc (2.27) while `go-sqlite3` requires 2.28 or higher.  mm-server does not support sqlite thus there is no point including it as a dependency.
go.mod files are not impacted as they always include all packages as if all build tags are active.
See https://community.mattermost.com/private-core/pl/5z4etm5883n6ie88sas9jh1owr for discussion.
Tested with personal server (Linux & Windows). 
fixes https://github.com/mattermost/focalboard/issues/4210

Require build tag to include sqlite

---

webapp/i18n/en.json
webapp/src/components/boardTemplateSelector/__snapshots__/boardTemplateSelector.test.tsx.snap
webapp/src/components/boardTemplateSelector/boardTemplateSelector.scss
webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx
webapp/src/components/boardTemplateSelector/boardTemplateSelector.tsx
webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.scss
webapp/src/components/boardTemplateSelector/boardTemplateSelectorPreview.scss
webapp/src/components/kanban/kanbanCard.scss
webapp/src/widgets/buttons/button.scss

Updating board template picker ui to include the use template button in the header, and empty board button in the sidebar, so the buttons do not overlap the content.
Additionally, made the UI scalable on larger screen sizes so scroll on the sidebar can be avoided.

Updating board template picker ui

---

webapp/src/components/table/tableRow.scss

This PR will fix the overflow and alignment of read-only users in the table view
Fixes https://github.com/mattermost/focalboard/issues/4184

CSS fix for readonly user

---

mattermost-plugin/product/api_adapter.go
mattermost-plugin/webapp/src/index.tsx

This PR uses the `boards` product name to register with the MPA and label WS messages instead of the ID to be consistent.
Related to https://github.com/mattermost/mattermost-server/pull/21737

Updates boards registration as product to use name instead of ID

---

webapp/src/components/centerPanel.tsx

Creating a new table row should focus on the new row's title so that the user can edit it right away.
The problem is that we reset the `cardIdToFocusOnRender` state too fast, so the new card doesn't see the value anymore when mounted and therefore doesn't focus. That's why I increased the timeout from 100ms to 300ms.
Fixes https://github.com/mattermost/focalboard/issues/4070

[GH-4070] Fix focus on new table row

---

server/app/boards_test.go
server/app/category_boards.go
server/app/category_boards_test.go
server/app/category_test.go
server/app/import_test.go
server/app/onboarding_test.go

Fixes #4283
In PR #4283 I was using the method `GetMembersForUser(<userID>)` to fetch the list of all boards for a user in a team. However, I missed the fact that that method is NOT scoped to a specific team, as you can see from its parameters.
What this caused was for all boards in all teams to be considered as candidate boards to be moved into the current team's default `Boards` category. This ended the system in a state where the board belongs to Team A but is associated with a category of Team B, so it didn't show up anywhere.
I've now fixed this by using the method `GetBoardsForUserAndTeam(<userID,> <teamID>, <includePublicBoards>` to gets user's boards for the current team.

Fixed bug where boards would move to category of a different team

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

This PR uses a `UNION` query to optimize fetching `Boards` when in plugin/product mode

Replace SearchBoardsForUserInTeam query with a more efficient one

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

This PR makes the UNION queries use always the question mark positional argument (that is not numbered) and replaces it after the queries have been merged with a positional argument if the database requires it.
Fixes https://github.com/mattermost/focalboard/issues/4326

Fixes positional arguments in UNION queries

---

server/services/store/mattermostauthlayer/mattermostauthlayer.go

This PR fixes the issue, by updating the `team_member` query to only include Open Boards. Because the `team_member` query should be used to allow access to Open Boards to team members. Also the `channel_members` and `board_members` queries should NOT return Open Boards.
The rest of the PR was for clean-up, simplification. Since we now have simple queries. `includePublicBoards` means include the `team_members` query. If the User is a guest. Don't include the `channel_members` query. 
`includePublicBoards` and `user.IsGuest` are handled separately. However, currently, both are always either true or false. 
Fixes https://github.com/mattermost/focalboard/issues/4333

Update query to only allow open boards for team members

---

webapp/i18n/en.json
webapp/src/components/__snapshots__/centerPanel.test.tsx.snap
webapp/src/components/table/__snapshots__/table.test.tsx.snap
webapp/src/components/table/__snapshots__/tableRow.test.tsx.snap
webapp/src/components/table/__snapshots__/tableRows.test.tsx.snap
webapp/src/components/table/tableRow.tsx

This PR add's tooltip for the menu in Table view with title `More actions`
Fixes https://github.com/mattermost/focalboard/issues/4280

ToolTip for Table view menu

---

linux/go.mod
linux/go.sum
mattermost-plugin/go.mod
mattermost-plugin/go.sum
server/go.mod
server/go.sum

After https://github.com/mattermost/mattermost-server/pull/21853 merged, we need to update the server dependency.

go.mod: update mattermost-server dependency

---

webapp/src/components/content/attachmentElement.tsx

This PR fixes the transparency issue of the name of the attachment and the menu `...`
Fixes https://github.com/mattermost/focalboard/issues/4240

Fixed the length

---

server/app/boards.go
server/app/boards_test.go

When duplicating a board, whether from a template or not, we move the new board to the old board's category. When creating a template from a board, we were assigned a category to the template, which later was assigned to the board created from this template. Not assigning a category to the template stops the chain and causes the new board to be moved to the default category.
Fixes #3938

Don't set cattegory for board template

---

mattermost-plugin/server/boards/boardsapp.go
server/services/store/sqlstore/migrate.go
server/services/store/sqlstore/params.go
server/services/store/sqlstore/sqlstore.go

Use standard settings for initiating a connection for migrations. In both product and plugin mode, boards should use the settings from mattermost-server.
https://mattermost.atlassian.net/browse/MM-49352

services/store: use mattermost sql settings for migration connections

---

mattermost-plugin/server/boards/boards_service_api.go

This PR adds `DuplicateBoard` to the Boards service API.
mm-server PR: 
NONE

Add DuplicateBoard to service API

---

mattermost-plugin/product/boards_product.go
mattermost-plugin/server/boards/boards_service_api.go
server/app/app.go
server/app/permissions.go
server/model/board.go

Cherry-pick of https://github.com/mattermost/focalboard/pull/4372 and https://github.com/mattermost/focalboard/pull/4400 to rolling-stable since they were breaking API changes.
NONE

Cherry pick pr4400 rolling stable

---

mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoardItem.test.tsx.snap
mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoards.test.tsx.snap

Date format changed because these dates are now "last year", the years is now displayed.
Update snapshots to fix.

Update snapshots for date format

---

mattermost-plugin/webapp/webpack.config.js

This is fixes the caching issue that Christopher reported earlier and that some others have reported over the last while as well. Basically, the product version of Boards was generating chunks with non-unique file names causing some people to get weeks old versions of Boards on community. This was never a problem with the plugin version since, even though it just generates a consistently-named `bundle.js`, the MM server would give it a unique name instead.
https://mattermost.atlassian.net/browse/MM-49637

MM-49637 Make chunk filenames generated for MPA unique

---

mattermost-plugin/server/boards/boardsapp_util.go

Changes the base URL for the server from '/plugins/focalboard' to '/boards'
This fixes the "Page not found" error in links when linking/unlinking a board. But does NOT fix the issue with Shared Boards.
Fixes https://github.com/mattermost/focalboard/issues/4441

Change board serverRoot from '/plugins/focalboard' to '/boards'

---

webapp/src/components/viewHeader/__snapshots__/filterEntry.test.tsx.snap
webapp/src/components/viewHeader/filterEntry.test.tsx
webapp/src/components/viewHeader/filterEntry.tsx
webapp/src/octoUtils.test.ts
webapp/src/octoUtils.tsx

When a user selects a new property, the condition does not change. This results in the actual filter clause not being what is expected. This PR will update the condition to a default if the existing condition is not valid for that property.
Fixes https://github.com/mattermost/focalboard/issues/4445

Update the filter condition if property changes and not supported

---

mattermost-plugin/server/boards/configuration.go

Check the ProductSettings.EnablePublicSharedBoards config setting.
Did not remove original check, so not feature flag check is needed.
Fixes #4481

Update configuration to use 'ProductSettings.EnablePublicSharedBoards'

---

server/services/notify/plugindelivery/subscription_deliver.go

This PR fixes a crashing bug in Boards notification system in MPA mode. When a notification is sent, it first gets or creates a channel between the Boards bot and the user to be notified. Previously this used the `GetDirectChannel` method in the plugin API. That method gets or creates the channel. The product API version of that call only gets the channel and will not create it if not found. To make matters worse, the `getDirectChannel` method in the mm-server app layer swallows the `NotFoundError` and returns `nil, nil`. The Boards code was not expecting a nil channel when there is no error since that that could not happen as a plugin.  
This is a quick fix to ensure mm-server does not crash.  A proper fix will be submitted that requires PRs for Boards and mm-server. …

Fix panic when notifying of block change (getDirectChannel returning nil,nil)

---

webapp/src/boardUtils.ts

Several of our templates have been created with different options over time. That has resulted in some invalid date in the templates and missing option ids. Currently, we display an error when an option id isn't found. However, there is no action to take and this is a benign error, this PR removes the error.
Fixes https://github.com/mattermost/focalboard/issues/3846

Suppress error message on unfound option id

---

mattermost-plugin/product/api_adapter.go
mattermost-plugin/server/api_adapter.go
mattermost-plugin/server/manifest.go
server/model/mocks/mockservicesapi.go
server/model/services_api.go
server/services/notify/plugindelivery/plugin_delivery.go
server/services/notify/plugindelivery/subscription_deliver.go
server/services/notify/plugindelivery/user_test.go

There is a bug in Boards notification system in MPA mode. When a notification is sent, it first gets or creates a channel between the Boards bot and the user to be notified. Previously this used the GetDirectChannel method in the plugin API. That method gets or creates the channel. The product API version of that call only gets the channel and will not create it if not found. 
This PR fixes the issue by calling the newly added GetDirectChannelOrCreate product API.  Requires the [matching mm-server PR](https://github.com/mattermost/mattermost-server/pull/22112) to be merged first.
https://mattermost.atlassian.net/browse/MM-49752

Use GetDirectChannelOrCreate when notifying block chg in MPA mode

---

webapp/src/components/cardDialog.scss
webapp/src/components/dialog.scss
webapp/src/components/kanban/kanban.scss

Updating card dialog modal to not go 100% height
Also fixes:
https://github.com/mattermost/focalboard/issues/4500
https://github.com/mattermost/focalboard/issues/4509
https://github.com/mattermost/focalboard/issues/4493
Fixes https://github.com/mattermost/focalboard/issues/4500
Fixes https://github.com/mattermost/focalboard/issues/4509
Fixes https://github.com/mattermost/focalboard/issues/4493
Current:
Fix:

Multiple UI Fixes (Modals and person property label)

---

server/app/import.go
server/app/import_test.go

Only users in the import file are being created. The importing user should always be added as an admin to the imported boards.
Found while investigating...
#4532 and #4524

add admin user on import

---

webapp/src/components/markdownEditorInput/entryComponent/entryComponent.tsx

The BotsBadge we use from windows Components was updated [here](https://github.com/mattermost/mattermost-webapp/pull/11100).
As part of the update, 
- removed the `show` prop and instead added conditional rendering to where it got used
This PR adds conditional rendering instead of passing the property to the component.
Fixes https://github.com/mattermost/focalboard/issues/4520

GH-4520 - Check isBot property before displaying BotBadge

---

webapp/src/properties/date/date.tsx

When updating the date, the caller's <Table> object gets recreated causing the modal to close.
Rather than update the property value with every change, only update once the modal window closes. This keeps the modal open until date changes are complete. 
This works similar to a text field which doesn't update until the changes are complete, it doesn't update with each keystroke. 
Fixes https://github.com/mattermost/focalboard/issues/4475

GH-4475 - Save date change to database when closing form

---

webapp/src/components/sidebar/sidebarCategory.tsx

All menues in the LHS are `fixed={true}` as that's the best way to display a menu in an overflow limited container. The menu for categories was missing the `fixed` prop, adding which resolves the issue.
Fixes #4553

Fixed category menu position

---

webapp/src/widgets/menu/menu.scss

A css change for another issue(https://github.com/mattermost/focalboard/pull/4411) started using an ID in a NOT() operation which caused the css specificity to change. Because of that change the "shareboard.css" gets overwritten rather than being the final css.
This PR changes to use the specific classes used by menu.tsx, which allows the specificity to remain the same. 
Fixes https://github.com/mattermost/focalboard/pull/4411

use specific class, rather than NOT an unrelated ID

---

mattermost-plugin/server/manifest.go
server/services/store/sqlstore/schema_table_migration.go

A number of support tickets have been due to full migrations being run on existing Sqlite databases when upgrading.  There are only a few causes for the server to think a complete set of migrations is needed.  
1.  The schema_migrations table is empty
2.  The schema_migrations table has a column named `dirty`, forcing a schema migration for Morph 
3.  The schema_migrations table is missing
Point 3 would result in an error being logged.  
The most likely cause is item 2 since we have observed issues deleting columns in Sqlite.  Instead of checking for a column named `dirty` to ensure it was deleted, this PR modifies the check to look for a column named `name` to determine if a schema migration is needed on the schema_migrations table.  The `name` column was added for Morph, and is more …

Use `name` column to determine if schema_migrations table is correct format

---

server/services/notify/notifysubscriptions/diff2slackattachments.go
server/utils/callbackqueue.go
server/ws/plugin_adapter.go

This PR makes a few minor improvements to logging:
1. change log level for `appendContentChanges` to trace to reduce debug  noise
2. force a stack trace for the notify callback panic handler
3. change log level for `BroadcastingBlockChange` to trace to reduce debug  noise
Will be cherry-picked to mono-repo branch
NONE

Minor improvements to logging

---

mattermost-plugin/server/manifest.go
mattermost-plugin/webapp/src/components/__snapshots__/rhsChannelBoards.test.tsx.snap
mattermost-plugin/webapp/src/components/rhsChannelBoards.test.tsx
mattermost-plugin/webapp/src/components/rhsChannelBoards.tsx
mattermost-plugin/webapp/src/index.tsx
server/api/users.go
server/app/user.go
server/app/user_test.go
server/integrationtests/clienttestlib.go
server/model/permission.go
webapp/src/components/boardsSwitcher/boardsSwitcher.tsx
webapp/src/components/table/table.scss
webapp/src/constants.ts
webapp/src/octoClient.ts

Implement Channel members check before allowing to add linked board. 
User must have 'create-post' permission in order to create posts.
https://docs.google.com/document/d/1H5ocQMKz-6tlJJKAohuUNFcT05f-YfZbkKJkOzbTnBo/edit

Fix for users adding board links to Read-only channels

---

mattermost-plugin/webapp/webpack.config.js

With Playbooks moving to MPA, we're running into some errors that cause either one of Boards or Playbooks to fail to load. It seems like it was happening due to an issue with the resolution of shared modules by module federation. Specifically, it seems to be due to how it was trying to choose which version of those shared modules to use between the ones bundled with the web app, Boards, and Playbooks.
Since I've been trying to make the web app the authority for these dependencies, I just changed it so that the builds for both Boards and Playbooks will never include "fallback" versions of React and such since we know they'll always exist in the web app.
https://mattermost.atlassian.net/browse/MM-50818
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1826 …

MM-50810 Fix module loading issues caused by shared modules

---

mattermost-plugin/webapp/src/components/createBoardFromTemplate.tsx

Use the reference id value instead of the component state value when validating the id of the template inside the action function sent from the plugin to the webapp.
https://mattermost.atlassian.net/browse/MM-50804
Before:
https://user-images.githubusercontent.com/10082627/221557657-4b71d0e6-242d-42c6-b559-d8bcdf3dcc9c.mov
After:
https://user-images.githubusercontent.com/10082627/221557703-efa57845-de2f-4a83-96bd-36c68fd70699.mov

MM-50804 - add reference to template id to action function

---

server/app/boards.go
server/app/boards_test.go
webapp/src/properties/url/url.tsx

When patching a board, ensure a user can Post to a channel before allowing the linking to occur. This will ensure the user is a member of the channel and not a read-only user.
Fixes https://mattermost.atlassian.net/browse/MM-51062

check permissions to channel before patching via api

---

Makefile
webapp/src/components/sidebar/sidebarCategory.scss

Set the color for sidebar dialog box. Currently defaults to Sidebar Color `rgb(var(--sidebar-text-rgb))`, which cannot be seen in normal color scheme.
Fixes https://github.com/mattermost/focalboard/issues/4649
```release-note
Fixes issue with Delete Category Dialog message not visible
```

Fix category dialog

---

server/api/files.go

Copy writeFileResponse code from server back to boards code base.
This code is safer than previous implementation, but we don't want to depend on the server code for this, this change is not needed in plugin implementation. 
Also fixes an issue displaying images from templates. 
Fixes https://github.com/mattermost/focalboard/issues/4637

copy safe writeFileResponse into personal server/desktop

---

.github/workflows/ci.yml
.github/workflows/dev-release.yml
.github/workflows/lint-server.yml
.github/workflows/prod-release.yml

This PR updates the default `mattermost-server` reference to be pulled if a test run doesn't have a branch on the server repo. The reference now points to the commit pre-mono-repo, so the code can build and test can run normally.
This fixes CI for `main` and for the PRs of both new fixes and cherry-picks to the release branches we're still maintaining

Fix CI after mono-repo

---

.github/workflows/ci.yml
.github/workflows/dev-release.yml
.github/workflows/lint-server.yml
.github/workflows/prod-release.yml

Github deprecating ubuntu 18.04, use latest.
https://github.com/actions/runner-images/issues/6002
> Workflows using the ubuntu-18.04 image label should be updated to ubuntu-latest, ubuntu-20.04, or ubuntu-22.04

update ubuntu to latest

---

server/services/store/sqlstore/schema_table_migration.go

Fix `isSchemaMigrationNeeded` for postgres when running under Perseus.

Fix schema migration check for postgres

---

server/api/files.go
server/ws/server.go
server/ws/server_test.go

Fixes issue where an update from one user causes cascading updates back and forth. Fix is to only send Category/CategoryBoards update to user. Categories are now individual, not teams.
Fixes https://github.com/mattermost/focalboard/issues/4644

only send category updates to user

---

server/api/files.go

This PR fixes a panic in the Boards Rest API for fetching files.  It panics if the `app.getFile` call returns an error other than `not found`.
The panic is caught and handled, but it is logged and thus is [reported by customers](https://community.mattermost.com/private-core/pl/pqnrooyqj3b9fcz7ktq46rkshr) as a crash.  It also returns the wrong error to the client.
https://mattermost.atlassian.net/browse/MM-51885
Fixes https://github.com/mattermost/focalboard/issues/4691
```release-note
Fixes an innocuous panic in Boards Rest API when requesting files and a error other than `not found` is encountered.
```

Avoid panic in file request handler on error

---

server/api/files.go

Cherry-pick of https://github.com/mattermost/focalboard/pull/4693
This PR fixes a panic in the Boards Rest API for fetching files.  It panics if the `app.getFile` call returns an error other than `not found`.
The panic is caught and handled, but it is logged and thus is [reported by customers](https://community.mattermost.com/private-core/pl/pqnrooyqj3b9fcz7ktq46rkshr) as a crash.  It also returns the wrong error to the client.
https://mattermost.atlassian.net/browse/MM-51885
```release-note
Fixes an innocuous panic in Boards Rest API when requesting files and a error other than `not found` is encountered.
```

Cherry-pick MM-51885: Avoid panic in file request handler on error

---

webapp/src/wsclient.ts

Adds a reconnection retry count to the websocket client for Personal Server and Personal Desktop. Product client builds on top of the main Mattermost websockets client, so it doesn't require of any change.
https://github.com/mattermost/focalboard/issues/4632

Adds a retry count to the websocket re-open flow

---

webapp/src/hooks/permissions.tsx

Permissions were being returned as true for personal server, remove code so permissions are checked on the UI.
Fixes https://github.com/mattermost/focalboard/issues/4705

check permissions for personal server

---

webapp/src/components/kanban/kanban.tsx

Fixes issue so that dropping on cards has latest card data and doesn't lose recent changed.
Fixes https://github.com/mattermost/focalboard/issues/4719

fix so dropping on card has latest cards objects

---

server/auth/auth.go
server/integrationtests/permissions_test.go

Backport of https://github.com/mattermost/mattermost-server/pull/22921
The public boards setting was not applied properly. This fixes it so the setting will now apply to existing board links.
https://mattermost.atlassian.net/browse/MM-51820
```release-note
NONE
```

Fix public boards setting not applying properly

---

server/api/blocks.go
server/api/files.go
server/app/blocks.go
server/app/boards.go
server/app/export.go
server/app/files.go
server/app/files_test.go
server/app/import.go
server/app/import_test.go
server/app/templates_test.go
server/integrationtests/permissions_test.go
server/model/file.go
webapp/src/blocks/attachmentBlock.tsx
webapp/src/components/cardDialog.tsx
webapp/src/components/content/attachmentElement.test.tsx
webapp/src/components/content/attachmentElement.tsx

Backport of https://github.com/mattermost/mattermost-server/pull/22915
Initially intended to add attachment files to board exports (and handle the import of same). However, several other issues were discovered and fixed as well.
Duplicate Block (Card) - created the fileInfo object but did not duplicate the file. So all cards duplicated would share a single file.
Duplicate Board - it tried to copy files, but failed because it was only looking for files based on earlier path defined as `teamID/boardID/fileName`. It did not use fileInfo to look up file paths at all.
Both of there were fixed and made to share code along with updating during import.
Also added code to be able to retrieve the file path if the fileInfo row exists or use old file path if not. 
Fixes …

Backport fixes for import/export attachments and fixes

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dev-release.yml
.github/workflows/lint-server.yml
.github/workflows/prod-release.yml
.github/workflows/scorecards-analysis.yml

This PR updates the CI image from `ubuntu-latest` to `ubuntu-20.04` to compile pinning the latest LTS.
We should probably cherry-pick to `v7.11` and `v7.10`

Update ubuntu version to use latest LTS

---

server/auth/auth.go
server/integrationtests/permissions_test.go

Cherry pick of #4739 on release-7.8.
/cc  @sbishel
```release-note
NONE
```

Automated cherry pick of #4739

---

server/app/import.go

This PR updates the import reading logic to use a scanner. 
https://mattermost.atlassian.net/browse/MM-53232

Updates import to read with a scanner

---

server/services/store/sqlstore/blocks.go

Adds the `parent_id` filter to the query that fetches the blocks to get `fileId`s and `attachmentId`s and prevents soft deleting more `FileInfo`s than intended.
https://mattermost.atlassian.net/browse/MM-53713

Filter the fileinfo deletion query on block child deletion

---

mattermost-plugin/webapp/webpack.config.js

The Boards plugin has been trying to load the fonts that it packages from the wrong place for a while now. These fonts aren't actually necessary because the MM web app also loads the same fonts from a different location (`/static/<some-hash>.woff2`), but I figured it would be less likely to break something if I fixed that instead of removing the CSS that includes that font file.
https://mattermost.atlassian.net/browse/MM-41813

MM-41813 Fix path to fonts loaded by plugin

---

docs/board-metrics.md
docs/create-new-board.md
docs/dev-tips.md
docs/focalboard-dev-guide.md
docs/focalboard-plugin-end-user-guide.md
docs/get-started-with-board-templates.md
docs/group-filter-sort-boards.md
docs/import-export-backup-data.md
docs/index.md
docs/link-boards-to-mattermost-channels.md
docs/manage-boards.md
docs/manage-plugin-preferences.md
docs/plugin-data-being-collected.md
docs/share-collaborate.md
docs/work-with-board-views.md
docs/work-with-cards.md

Migrates Mattermost Boards product documentation to the Focalboard plugin GitHub repository. 
Also addresses the following by not merging the related content:
- https://github.com/mattermost/mattermost/pull/24223 
Docs PR https://github.com/mattermost/docs/pull/6498 pulls Boards content from docs.mm.com

Transitioning Mattermost Boards > Focalboards plugin docs

---

server/api/users.go
server/client/client.go
server/integrationtests/pluginteststore.go
server/integrationtests/user_test.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go

Guests should only have access to other members if they are both members of the same channel or board. This PR enforces that on the '/user' post endpoint. Also required fixing queries.
Fixes https://mattermost.atlassian.net/browse/MM-54366

MM-54366 Check guest access to other members

---

server/api/users.go
server/client/client.go
server/integrationtests/pluginteststore.go
server/integrationtests/user_test.go
server/services/store/mattermostauthlayer/mattermostauthlayer.go

Cherry pick of #4884 on release-7.8.
/cc  @mattermost-build
```release-note
NONE
```

Automated cherry pick of #4884

---

mattermost-plugin/plugin.json
mattermost-plugin/server/manifest.go
server/model/version.go
webapp/package-lock.json
webapp/package.json
webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
webapp/src/constants.ts

Update to version 8.0 that includes all plugin dependency updates including to latest Mattermost server models. 
https://github.com/mattermost/focalboard/pull/5009
https://github.com/mattermost/focalboard/pull/5008
https://mattermost.atlassian.net/browse/MM-58682

Update to version 8.0

---

docker-testing/docker-compose-mysql.yml
webapp/i18n/en.json
webapp/package-lock.json
webapp/package.json
webapp/src/components/__snapshots__/contentBlock.test.tsx.snap
webapp/src/components/content/__snapshots__/textElement.test.tsx.snap
webapp/src/components/content/textElement.scss
webapp/src/components/content/textElement.tsx

Fixes: https://mattermost.atlassian.net/browse/MM-58502
This PR implements a client-side check for the block limit on the card. Instead of failing silently without any error message, the front end will display an error if the block limit is exceeded.
User flow: 
- An error will be shown if the user crosses the block limit on the client side. 
- Error will persist if the user loses the focus from the block and no API call will be made. 
- If users close the card with an error then the data will be lost. 
https://github.com/mattermost/focalboard/assets/26198062/1abc8038-7005-4204-b808-c8ae3d3b19e6
I also updated the `mysql/mysql-server` docker version because version `5.7.12` was deprecated.

MM-58502 Error on crossing block limit on client side

---

README.md

Remove references to boards plugin from README.

Remove references to boards plugin from README
